import { getAudioPackConfig, buildAudioPricingPresentation } from '@/lib/audio-generation';
import { listBillingProducts, computeBillingProductSnapshot } from '@/lib/billing-products';
import { loadPricingPolicyOverrides } from '@/lib/pricing-rule-store';
import { getFalEngineById } from '@/config/falEngines';
import { ANGLE_TOOL_ENGINES } from '@/config/tools-angle-engines';
import { ANGLE_MULTI_OUTPUT_COUNT, estimateAngleCostUsd, getAngleBillingProductKeyForEngine } from '@/lib/tools-angle';
import { getCharacterFormatResolution, getQualityEngineId } from '@/lib/character-builder';
import { getBillingProductKey } from '@/server/tools/character-builder/utils';
import { buildBillingPricingFacts } from '@/lib/pricing-billing-facts';
import type { PricingContext } from '@/lib/pricing-context';
import { UPSCALE_TOOL_ENGINES } from '@/config/tools-upscale-engines';
import { getBackgroundRemovalToolEngine } from '@/config/tools-background-removal-engines';
import { estimateImageUpscaleCostUsd } from '@/lib/tools-upscale';
import { FINISHING_PROFILES, estimateFinishingVendorBudget } from '@/server/tools/finishing-providers';
import { FINISHING_TOOL_IDS, FINISHING_QUALITY_CHOICES, defaultFinishingSettings, finishingSettingsSchemas } from '@/lib/toolbox/finishing';
import { isFinishingProfileReleased } from '@/server/tools/finishing-release';
import { resolveUpscalePricingContext } from '@/server/tools/upscale-pricing-context';
import { resolveBackgroundRemovalPricingContext } from '@/server/tools/background-removal-pricing-context';
import { computeCanonicalAudioBillingSnapshot, computeCanonicalBillingSnapshot, computeCanonicalStoryboardBillingSnapshot, computeCanonicalFinishingBillingSnapshot } from '@/server/pricing/quote-billing';
import type { ProductPricingInventory, ProductPricingRow } from '@/lib/admin/product-pricing-contract';
import { listReferencedBillingProductKeys } from './billing-product-service';
import { buildAdminAudioReferenceInputs } from './product-policy-scenarios';
import { catalogSupplierReference } from './catalog-supplier-reference';
import { resolveDynamicToolPriceMultiplier } from '@/lib/tools-dynamic-pricing';

/** Bounded comparison scenarios only. No media reads, submissions, charges or schema writes. */
export async function loadAdminProductPricing(durationSec = 10): Promise<ProductPricingInventory> {
  const rows: ProductPricingRow[] = [];
  const warnings: string[] = [];
  const policy = await loadPricingPolicyOverrides();
  const pricingPolicy = { loadOverrides: async () => policy };
  const capture = async (row: ProductPricingRow, quote: () => Promise<{ totalCents: number; currency: string }>) => {
    try {
      if (policy.status !== 'loaded' && row.policySelector) throw new Error('Effective policy unavailable');
      const snapshot = await quote();
      row.totalCents = snapshot.totalCents;
      row.currency = snapshot.currency;
      if (snapshot.currency !== 'USD') { row.supplierCents = null; row.notes.push('Supplier reference is in USD; currency conversion is not assumed.'); }
    } catch (error) {
      row.totalCents = null;
      row.notes.push(error instanceof Error && error.message === 'TOOL_PRICING_UNAVAILABLE'
        ? 'No tool-specific effective pricing rule. The global legacy rule is intentionally rejected for this product.'
        : 'Current quote unavailable.');
    }
    rows.push(row);
  };
  for (const { id, label, input } of buildAdminAudioReferenceInputs(durationSec)) {
      const config = getAudioPackConfig(input.pack);
      const seconds = input.durationSec;
      const facts = buildAudioPricingPresentation(input);
      await capture({ id, category: 'audio', label,
        scenario: input.pack === 'song' ? '1 song · output duration generated by the provider'
          : input.voiceModel === 'minimax' ? `1,000 characters${config.requiresVideo ? ` · ${seconds} s source video` : ''}` : `${seconds} s${config.requiresVideo ? ' · source video reference' : ''}`,
        currency: 'USD', totalCents: null, supplierCents: facts.vendorSubtotalCents, supplierBasis: 'catalogue',
        quantity: input.voiceModel === 'minimax' || input.pack === 'song' ? 1 : facts.durationSec,
        unit: input.pack === 'song' ? 'song' : input.voiceModel === 'minimax' ? '1k chars' : 's',
        policySelector: { engineId: 'audio-generation', mode: input.pack, resolution: 'audio' },
        notes: [`Provider billing unit: ${facts.base.unit ?? 'audio'}.${input.voiceModel !== 'minimax' && input.pack !== 'song' ? ' Displayed /s is a comparison rate.' : ''}`,
          `Catalogue estimate; contract and invoice unconfirmed. This policy applies to all variants of the ${input.pack} pack.`] },
        () => computeCanonicalAudioBillingSnapshot(input, { pricingPolicy }));
  }
  try {
    const keys = listReferencedBillingProductKeys();
    const products = (await listBillingProducts()).filter((product) => keys.has(product.productKey));
    for (const product of products) {
      const engine = UPSCALE_TOOL_ENGINES.find((item) => item.billingProductKey === product.productKey);
      const background = product.surface === 'background-removal' ? getBackgroundRemovalToolEngine() : null;
      const seconds = Math.min(durationSec, 60);
      const metadata = { width: 1280, height: 720, durationSec: seconds, fps: 30 };
      const row: ProductPricingRow = { id: product.productKey, category: 'tools', label: product.label,
        scenario: engine?.mediaType === 'video' ? `${seconds} s · 720p source · 30 fps → ${engine.defaultTargetResolution ?? '2×'}`
          : background ? `${seconds} s · WebM VP9` : `1 ${product.unitKind}`,
        currency: product.currency, totalCents: null, supplierCents: null, supplierBasis: 'unknown',
        quantity: engine?.mediaType === 'video' || background ? seconds : 1,
        unit: engine?.mediaType === 'video' || background ? 's' : product.unitKind,
        billingProductKey: product.productKey, notes: [`Fixed ${engine?.mediaType === 'video' || background ? 'minimum' : 'unit price'}: ${product.unitPriceCents} cents.`,
          ...(product.active ? [] : ['Inactive product.']),
          ...(engine?.mediaType === 'video' || background ? [
            `Customer coefficient: ×${resolveDynamicToolPriceMultiplier(product.productKey, product.metadata)} on the processing estimate, subject to the fixed minimum.`,
            'Minimum and coefficient are editable together. Actual duration, dimensions and processing determine the final price; supplier contract and invoice remain unconfirmed.',
          ] : [])] };
      const characterQuality = (['draft', 'final'] as const).find((quality) => getBillingProductKey(quality) === product.productKey);
      const angle = ANGLE_TOOL_ENGINES.find((item) => [false, true].some((multi) => getAngleBillingProductKeyForEngine(item.id, multi) === product.productKey));
      if (characterQuality) {
        const character = getFalEngineById(getQualityEngineId(characterQuality));
        const resolution = getCharacterFormatResolution('standard', characterQuality);
        row.scenario = `1 image · ${resolution.toUpperCase()} · ${character?.marketingName ?? 'Character Builder'} · standard format`;
        const reference = character && catalogSupplierReference({ engine: character.engine, durationSec: 1, mode: 't2i', resolution });
        if (reference && product.currency === 'USD') {
          row.supplierCents = reference.amountUsd * 100;
          row.supplierBasis = 'catalogue';
        }
        row.notes.push(`Supplier reference: ${character?.marketingName ?? 'underlying image model'} · Google Vertex catalogue · ${resolution.toUpperCase()} output.`,
          'Catalogue estimate; contract and invoice unconfirmed. Standard format, one output; higher formats change provider resolution and customer billing quantity.');
      } else if (angle) {
        const count = product.productKey === getAngleBillingProductKeyForEngine(angle.id, true) ? ANGLE_MULTI_OUTPUT_COUNT : 1;
        row.scenario = `${count} image${count === 1 ? '' : 's'} · 1 MP source · 1 run`;
        if (product.currency === 'USD') {
          row.supplierCents = Number((estimateAngleCostUsd(angle.id, 1000, 1000) * count * 100).toFixed(6));
          row.supplierBasis = 'catalogue';
        }
        row.notes.push(`Supplier reference: ${angle.label} · Fal catalogue · ${count} provider call${count === 1 ? '' : 's'} at 1 MP each.`,
          'Catalogue estimate; contract and invoice unconfirmed. Actual cost depends on source dimensions; the customer price is fixed per run.',
          ...(angle.id === 'flux-multiple-angles' ? ['Negative tilt uses Qwen and its corresponding billing product in the app.'] : []));
      }
      if (product.currency !== 'USD') row.notes.push('Supplier reference is in USD; currency conversion is not assumed.');
      await capture(row, async () => {
        if (engine?.mediaType === 'video') {
          const result = await resolveUpscalePricingContext({ billingProductKey: product.productKey, engine,
            input: { mediaType: 'video' }, targetResolution: engine.defaultTargetResolution ?? '1080p',
            upscaleFactor: engine.defaultUpscaleFactor, videoMetadata: metadata });
          row.supplierCents = Number(result.pricing.meta?.providerEstimateUsd) * 100;
          row.supplierBasis = 'catalogue';
          return result.pricing;
        }
        if (background) {
          const result = await resolveBackgroundRemovalPricingContext({ billingProductKey: product.productKey, engine: background, outputCodec: 'webm_vp9', videoMetadata: metadata });
          row.supplierCents = background.providerPriceUsdPerSecond * seconds * 100;
          row.supplierBasis = 'catalogue';
          return result.pricing;
        }
        if (engine) {
          row.supplierCents = estimateImageUpscaleCostUsd({ engineId: engine.id, width: 1024, height: 1024, factor: engine.defaultUpscaleFactor }) * 100;
          row.supplierBasis = 'catalogue';
          row.notes.push('Supplier scenario: 1024 × 1024 source, default upscale factor.');
        }
        return computeBillingProductSnapshot({ productKey: product.productKey, quantity: 1 });
      });
    }
    if (products.length !== keys.size) warnings.push('Some referenced billing products are missing.');
  } catch { warnings.push('Billing product inventory unavailable.'); }
  const image = getFalEngineById('gpt-image-2');
  if (image) for (const operation of ['storyboard', 'storyboard_edit'] as const) for (const tier of ['hd', '4k', 'ultra'] as const) {
    const resolution = tier === 'hd' ? '1920x1080' : '3840x2160';
    const context: PricingContext = { engine: image.engine, durationSec: 1, mode: operation === 'storyboard_edit' ? 'i2i' : 't2i',
      resolution, quality: tier === 'ultra' ? 'high' : 'medium', referenceImageCount: operation === 'storyboard_edit' ? 1 : 0,
      membershipTier: 'member' };
    const facts = buildBillingPricingFacts(context, image.engine.pricingDetails, 'USD');
    const row: ProductPricingRow = { id: `${operation}:${tier}`, category: 'storyboard', label: operation === 'storyboard' ? 'Generate storyboard' : 'Edit storyboard',
      scenario: `${tier.toUpperCase()} · GPT Image 2 · 1 board · landscape`, currency: 'USD', totalCents: null,
      supplierCents: facts.base.amountCents, supplierBasis: 'catalogue', quantity: 1, unit: 'board',
      policySelector: { engineId: 'storyboarder', mode: operation }, notes: [
        `Supplier reference: GPT Image 2 · Fal catalogue · ${resolution} · ${context.quality} quality · ${operation === 'storyboard_edit' ? 'one source image' : 'no source images'}.`,
        'Catalogue estimate; contract and invoice unconfirmed. The storyboard quote uses the underlying image base cost and its own effective commercial policy.',
        'Reference scenario; image dimensions, quality and sources affect the final quote. Kling first-frame bundles have a separate combined quote.'] };
    await capture(row, async () => {
      const base = await computeCanonicalBillingSnapshot(context, { pricingPolicy });
      return computeCanonicalStoryboardBillingSnapshot({ snapshot: base, operation, tier }, { pricingPolicy });
    });
  }
  for (const toolId of FINISHING_TOOL_IDS) for (const quality of FINISHING_QUALITY_CHOICES[toolId]) {
    const profile = FINISHING_PROFILES[toolId][quality]!;
    const settings = finishingSettingsSchemas[toolId].parse({ ...defaultFinishingSettings(toolId), quality });
    const seconds = Math.min(durationSec, 60);
    const budgetUsd = estimateFinishingVendorBudget(toolId, settings, { width: 1280, height: 720, durationSec: seconds, fps: 30 });
    await capture({ id: `${toolId}:${quality}`, category: 'tools', label: `${toolId.replaceAll('-', ' ')} · ${quality}`,
      scenario: `${seconds} s · 720p · 30 fps${toolId === 'restore-video' ? ' → 1080p' : toolId === 'smooth-motion' ? ' → 60 fps' : ''}`, currency: 'USD', totalCents: null, supplierCents: budgetUsd * 100,
      supplierBasis: 'budget', quantity: seconds, unit: 's', policySelector: { engineId: 'toolbox-finishing', mode: `${toolId}:${quality}`, resolution: 'video' },
      notes: ['Conservative provider budget; not a verified per-frame rate or invoice.',
        toolId === 'restore-video' ? 'Budget depends on output resolution, source frame rate and quality.'
          : 'Budget rounds up to complete 300-frame blocks; source dimensions, frame rate and quality affect the quote.',
        'This editor changes only the selected tool and quality. Preview includes other source sizes, durations and priced output options.',
        isFinishingProfileReleased(profile, quality) ? 'Released profile.' : 'Profile not released for generation.'] },
      () => computeCanonicalFinishingBillingSnapshot({ toolId, quality, vendorBudgetUsd: budgetUsd, durationSec: seconds,
        profileId: profile.id, pricingSource: profile.pricingSource }, { pricingPolicy }));
  }
  if (policy.status !== 'loaded') warnings.push('Effective pricing policy unavailable; affected current prices are hidden.');
  return { rows, warnings };
}
