packages:
  - 'frontend'
  - 'packages/*'
allowBuilds:
  '@ffmpeg-installer/darwin-arm64': false
  '@ffmpeg-installer/linux-x64': true
  '@vercel/speed-insights': false
  bufferutil: true
  esbuild: true
  sharp: true
  unrs-resolver: false
