export type SeoWatchVideoConfig = {
  id: string;
  engineSlug: string;
  engineFamily: string;
  engineLabel: string;
  seoTitle: string;
  intro: string;
  reasonForSelection: string;
  priority: number;
  publishedAt: string;
};

export const VIDEO_SEO_WATCHLIST: readonly SeoWatchVideoConfig[] = [
  {
    id: 'job_665a317f-f4dc-41c8-ade4-4a0a891627c8',
    engineSlug: 'kling-3-pro',
    engineFamily: 'kling',
    engineLabel: 'Kling 3 Pro',
    seoTitle: 'Kling 3 Pro neon street multi-shot demo',
    intro: 'A premium Kling 3 Pro sequence that shows controlled multi-shot storytelling, neon reflections, and stable cinematic motion.',
    reasonForSelection: 'Flagship Kling 3 Pro multi-shot render with strong watch-page value.',
    priority: 240,
    publishedAt: '2026-02-10T14:09:32.617Z',
  },
  {
    id: 'job_3092cc94-f948-42e8-abd0-744534f5b38e',
    engineSlug: 'kling-3-pro',
    engineFamily: 'kling',
    engineLabel: 'Kling 3 Pro',
    seoTitle: 'Kling 3 Pro futuristic studio orb commercial',
    intro: 'A polished studio-style Kling 3 Pro render that highlights premium lighting, clean motion, and audio-aware commercial staging.',
    reasonForSelection: 'Premium commercial-style example with a clear hero subject and reusable prompt structure.',
    priority: 238,
    publishedAt: '2026-02-10T14:09:03.077Z',
  },
  {
    id: 'job_3f82e69d-ef44-4c46-aded-16d06dd4a1ab',
    engineSlug: 'seedance-1-5-pro',
    engineFamily: 'seedance',
    engineLabel: 'Seedance 1.5 Pro',
    seoTitle: 'Seedance 1.5 Pro tabletop product commercial',
    intro: 'A clean Seedance 1.5 Pro product spot built around controlled tabletop motion, precise framing, and high-end studio cues.',
    reasonForSelection: 'Strong product-demo watch page with commercial intent and reusable prompt patterns.',
    priority: 236,
    publishedAt: '2026-02-10T14:11:23.966Z',
  },
  {
    id: 'job_2a07e085-4764-4e9b-8850-c3941dbf303a',
    engineSlug: 'ltx-2-3-pro',
    engineFamily: 'ltx',
    engineLabel: 'LTX 2.3 Pro',
    seoTitle: 'LTX 2.3 Pro rooftop lightning fashion shot',
    intro: 'A dramatic LTX 2.3 Pro fashion render with strong subject isolation, weather effects, and cinematic rooftop atmosphere.',
    reasonForSelection: 'Flagship visual render with clear storytelling and high visual distinctiveness.',
    priority: 234,
    publishedAt: '2026-03-06T22:53:48.997Z',
  },
  {
    id: 'job_7fbd6334-8535-438a-98a2-880205744b6b',
    engineSlug: 'sora-2',
    engineFamily: 'sora',
    engineLabel: 'OpenAI Sora 2',
    seoTitle: 'Sora 2 smartwatch sunrise ad demo',
    intro: 'A polished Sora 2 lifestyle ad that showcases multi-shot pacing, product framing, and sunrise commercial energy.',
    reasonForSelection: 'Commercial hero render with strong product-search intent.',
    priority: 232,
    publishedAt: '2025-11-10T22:31:17.821Z',
  },
  {
    id: 'job_8547a19e-ebad-4376-8889-1d88355c0f52',
    engineSlug: 'veo-3-1',
    engineFamily: 'veo',
    engineLabel: 'Google Veo 3.1',
    seoTitle: 'Veo 3.1 earbud commercial sequence',
    intro: 'A Veo 3.1 audio-product spot with macro product framing, lifestyle context, and a clear multi-shot commercial structure.',
    reasonForSelection: 'High-intent demo for product-commercial and device-review searches.',
    priority: 230,
    publishedAt: '2025-11-22T22:55:03.920Z',
  },
  {
    id: 'job_20b54ee7-ec03-47d4-b1ca-2fef046093f8',
    engineSlug: 'sora-2-pro',
    engineFamily: 'sora',
    engineLabel: 'OpenAI Sora 2 Pro',
    seoTitle: 'Sora 2 Pro rainy runner motion test',
    intro: 'A Sora 2 Pro action render that makes motion handling easy to evaluate thanks to rain, reflections, and fast lateral tracking.',
    reasonForSelection: 'Strong motion-physics benchmark with clear watch intent.',
    priority: 228,
    publishedAt: '2026-02-02T13:15:26.558Z',
  },
  {
    id: 'job_a3e088db-b1e2-430f-83b3-2efce518c282',
    engineSlug: 'veo-3-1-fast',
    engineFamily: 'veo',
    engineLabel: 'Google Veo 3 Fast',
    seoTitle: 'Veo 3 Fast FPV apartment commercial',
    intro: 'A Veo 3 Fast fly-through ad with a strong point of view, commercial reveal, and easy-to-read interior transitions.',
    reasonForSelection: 'Distinctive cinematic concept suited to video-search clicks.',
    priority: 226,
    publishedAt: '2025-11-15T00:19:58.468Z',
  },
  {
    id: 'job_4b882003-b595-4d4e-b62c-1ae22f002bcf',
    engineSlug: 'wan-2-5',
    engineFamily: 'wan',
    engineLabel: 'Wan 2.5 Text & Image to Video',
    seoTitle: 'Wan 2.5 spy-to-Zoom comedy spot',
    intro: 'A playful Wan 2.5 short that opens like an action trailer, then lands a clear comedic reveal without losing pacing.',
    reasonForSelection: 'Memorable storytelling hook that can stand alone as a watch page.',
    priority: 224,
    publishedAt: '2025-11-16T18:54:16.098Z',
  },
  {
    id: 'job_b748b50c-30bc-42ba-a83b-208abbd4fb7f',
    engineSlug: 'seedance-1-5-pro',
    engineFamily: 'seedance',
    engineLabel: 'Seedance 1.5 Pro',
    seoTitle: 'Seedance 1.5 Pro rainy city reflections shot',
    intro: 'A controlled Seedance 1.5 Pro city render that emphasizes reflections, atmosphere, and premium night cinematography.',
    reasonForSelection: 'Flagship cinematic city example with broad search appeal.',
    priority: 222,
    publishedAt: '2026-02-10T14:11:06.094Z',
  },
  {
    id: 'job_a3197eac-62e4-4043-a0d6-7b62a8f57ff0',
    engineSlug: 'ltx-2-3-fast',
    engineFamily: 'ltx',
    engineLabel: 'LTX 2.3 Fast',
    seoTitle: 'LTX 2.3 Fast boxer arena tunnel shot',
    intro: 'A moody LTX 2.3 Fast sports render that uses sparks, tunnel depth, and restrained camera movement to create tension.',
    reasonForSelection: 'Strong cinematic character reveal with clean visual hierarchy.',
    priority: 220,
    publishedAt: '2026-03-06T22:55:41.605Z',
  },
  {
    id: 'job_f5992c71-a197-482f-8d0f-028f261ed27b',
    engineSlug: 'pika-text-to-video',
    engineFamily: 'pika',
    engineLabel: 'Pika 2.2 Text & Image to Video',
    seoTitle: 'Pika 2.2 pixel wizard loop demo',
    intro: 'A tight Pika 2.2 creative loop that proves pixel-art motion, repeating action, and stylized charm in a short watch page.',
    reasonForSelection: 'Distinctive creative format that broadens the watch-page portfolio.',
    priority: 218,
    publishedAt: '2025-11-22T23:00:03.145Z',
  },
  {
    id: 'job_0ec5b210-47ff-4eed-9a43-4b0061e20dc7',
    engineSlug: 'minimax-hailuo-02-text',
    engineFamily: 'hailuo',
    engineLabel: 'MiniMax Hailuo 02 Standard',
    seoTitle: 'Hailuo 02 rainy runner motion test',
    intro: 'A Hailuo 02 benchmark render focused on speed, reflections, and legible motion under difficult night-action conditions.',
    reasonForSelection: 'Comparable benchmark watch page for motion and action queries.',
    priority: 216,
    publishedAt: '2026-01-29T23:37:24.641Z',
  },
  {
    id: 'job_55c36d3f-8591-4e32-a6a3-dbf191706d18',
    engineSlug: 'sora-2',
    engineFamily: 'sora',
    engineLabel: 'OpenAI Sora 2',
    seoTitle: 'Sora 2 vertical creator selfie promo',
    intro: 'A short Sora 2 vertical watch page built for UGC-style pacing, direct-to-camera delivery, and social-first clarity.',
    reasonForSelection: 'Vertical UGC proof point with strong user-facing value.',
    priority: 214,
    publishedAt: '2026-02-02T12:16:37.028Z',
  },
  {
    id: 'job_b197fc68-0bb7-4a24-9720-0ff721642446',
    engineSlug: 'veo-3-1',
    engineFamily: 'veo',
    engineLabel: 'Google Veo 3.1',
    seoTitle: 'Veo 3.1 vertical creator explainer',
    intro: 'A Veo 3.1 vertical creator clip that makes selfie realism, speech framing, and mobile-first delivery easy to judge.',
    reasonForSelection: 'UGC-style watch page with clear social-video intent.',
    priority: 212,
    publishedAt: '2026-02-02T12:16:25.022Z',
  },
  {
    id: 'job_0a9ee690-d91d-499d-817e-dccec23d8c9e',
    engineSlug: 'kling-3-pro',
    engineFamily: 'kling',
    engineLabel: 'Kling 3 Pro',
    seoTitle: 'Kling 3 Pro vertical creator promo',
    intro: 'A compact Kling 3 Pro vertical clip that demonstrates direct-to-camera delivery, social framing, and creator-style motion.',
    reasonForSelection: 'Vertical proof point that complements Kling flagship cinematic renders.',
    priority: 210,
    publishedAt: '2026-02-10T12:45:22.036Z',
  },
  {
    id: 'job_7bfe7823-5794-4a41-9869-2bb4458a9bc7',
    engineSlug: 'wan-2-6',
    engineFamily: 'wan',
    engineLabel: 'Wan 2.6 Text & Image to Video',
    seoTitle: 'Wan 2.6 vertical creator demo',
    intro: 'A Wan 2.6 vertical watch page focused on handheld-feel creator delivery and clean speech-to-camera framing.',
    reasonForSelection: 'Social-video candidate with clear standalone value.',
    priority: 208,
    publishedAt: '2026-02-02T12:17:51.566Z',
  },
  {
    id: 'job_f94d62e7-4b15-446e-b43a-319d8bfde3f3',
    engineSlug: 'seedance-1-5-pro',
    engineFamily: 'seedance',
    engineLabel: 'Seedance 1.5 Pro',
    seoTitle: 'Seedance 1.5 Pro vertical creator ad',
    intro: 'A Seedance 1.5 Pro vertical clip built to evaluate natural creator framing, pacing, and mobile-first presentation.',
    reasonForSelection: 'Vertical UGC reference that broadens Seedance intent coverage.',
    priority: 206,
    publishedAt: '2026-02-10T12:43:27.570Z',
  },
  {
    id: 'job_d2e0b731-ba85-498b-bf45-a1b17b468963',
    engineSlug: 'ltx-2-3-pro',
    engineFamily: 'ltx',
    engineLabel: 'LTX 2.3 Pro',
    seoTitle: 'LTX 2.3 Pro vertical creator pitch',
    intro: 'A vertical LTX 2.3 Pro example that gives a clean read on creator-style realism, framing, and social-ready delivery.',
    reasonForSelection: 'Vertical watch page that complements LTX cinematic entries.',
    priority: 204,
    publishedAt: '2026-03-06T23:09:18.906Z',
  },
  {
    id: 'job_df68f2a6-4223-4721-811c-efb85de01c46',
    engineSlug: 'pika-text-to-video',
    engineFamily: 'pika',
    engineLabel: 'Pika 2.2 Text & Image to Video',
    seoTitle: 'Pika 2.2 vertical creator demo',
    intro: 'A short Pika 2.2 creator clip that makes direct-to-camera pacing and vertical composition easy to evaluate.',
    reasonForSelection: 'Vertical UGC proof point for Pika.',
    priority: 202,
    publishedAt: '2026-02-02T12:17:05.676Z',
  },
  {
    id: 'job_be5bff74-eec5-4fb9-80c7-e6f28d317cb7',
    engineSlug: 'minimax-hailuo-02-text',
    engineFamily: 'hailuo',
    engineLabel: 'MiniMax Hailuo 02 Standard',
    seoTitle: 'Hailuo 02 vertical creator demo',
    intro: 'A Hailuo 02 vertical clip built for creator-style delivery, selfie realism, and social-ready composition.',
    reasonForSelection: 'Vertical watch page that improves intent diversity for Hailuo.',
    priority: 200,
    publishedAt: '2026-02-02T12:18:02.329Z',
  },
  {
    id: 'job_2c795d5a-f8fb-4359-9d15-fbc65678327d',
    engineSlug: 'wan-2-6',
    engineFamily: 'wan',
    engineLabel: 'Wan 2.6 Text & Image to Video',
    seoTitle: 'Wan 2.6 full-body gadget unboxing',
    intro: 'A Wan 2.6 product-demo render with a full-body presenter, clear object handling, and stable studio composition.',
    reasonForSelection: 'Useful product-demo watch page with strong commercial intent.',
    priority: 198,
    publishedAt: '2026-02-02T12:40:16.556Z',
  },
  {
    id: 'job_2c958e35-92e7-4c0f-8828-ec49476c8c4e',
    engineSlug: 'pika-text-to-video',
    engineFamily: 'pika',
    engineLabel: 'Pika 2.2 Text & Image to Video',
    seoTitle: 'Pika 2.2 moody portrait turn',
    intro: 'A minimal Pika 2.2 portrait study that isolates facial motion, fog, and cinematic mood in a short watch page.',
    reasonForSelection: 'Simple but strong portrait-motion example with clear visual focus.',
    priority: 196,
    publishedAt: '2026-01-18T10:13:44.431Z',
  },
  {
    id: 'job_96c348e2-cce5-4d09-9340-25bbe74d9873',
    engineSlug: 'minimax-hailuo-02-text',
    engineFamily: 'hailuo',
    engineLabel: 'MiniMax Hailuo 02 Standard',
    seoTitle: 'Hailuo 02 studio gadget unboxing',
    intro: 'A clean Hailuo 02 unboxing render with a visible presenter, clear tabletop action, and straightforward product-commercial framing.',
    reasonForSelection: 'Commercial product-demo watch page for Hailuo coverage.',
    priority: 194,
    publishedAt: '2026-02-02T12:39:58.653Z',
  },
] satisfies readonly SeoWatchVideoConfig[];
