export const DEFAULT_BILLING_COPY = {
  title: 'Billing',
  hero: {
    title: 'Add credits',
    subtitle: 'Choose an amount, then complete payment in secure Stripe Checkout.',
    liveMode: 'Live Mode',
    testMode: 'Test Mode',
  },
  wallet: {
    title: 'Wallet',
    addCreditsTitle: 'Add credits',
    description: 'Your balance pays for successful renders only. Unused credits stay in your wallet.',
    balanceLabel: 'Current balance',
    balanceReady: 'Available to create',
    balanceLoading: 'Loading balance…',
    balanceRefreshing: 'Refreshing balance…',
    balanceUnavailable: 'Balance unavailable. Try again.',
    guestBalance: 'Sign in to view your balance',
    refreshBalance: 'Refresh balance',
    stepChoose: 'Choose wallet credits',
    stepChooseHint: 'Credits are stored in USD and do not expire while your account remains active.',
    stepReview: 'Review payment',
    stepReviewHint: 'Pay in EUR or USD. Your bank may charge currency conversion fees.',
    paymentAmount: "Amount before tax",
    creditsReceived: 'Credits received',
    quoteCurrent: "Tax may be added. You will see the final total before confirming payment.",
    quoteUnavailable: 'Finalized in Stripe Checkout',
    addFunds: '{amount}',
    quickAmount: '{amount}',
    selectedAmount: 'Selected amount',
    checkoutCta: "Card or other methods",
    checkoutSecure: 'Secure payment by',
    checkoutNote: "Credits are added after confirmation; your receipt is saved here.",
    customLabel: 'Custom amount',
    customPresetLabel: 'Custom',
    customPresetHint: 'Enter amount',
    customPlaceholder: 'Minimum $10',
    customHint: 'Enter any amount from $10.',
    customCta: 'Set amount',
    customSelectCta: 'Set amount',
    customInvalid: 'Enter a valid amount.',
    customMin: 'Minimum is $10.',
    chooseAmount: 'Select',
    expressTitle: "Pay instantly",
    expressLoading: "Loading secure payment options…",
    expressUnavailable: "Instant payment is unavailable. Choose another payment method below.",
    expressError: "Unable to open instant payment. Choose another payment method below.",
    expressClosed: "Payment window closed. Try again or choose another method below.",
    expressAriaLabel: 'Express checkout',
    captchaPrompt: 'Security check required before Checkout.',
    captchaComplete: 'Security check complete. Continue to payment.',
    captchaError: 'Security check unavailable. Try again.',
    rateLimited: 'Too many payment attempts. Try again in {time}.',
    autoTopUp: 'Enable auto top-up (optional)',
    lowBalance: 'Your balance is low. Top up to keep creating.',
    currencyLabel: "Pay in",
    currencyLoading: 'Detecting currencies…',
    currencyLoadError: 'Unable to load currencies. Defaulting to USD.',
    currencyDetected: 'Auto-detected {currency}',
    currencyOverride: 'Charging in {selected} (auto: {detected})',
    quoteLoading: "Calculating amount…",
    quoteError: 'Unable to fetch FX quotes. Amount finalized at checkout.',
  },
  teams: {
    title: 'For Teams',
    description: 'Shared wallet & roles. Let your team create with one balance. Set soft/hard project budgets. Daily summary by email.',
    actions: {
      invite: 'Invite teammates',
      budgets: 'Set project budgets',
    },
    note: 'Team note: On shared wallets, status applies to all members.',
    comingSoon:
      'Coming soon — unified wallets, role-based approvals, and budgeting controls. Join the beta at {email}.',
    contactEmail: 'support@maxvideoai.com',
    statusLive: 'Live',
    statusSoon: 'Coming soon',
  },
  receipts: {
    ledgerLabel: 'Billing documents',
    title: 'Receipts & invoices',
    subtitle: 'Download Stripe documents for wallet top-ups and review charges or refunds.',
    openDocuments: 'Receipts & invoices',
    empty: 'No payment documents or wallet activity yet.',
    documentsEmpty: 'No wallet top-up documents yet.',
    activityEmpty: 'No wallet activity yet.',
    tabs: {
      documents: 'Documents',
      activity: 'Wallet activity',
    },
    loading: 'Loading…',
    loadMore: 'Load more',
    exportCsv: 'Export CSV',
    collapsedLabel: 'Show',
    expandedLabel: 'Hide',
    typeLabels: {
      charge: 'Charge',
      refund: 'Refund',
      topup: 'Top-up',
    },
    fields: {
      total: 'Total',
      walletMovement: 'Wallet movement',
      paymentAmount: 'Amount paid (including tax)',
      tax: 'Tax',
      discount: 'Discount',
      document: 'Document',
    },
    viewReceipt: 'View receipt',
    viewInvoice: 'View invoice',
    receiptLabel: 'Receipt',
    invoiceLabel: 'Invoice',
    contactSupport: 'Contact support',
  },
  checkoutReturn: {
    successTitle: 'Payment returned',
    cancelledTitle: 'Checkout cancelled',
    refreshingDetail: 'Refreshing your balance and payment history…',
    refreshedDetail: 'Latest wallet and payment history loaded.',
    delayedDetail: 'Payment returned. Account updates may still be processing; refresh again shortly.',
    cancelledDetail: 'No charge was completed. Your selected amount has been kept.',
  },
  refunds: {
    title: 'Protections',
    points: [
      'Failed renders are refunded automatically.',
      'Receipts include itemized tax and payment details.',
      'No subscription. Add credits only when you need them.',
    ],
  },
  faq: {
    title: 'Micro-FAQ',
    entries: [
      { question: 'Do I need a subscription?', answer: 'No. Pay as you go.' },
      { question: 'Can I buy just one small render?', answer: 'Yes — funds are debited per run from your $10 Starter balance.' },
      { question: 'Will my credits expire?', answer: 'Credits don’t expire while your account remains active.' },
      { question: 'Which price applies?', answer: 'New generations use standard pricing. The exact price is shown before confirmation.' },
    ],
    footnote:
      'VAT included where applicable. Refunds on failed renders. “Works with” indicates compatibility; trademarks belong to their respective owners.',
  },
  toasts: {
    success: 'Payment successful. Funds added to your wallet.',
    cancelled: 'Checkout closed. No charge made.',
    returnToWorkspace: 'Return to the video workspace',
  },
  errors: {
    loadReceipts: 'We couldn’t load your payment history. Refresh the page or contact support.',
    loadMore: 'Failed to load more receipts',
    lowBalance: 'Your balance is low. Top up to keep creating.',
    topupStart: 'Unable to start payment.',
  },
  authGate: {
    title: 'Sign in to add credits',
    body: 'Your account keeps your credits and payment documents together.',
    primary: 'Create account',
    secondary: 'Sign in',
    close: 'Maybe later',
  },
};

export type BillingCopy = typeof DEFAULT_BILLING_COPY;
