/** Read-only design projection. Keep pricing logic in the existing public owners. */
import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { listFalEngines } from '../../../frontend/src/config/falEngines';
import { buildEngineOption, buildAudioAddonPayload } from '../../../frontend/components/marketing/price-estimator/price-estimator-options';
import { getPricingKernel } from '../../../frontend/src/lib/pricing-kernel';
import { buildPublicPricingFacts } from '../../../frontend/src/lib/pricing-public-facts';
import { quotePublicPricing } from '../../../frontend/src/lib/pricing-public-quote';
import { getModelFamilyDefinition } from '../../../frontend/config/model-families';

const ids = ['veo-3-1-fast', 'veo-3-1', 'kling-3-pro', 'sora-2', 'wan-2-6', 'seedance-2-5'];
const entries = listFalEngines();
const models = ids.map(id => {
  const entry = entries.find(e => e.id === id);
  assert.ok(entry?.surfaces.app.enabled && entry.surfaces.pricing.includeInEstimator && entry.engine.modes.includes('t2v'), `${id}: catalogue scope changed`);
  const option = buildEngineOption(entry, entry.engine, entry.engine, getPricingKernel(), {});
  assert.ok(option?.pricingEngineCaps && option.availability === 'available', `${id}: unavailable`);
  const durations = option.durationOptions.length
    ? option.durationOptions.map(d => d.value)
    : Array.from({ length: option.maxDuration - option.minDuration + 1 }, (_, i) => option.minDuration + i);
  const audioValues = option.audioToggle ? [true, false] : [option.audioIncluded];
  assert.ok(durations.includes(option.defaultDuration), `${id}: default duration is not selectable`);
  const quotes = durations.flatMap(duration => option.resolutions.flatMap(resolution => audioValues.map(audio => {
    const addons = buildAudioAddonPayload(option.audioAddonKey, audio);
    const facts = buildPublicPricingFacts({
      engine: option.pricingEngineCaps!, durationSec: duration, resolution: resolution.value,
      mode: 't2v', ...(addons ? { addons } : {}), useStandardDefinitionFacts: true,
    });
    const quote = quotePublicPricing({
      facts: facts.facts,
      scenario: { id: `design:${id}:${duration}:${resolution.value}:${audio}`, engineId: facts.facts.engineId, mode: 't2v', resolution: resolution.value, membershipTier: 'member' },
      compatibilityProfileId: 'public-rounded-vendor-current',
    });
    assert.ok(Number.isSafeInteger(quote.customerTotalCents) && quote.customerTotalCents > 0, `${id}: invalid estimate`);
    assert.equal(quote.currency, 'USD');
    return { duration, resolution: resolution.value, audio, totalCents: quote.customerTotalCents, currency: quote.currency };
  })));
  return {
    id, label: option.label, familyId: entry.family, familyLabel: getModelFamilyDefinition(entry.family)?.label ?? option.label,
    durations, resolutions: option.resolutions.map(r => ({ value: r.value, label: r.label })),
    formats: entry.engine.aspectRatios,
    audio: option.audioToggle ? 'optional' : option.audioIncluded ? 'included' : 'none',
    defaultDuration: option.defaultDuration, quotes,
  };
});
const catalogue = {
  scope: { mode: 't2v', membershipTier: 'member', currency: 'USD', source: 'Versioned public catalogue; no database overrides or account-specific quote', generatedAt: new Date().toISOString() },
  models,
};
assert.ok(process.argv[2], 'Provide the ignored preview catalogue destination');
writeFileSync(process.argv[2], `// Generated by export-catalog.ts. Never edit prices here.\nexport const catalogue = ${JSON.stringify(catalogue)};\n`);
console.log(`Catalogue: ${models.length} models, ${models.reduce((n, m) => n + m.quotes.length, 0)} public scenarios`);
