import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const root = process.cwd();
const executorPath = join(root, 'frontend/src/server/images/execute-image-generation.ts');
const existingJobResponsePath = join(root, 'frontend/src/server/images/existing-image-job-response.ts');
const referenceNormalizationPath = join(root, 'frontend/src/server/images/image-reference-normalization.ts');
const initialJobPath = join(root, 'frontend/src/server/images/image-initial-job.ts');
const errorPath = join(root, 'frontend/src/server/images/image-generation-error.ts');
const providerPayloadPath = join(root, 'frontend/src/server/images/image-provider-payload.ts');
const completionPath = join(root, 'frontend/src/server/images/image-generation-completion.ts');
const receiptsPath = join(root, 'frontend/src/server/images/image-generation-receipts.ts');
const settingsSnapshotPath = join(root, 'frontend/src/server/images/image-generation-settings-snapshot.ts');

const executorSource = readFileSync(executorPath, 'utf8');
const existingJobResponseSource = readFileSync(existingJobResponsePath, 'utf8');
const referenceNormalizationSource = readFileSync(referenceNormalizationPath, 'utf8');
const initialJobSource = readFileSync(initialJobPath, 'utf8');
const errorSource = readFileSync(errorPath, 'utf8');
const providerPayloadSource = readFileSync(providerPayloadPath, 'utf8');
const completionSource = readFileSync(completionPath, 'utf8');
const receiptsSource = readFileSync(receiptsPath, 'utf8');
const settingsSnapshotSource = readFileSync(settingsSnapshotPath, 'utf8');

test('image generation executor delegates focused server helpers', () => {
  assert.ok(existsSync(existingJobResponsePath), 'existing image job response helpers should live in a focused module');
  assert.ok(existsSync(referenceNormalizationPath), 'image reference normalization should live in a focused module');
  assert.ok(existsSync(initialJobPath), 'atomic initial image job creation should live in a focused module');
  assert.ok(existsSync(errorPath), 'image generation execution error should live in a focused module');
  assert.ok(existsSync(providerPayloadPath), 'provider payload parsing should live in a focused module');
  assert.ok(existsSync(completionPath), 'image generation completion persistence should live in a focused module');
  assert.ok(existsSync(receiptsPath), 'image generation receipt helpers should live in a focused module');
  assert.ok(existsSync(settingsSnapshotPath), 'image settings snapshot helpers should live in a focused module');
  assert.match(executorSource, /from '\.\/existing-image-job-response'/);
  assert.match(executorSource, /from '\.\/image-reference-normalization'/);
  assert.match(executorSource, /from '\.\/image-initial-job'/);
  assert.match(executorSource, /from '\.\/image-generation-error'/);
  assert.match(executorSource, /from '\.\/image-provider-payload'/);
  assert.match(executorSource, /from '\.\/image-generation-completion'/);
  assert.match(executorSource, /from '\.\/image-generation-receipts'/);
  assert.match(executorSource, /from '\.\/image-generation-settings-snapshot'/);
  assert.match(executorSource, /export \{ buildResponseFromExistingJob \} from '\.\/existing-image-job-response'/);
  assert.match(executorSource, /export \{ ImageGenerationExecutionError \} from '\.\/image-generation-error'/);
});

test('image generation executor does not regain extracted server ownership', () => {
  assert.doesNotMatch(executorSource, /function buildImagesFromExistingJob\(/, 'stored render parsing belongs in existing-image-job-response.ts');
  assert.doesNotMatch(executorSource, /function parseResolutionFromSettingsSnapshot\(/, 'settings snapshot resolution parsing belongs in existing-image-job-response.ts');
  assert.doesNotMatch(executorSource, /parseStoredImageRenders/, 'stored render parsing belongs in existing-image-job-response.ts');
  assert.doesNotMatch(executorSource, /function pickNormalizedReferenceMime\(/, 'reference mime selection belongs in image-reference-normalization.ts');
  assert.doesNotMatch(executorSource, /function isReferenceImageSupported\(/, 'reference format checks belong in image-reference-normalization.ts');
  assert.doesNotMatch(executorSource, /async function normalizeReferenceImageForEngine\(/, 'reference normalization belongs in image-reference-normalization.ts');
  assert.doesNotMatch(executorSource, /withDbTransaction/, 'initial job transaction belongs in image-initial-job.ts');
  assert.doesNotMatch(executorSource, /reserveWalletChargeInExecutor/, 'wallet reservation belongs in image-initial-job.ts');
  assert.doesNotMatch(executorSource, /async function insertProvisionalImageJob\(/, 'provisional job insert belongs in image-initial-job.ts');
  assert.doesNotMatch(executorSource, /export class ImageGenerationExecutionError/, 'execution error contract belongs in image-generation-error.ts');
  assert.doesNotMatch(executorSource, /function normalizeUrl\(/, 'provider URL normalization belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function sanitizeCharacterReferences\(/, 'character reference sanitizing belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function buildCharacterReferencePrompt\(/, 'character reference prompt building belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function extractImages\(/, 'provider image extraction belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function parseRequestId\(/, 'provider request id parsing belongs in image-provider-payload.ts');
  assert.doesNotMatch(executorSource, /function buildReceiptSnapshot\(/, 'receipt snapshots belong in image-generation-receipts.ts');
  assert.doesNotMatch(executorSource, /async function recordRefundReceipt\(/, 'refund receipt writes belong in image-generation-receipts.ts');
  assert.doesNotMatch(executorSource, /function buildDefaultSettingsSnapshot\(/, 'default settings snapshots belong in image-generation-settings-snapshot.ts');
  assert.doesNotMatch(executorSource, /recordUserAsset/, 'completed character asset persistence belongs in image-generation-completion.ts');
  assert.doesNotMatch(executorSource, /upsertLegacyJobOutputs/, 'completed output persistence belongs in image-generation-completion.ts');
  assert.doesNotMatch(executorSource, /ensureReusableAsset/, 'reusable character asset persistence belongs in image-generation-completion.ts');
  assert.doesNotMatch(executorSource, /status = 'completed'/, 'completed job update belongs in image-generation-completion.ts');

  const lineCount = executorSource.split('\n').length;
  assert.ok(lineCount <= 860, `image generation executor should stay below 860 lines after completion extraction, got ${lineCount}`);
});

test('existing image job response module exposes the expected contract', () => {
  assert.match(existingJobResponseSource, /export type ExistingImageJobRow/);
  assert.match(existingJobResponseSource, /export function parseResolutionFromSettingsSnapshot/);
  assert.match(existingJobResponseSource, /export function buildResponseFromExistingJob/);
  assert.match(existingJobResponseSource, /parseStoredImageRenders/);
  assert.match(referenceNormalizationSource, /export type StoredAssetInfo/);
  assert.match(referenceNormalizationSource, /export async function getStoredAssetInfoByUrl/);
  assert.match(referenceNormalizationSource, /export function isReferenceImageSupported/);
  assert.match(referenceNormalizationSource, /export function pickNormalizedReferenceMime/);
  assert.match(referenceNormalizationSource, /export async function normalizeReferenceImageForEngine/);
  assert.match(initialJobSource, /export const PLACEHOLDER_THUMB/);
  assert.match(initialJobSource, /export async function createAtomicInitialImageJob/);
  assert.match(initialJobSource, /async function insertProvisionalImageJob/);
  assert.match(initialJobSource, /withDbTransaction/);
  assert.match(initialJobSource, /reserveWalletChargeInExecutor/);
  assert.match(errorSource, /export class ImageGenerationExecutionError/);
  assert.match(providerPayloadSource, /export function normalizeProviderImageUrl/);
  assert.match(providerPayloadSource, /export function sanitizeCharacterReferences/);
  assert.match(providerPayloadSource, /export function buildCharacterReferencePrompt/);
  assert.match(providerPayloadSource, /export function extractImages/);
  assert.match(providerPayloadSource, /export function parseRequestId/);
  assert.match(completionSource, /export async function persistCompletedImageGeneration/);
  assert.match(completionSource, /recordUserAsset/);
  assert.match(completionSource, /upsertLegacyJobOutputs/);
  assert.match(completionSource, /ensureReusableAsset/);
  assert.match(completionSource, /status = 'completed'/);
  assert.match(receiptsSource, /export type PendingReceipt/);
  assert.match(receiptsSource, /export function buildReceiptSnapshot/);
  assert.match(receiptsSource, /export async function recordRefundReceipt/);
  assert.match(settingsSnapshotSource, /export function buildDefaultSettingsSnapshot/);
});
