import assert from 'node:assert/strict';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

import mcpPublication from '../frontend/config/mcp-publication.json';

const enabledPublication = {
  publicMarketing: true,
  publicIndexing: true,
  transport: true,
  oauth: true,
  discovery: true,
  paidGeneration: true,
  trial: true,
  referenceUploads: true,
};

const localizedMcpUrls = {
  '/mcp': {
    en: 'https://maxvideoai.com/mcp',
    fr: 'https://maxvideoai.com/fr/mcp',
    es: 'https://maxvideoai.com/es/mcp',
  },
  '/integrations/chatgpt': {
    en: 'https://maxvideoai.com/integrations/chatgpt',
    fr: 'https://maxvideoai.com/fr/integrations/chatgpt',
    es: 'https://maxvideoai.com/es/integraciones/chatgpt',
  },
  '/integrations/claude': {
    en: 'https://maxvideoai.com/integrations/claude',
    fr: 'https://maxvideoai.com/fr/integrations/claude',
    es: 'https://maxvideoai.com/es/integraciones/claude',
  },
  '/integrations/codex': {
    en: 'https://maxvideoai.com/integrations/codex',
    fr: 'https://maxvideoai.com/fr/integrations/codex',
    es: 'https://maxvideoai.com/es/integraciones/codex',
  },
  '/docs/mcp': {
    en: 'https://maxvideoai.com/docs/mcp',
    fr: 'https://maxvideoai.com/fr/docs/mcp',
    es: 'https://maxvideoai.com/es/docs/mcp',
  },
} as const;

function copyFixtureFile(source: string, destinationRoot: string) {
  const destination = join(destinationRoot, source);
  mkdirSync(resolve(destination, '..'), { recursive: true });
  copyFileSync(resolve(source), destination);
}

function buildEnabledPostbuildSitemap(): string {
  const fixtureRoot = mkdtempSync(join(tmpdir(), 'maxvideoai-mcp-sitemap-'));
  try {
    copyFixtureFile('frontend/next-sitemap.config.js', fixtureRoot);
    copyFixtureFile('frontend/config/model-roster.json', fixtureRoot);
    copyFixtureFile('frontend/config/localized-slugs.json', fixtureRoot);
    mkdirSync(join(fixtureRoot, 'frontend/config'), { recursive: true });
    writeFileSync(
      join(fixtureRoot, 'frontend/config/mcp-publication.json'),
      `${JSON.stringify(enabledPublication, null, 2)}\n`,
    );
    mkdirSync(join(fixtureRoot, 'frontend/.next'), { recursive: true });
    writeFileSync(
      join(fixtureRoot, 'frontend/.next/build-manifest.json'),
      JSON.stringify({ pages: {}, ampFirstPages: [] }),
    );
    symlinkSync(resolve('frontend/node_modules'), join(fixtureRoot, 'frontend/node_modules'), 'dir');

    const executable = resolve('frontend/node_modules/.bin/next-sitemap');
    const result = spawnSync(executable, ['--config', 'next-sitemap.config.js'], {
      cwd: join(fixtureRoot, 'frontend'),
      encoding: 'utf8',
      env: { PATH: process.env.PATH ?? '', NODE_ENV: 'production' },
    });
    assert.equal(result.status, 0, `${result.stdout}\n${result.stderr}`);
    const xmlPath = join(fixtureRoot, 'frontend/.next/generated-sitemaps/sitemap-0.xml');
    assert.equal(existsSync(xmlPath), true, `${basename(xmlPath)} should be generated by the real next-sitemap CLI`);
    return readFileSync(xmlPath, 'utf8');
  } finally {
    rmSync(fixtureRoot, { recursive: true, force: true });
  }
}

function extractUrlBlocks(xml: string) {
  return xml.match(/<url>.*?<\/url>/gs) ?? [];
}

function extractLoc(block: string) {
  return /<loc>([^<]+)<\/loc>/.exec(block)?.[1] ?? null;
}

function extractAlternates(block: string) {
  return Object.fromEntries(
    [...block.matchAll(/<xhtml:link rel="alternate" hreflang="([^"]+)" href="([^"]+)"\/>/g)].map(
      (match) => [match[1], match[2]],
    ),
  );
}

test('enabled postbuild XML contains all 15 localized MCP owners with reciprocal absolute alternates', () => {
  const xml = buildEnabledPostbuildSitemap();
  const expectedUrls = Object.values(localizedMcpUrls).flatMap((locales) => Object.values(locales));
  const expectedUrlSet = new Set(expectedUrls);
  assert.equal(expectedUrlSet.size, 15);

  const sourceBlocks = extractUrlBlocks(xml).filter((block) => {
    const loc = extractLoc(block);
    return loc != null && expectedUrlSet.has(loc);
  });
  assert.equal(sourceBlocks.length, 15, 'every localized source URL should be a sitemap <loc> exactly once');
  assert.deepEqual(new Set(sourceBlocks.map(extractLoc)), expectedUrlSet);

  for (const block of sourceBlocks) {
    const loc = extractLoc(block);
    const owner = Object.values(localizedMcpUrls).find((locales) => Object.values(locales).includes(loc as never));
    assert.ok(owner, `${loc} should map to one MCP intent owner`);
    assert.deepEqual(extractAlternates(block), { ...owner, 'x-default': owner.en });
  }
  assert.doesNotMatch(xml, /api\.maxvideoai\.com\/mcp/);
});

test('llms response is built deterministically from publication state without a public-file conflict', async () => {
  const builderPath = 'frontend/lib/seo/llms-text.ts';
  const routePath = 'frontend/app/llms.txt/route.ts';
  assert.equal(existsSync(builderPath), true, 'the pure llms text builder should exist');
  assert.equal(existsSync(routePath), true, 'the served llms route should exist');
  assert.equal(existsSync('frontend/public/llms.txt'), false, 'a static file must not shadow the state-aware route');

  const { buildLlmsText } = await import('../frontend/lib/seo/llms-text.ts');
  const falseText = buildLlmsText({
    publicMarketing: false,
    publicIndexing: false,
    transport: false,
    oauth: false,
    discovery: false,
    paidGeneration: false,
    trial: false,
    referenceUploads: false,
  });
  const releaseText = buildLlmsText(mcpPublication);
  const enabledText = buildLlmsText(enabledPublication);
  const sourceUrls = Object.values(localizedMcpUrls).map(({ en }) => en);
  sourceUrls.forEach((url) => assert.equal(falseText.includes(url), false));
  sourceUrls.forEach((url) => assert.equal(enabledText.split(url).length - 1, 1));
  assert.doesNotMatch(falseText, /publication gate|acquisition sources are omitted|shared.*closed/i);
  assert.doesNotMatch(enabledText, /publication gate is closed/i);
  assert.match(enabledText, /MaxVideoAI workflow for ChatGPT, Claude, and Codex/);
  assert.match(enabledText, /ChatGPT app and direct MCP setup/);
  assert.match(enabledText, /Claude connector setup and revocation/);
  assert.match(enabledText, /Codex-specific setup and revocation/);
  assert.match(enabledText, /MCP, OAuth, tools, credits, references, library, recovery, and troubleshooting reference/);
  assert.doesNotMatch(falseText, /api\.maxvideoai\.com\/mcp/);
  assert.doesNotMatch(enabledText, /api\.maxvideoai\.com\/mcp/);

  const routeSource = readFileSync(routePath, 'utf8');
  assert.match(routeSource, /mcp-publication\.json/);
  assert.match(routeSource, /buildLlmsText\(mcpPublication\)/);
  const { GET } = await import('../frontend/app/llms.txt/route.ts');
  const response = GET();
  assert.equal(response.status, 200);
  assert.match(response.headers.get('content-type') ?? '', /^text\/plain/);
  assert.equal(await response.text(), releaseText);
});

test('host-aware robots blocks the API protocol host and preserves explicit public crawler roles', async () => {
  const builderPath = 'frontend/lib/seo/robots-text.ts';
  const routePath = 'frontend/app/robots.txt/route.ts';
  assert.equal(existsSync(builderPath), true, 'the pure robots text builder should exist');
  assert.equal(existsSync(routePath), true, 'the host-aware robots route should exist');
  assert.equal(existsSync('frontend/public/robots.txt'), false, 'a static file must not shadow host-aware robots');

  const { GET } = await import('../frontend/app/robots.txt/route.ts');
  const apiResponse = GET(
    new Request('https://api.maxvideoai.com/robots.txt', {
      headers: { host: 'api.maxvideoai.com', 'x-forwarded-host': 'maxvideoai.com' },
    }),
  );
  assert.equal(await apiResponse.text(), '# MaxVideoAI protocol host\n\nUser-agent: *\nDisallow: /\n');

  const publicResponse = GET(
    new Request('https://maxvideoai.com/robots.txt', {
      headers: { host: 'maxvideoai.com', 'x-forwarded-host': 'api.maxvideoai.com' },
    }),
  );
  const publicText = await publicResponse.text();
  assert.match(publicText, /User-agent: Google-Extended\nAllow: \/\n/);
  assert.match(publicText, /Google-Extended controls both Gemini grounding and future model training/);
  assert.match(publicText, /User-agent: OAI-AdsBot\nAllow: \/\n/);
  assert.match(publicText, /Ads landing-page validation/);

  const searchGroup = /# AI search and user-requested retrieval[\s\S]*?(?=\n# Ads landing-page validation)/.exec(publicText)?.[0] ?? '';
  assert.doesNotMatch(searchGroup, /OAI-AdsBot/);
  for (const privatePath of ['/api/', '/oauth', '/account', '/uploads', '/app', '/docs/private']) {
    assert.match(publicText, new RegExp(`Disallow: ${privatePath.replace('/', '\\/')}`));
  }
});
