import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import test from 'node:test';
import {getDb} from '../frontend/src/lib/db';
import {startDisposablePostgres,createPaidGenerationTestSchema} from './helpers/disposable-postgres';
import {STUDIO_ASSISTANCE_TARIFF} from '../frontend/src/lib/studio/assistance-contract';

test('account-wide allowances, exact cumulative billing, unresolved exposure and explicit model choice survive concurrency',async t=>{
  const ledger = await import('../frontend/src/server/studio/assistance-ledger').catch(()=>null);
  assert.ok(ledger,'Studio requires durable account-wide monetary reservations');
  const pg=await startDisposablePostgres('studio-assistance');
  const old=process.env.DATABASE_URL; process.env.DATABASE_URL=pg.databaseUrl;
  t.after(async()=>{await getDb().end();if(old===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=old;await pg.cleanup();});
  await createPaidGenerationTestSchema(pg.pool);
  await pg.pool.query(readFileSync('neon/migrations/54_studio_assistance_ledger.sql','utf8'));
  await pg.pool.query(readFileSync('neon/migrations/62_studio_assistance_resolutions.sql','utf8'));
  const policy={enabled:true,solAllowanceNanoUsd:10_000_000,lunaAllowanceNanoUsd:5_000_000,campaignNanoUsd:100_000_000,maxAdditionalBudgetCents:2000};
  const actor={userId:'owner',projectId:'film',authMethod:'studio-session' as const,clientId:null};
  const request=randomUUID();
  const frozen=await ledger.openStudioAssistanceTurn(actor,request,policy);
  assert.equal(frozen.model,'gpt-6.1-sol');
  const concurrent=await Promise.allSettled([0,1].map(index=>ledger.reserveStudioAssistanceCall({...actor,requestId:request,leaseId:randomUUID(),index,inputTokens:100,outputTokens:975},policy)));
  assert.equal(concurrent.filter(v=>v.status==='fulfilled').length,1,'Two tabs cannot each consume the same allowance');
  const call=(concurrent.find(v=>v.status==='fulfilled') as PromiseFulfilledResult<any>).value;
  assert.equal((await ledger.readStudioAssistanceStatus('owner',policy)).includedSol.remainingPercent,0);
  await ledger.markStudioAssistanceUnknown(call.id,'owner');
  await assert.rejects(ledger.reserveStudioAssistanceCall({...actor,requestId:request,leaseId:randomUUID(),index:call.response_index,inputTokens:0,outputTokens:1},policy),/unresolved/i);
  assert.equal((await ledger.readStudioAssistanceStatus('other',policy)).includedSol.remainingPercent,100);
  const usage={input_tokens:100,input_tokens_details:{cached_tokens:0},output_tokens:50,output_tokens_details:{reasoning_tokens:10}};
  await ledger.settleStudioAssistanceCall(call.id,'owner',{id:'resp-discovery',model:'gpt-6.1-sol',service_tier:'default',usage});
  await ledger.settleStudioAssistanceCall(call.id,'owner',{id:'resp-discovery',model:'gpt-6.1-sol',service_tier:'default',usage});
  assert.equal((await ledger.readStudioAssistanceStatus('owner',policy)).includedSol.remainingPercent,92.5);
  await assert.rejects(ledger.settleStudioAssistanceCall(call.id,'other',{id:'foreign',model:'gpt-6.1-sol',service_tier:'default',usage}),/available/i);
  await pg.pool.query("INSERT INTO app_receipts(user_id,type,amount_cents,currency) VALUES ('owner','topup',100,'USD')");
  assert.equal((await ledger.readStudioAssistanceStatus('owner',policy)).mode,'included_sol','Funding must not authorize paid assistance');
  let status=await ledger.chooseStudioAssistance('owner',{action:'authorize_paid',budgetCents:50,tariffVersion:STUDIO_ASSISTANCE_TARIFF.version,expectedRevision:0},policy);
  assert.equal(status.mode,'paid_sol');
  assert.equal(status.paid.enabled,true);
  assert.equal((await ledger.openStudioAssistanceTurn(actor,request,policy)).mode,'included_sol','In-flight turn model/funding remains frozen');
  const paidRequest=randomUUID();await ledger.openStudioAssistanceTurn(actor,paidRequest,policy);
  const paidCall=await ledger.reserveStudioAssistanceCall({...actor,requestId:paidRequest,leaseId:randomUUID(),index:0,inputTokens:1000,outputTokens:1000},policy);
  assert.equal((await ledger.readStudioAssistanceStatus('owner',policy)).paid.reservedCents,4);
  assert.equal((await ledger.readStudioAssistanceStatus('owner',policy)).paid.maxAdditionalBudgetCents,1950,'The displayed increment must include held wallet reservations in the outstanding budget cap');
  await assert.rejects(ledger.chooseStudioAssistance('owner',{action:'authorize_paid',budgetCents:2001,tariffVersion:STUDIO_ASSISTANCE_TARIFF.version,expectedRevision:1},policy),/displayed range/i);
  await ledger.settleStudioAssistanceCall(paidCall.id,'owner',{id:'resp-paid-1',model:'gpt-6.1-sol',service_tier:'default',usage:{input_tokens:40,input_tokens_details:{cached_tokens:0},output_tokens:0}});
  const paidCall2=await ledger.reserveStudioAssistanceCall({...actor,requestId:paidRequest,leaseId:randomUUID(),index:1,inputTokens:1000,outputTokens:1000},policy);
  await ledger.settleStudioAssistanceCall(paidCall2.id,'owner',{id:'resp-paid-2',model:'gpt-6.1-sol',service_tier:'default',usage:{input_tokens:40,input_tokens_details:{cached_tokens:0},output_tokens:0}});
  status=await ledger.readStudioAssistanceStatus('owner',policy);
  assert.equal(status.paid.spentCents,1,'Two sub-cent tool calls are rounded only once for their client message');
  assert.equal(status.paid.reservedCents,0);
  const balance=(await pg.pool.query("SELECT sum(CASE WHEN type='charge' THEN -amount_cents ELSE amount_cents END)::int balance FROM app_receipts WHERE user_id='owner'")).rows[0].balance;
  assert.equal(balance,99);
  await assert.rejects(ledger.chooseStudioAssistance('owner',{action:'select_luna',expectedRevision:0},policy),/changed/i);
  status=await ledger.chooseStudioAssistance('owner',{action:'select_luna',expectedRevision:1},policy);
  assert.equal(status.selectedModel,'gpt-6-luna');
  assert.equal(status.paid.enabled,true,'Luna selection retains the existing paid Sol authorization');
  const lunaRequest=randomUUID();assert.equal((await ledger.openStudioAssistanceTurn(actor,lunaRequest,policy)).model,'gpt-6-luna');
  const luna=await ledger.reserveStudioAssistanceCall({...actor,requestId:lunaRequest,leaseId:randomUUID(),index:0,inputTokens:1000,outputTokens:1000},policy);
  await ledger.settleStudioAssistanceCall(luna.id,'owner',{id:'resp-luna-unknown',model:'gpt-6-luna',service_tier:'default',usage:null});
  status=await ledger.readStudioAssistanceStatus('owner',policy);
  assert.equal(status.unresolvedCalls,1);assert.equal(status.paid.spentCents,1);assert.equal(status.sponsoredLuna.remainingPercent,87.5);
  await assert.rejects(ledger.settleStudioAssistanceCall(luna.id,'owner',{id:'different-response',model:'gpt-6-luna',service_tier:'default',usage}),/different response/i);
  await assert.rejects(ledger.chooseStudioAssistance('owner',{action:'authorize_paid',budgetCents:100,tariffVersion:'old',expectedRevision:2},policy),/tariff/i);
  // A funded account with a revoked budget cannot keep charging a frozen paid turn.
  const revoked=await ledger.chooseStudioAssistance('owner',{action:'disable_paid',expectedRevision:2},policy);
  assert.equal(revoked.selectedModel,'gpt-6-luna');assert.equal(revoked.paid.enabled,false,'Paid authorization can be revoked while Luna has unresolved usage');
  assert.equal((await ledger.readStudioAssistanceStatus('other',policy)).paid.enabled,false);
  await assert.rejects(ledger.reserveStudioAssistanceCall({...actor,requestId:paidRequest,leaseId:randomUUID(),index:2,inputTokens:10,outputTokens:10},policy),error=>(error as any).nextAction?.reason==='paid_budget_exhausted');
  // Independently funded accounts still share one campaign exposure ceiling.
  await pg.pool.query('UPDATE studio_assistance_campaigns SET limit_nano_usd=10000000');
  const actors=['campaign-a','campaign-b'].map(userId=>({...actor,userId}));
  const requests=[randomUUID(),randomUUID()];
  await Promise.all(actors.map((current,i)=>ledger.openStudioAssistanceTurn(current,requests[i],policy)));
  const campaign=await Promise.allSettled(actors.map((current,i)=>ledger.reserveStudioAssistanceCall({...current,requestId:requests[i],leaseId:randomUUID(),index:0,inputTokens:0,outputTokens:600},policy)));
  assert.equal(campaign.filter(v=>v.status==='fulfilled').length,1,'Aggregate campaign cap must serialize different accounts');
  const blocked=campaign.find(v=>v.status==='rejected') as PromiseRejectedResult;
  assert.equal(blocked.reason.nextAction.reason,'campaign_exhausted');assert.equal(blocked.reason.nextAction.safeToStartNewRequest,true);
  // A customer budget is not proof of wallet funding. Failed reservations roll back completely.
  const unfunded={...actor,userId:'unfunded'};const unfundedRequest=randomUUID();
  await ledger.chooseStudioAssistance('unfunded',{action:'authorize_paid',budgetCents:100,tariffVersion:STUDIO_ASSISTANCE_TARIFF.version,expectedRevision:0},policy);
  await ledger.openStudioAssistanceTurn(unfunded,unfundedRequest,policy);
  await assert.rejects(ledger.reserveStudioAssistanceCall({...unfunded,requestId:unfundedRequest,leaseId:randomUUID(),index:0,inputTokens:1000,outputTokens:1000},policy),error=>(error as any).nextAction?.reason==='wallet_insufficient');
  assert.equal((await pg.pool.query('SELECT count(*)::int n FROM studio_assistance_calls WHERE user_id=$1',['unfunded'])).rows[0].n,0);
  await assert.rejects(ledger.openStudioAssistanceTurn(actor,randomUUID(),{...policy,enabled:false}),/unavailable/i);
});
