import test from 'node:test';
import assert from 'node:assert/strict';
import {NextRequest} from '../frontend/node_modules/next/server';
import {handleStudioTask} from '../frontend/app/api/studio/_lib/studio-task-handler';
import {handleStudioImageConversation} from '../frontend/app/api/studio/_lib/studio-image-conversation-handler';
import {STUDIO_TASK_POLICY_VERSION} from '../frontend/src/lib/studio/task-budget-contract';
const requestId='f2929a29-91b4-4c81-a731-820d6d3d7102';
const access=async()=>({ok:true as const,userId:'owner'});
test('task reads cannot dispatch and mutations reject cross-origin or mismatched identities',async()=>{
  let reads=0,resumes=0;
  const service={read:async()=>{reads++;return {state:'paused'};},resume:async()=>{resumes++;return {state:'queued'};},recover:async()=>null,cancel:async()=>null,enqueue:async()=>null};
  const overrides={resolveAccess:access,serviceFactory:()=>service};
  const url=`https://maxvideoai.com/api/studio/projects/film/conversation-tasks/${requestId}`;
  assert.equal((await handleStudioTask(new NextRequest(url),'film',requestId,'read',overrides)).status,200);
  assert.equal(reads,1);assert.equal(resumes,0);
  const body={action:'continue',requestId,approvalId:requestId,expectedRevision:0,maxCredits:250,policyVersion:STUDIO_TASK_POLICY_VERSION,confirmed:true};
  assert.equal((await handleStudioTask(new NextRequest(url,{method:'POST',headers:{origin:'https://foreign.invalid'},body:JSON.stringify(body)}),'film',requestId,'mutate',overrides)).status,403);
  assert.equal((await handleStudioTask(new NextRequest(url,{method:'POST',headers:{origin:'https://maxvideoai.com'},body:JSON.stringify({...body,requestId:'f2929a29-91b4-4c81-a731-820d6d3d7103'})}),'film',requestId,'mutate',overrides)).status,400);
  assert.equal(resumes,0);
  assert.equal((await handleStudioTask(new NextRequest(url,{method:'POST',headers:{origin:'https://maxvideoai.com'},body:'x'.repeat(24001)}),'film',requestId,'mutate',overrides)).status,413);
});
test('task-enabled conversation POST enqueues and returns a turn, never synchronous model submission',async()=>{
  let enqueues=0,synchronous=0;
  const turn={requestId,message:'Help me',references:[],reply:null,state:'thinking',quote:null,generation:null};
  const base={read:async()=>({projectId:'film',turns:[]}),submit:async()=>{synchronous++;throw new Error('Must enqueue');},confirm:async()=>null};
  const adapter={submit:async()=>{enqueues++;return turn;},read:base.read};
  const req=new NextRequest('https://maxvideoai.com/api/studio/projects/film/image-conversation',{method:'POST',headers:{origin:'https://maxvideoai.com'},body:JSON.stringify({requestId,message:'Help me',references:[],taskBudget:{profile:'standard',maxCredits:250,policyVersion:STUDIO_TASK_POLICY_VERSION}})});
  const response=await handleStudioImageConversation(req,'film','submit',{enabled:true,tasksEnabled:true,resolveAccess:access,serviceFactory:()=>base as never,taskAdapterFactory:()=>adapter as never});
  assert.equal(response.status,200);assert.equal(enqueues,1);assert.equal(synchronous,0);assert.equal((await response.json()).result.requestId,requestId);
});
test('only a queued submission or explicit resume schedules owned background work',async()=>{
  const scheduled:unknown[]=[];
  const scheduleWorker=(...args:unknown[])=>{scheduled.push(args);};
  const task={requestId,state:'queued'};
  const turn={requestId,state:'thinking',task};
  const base={read:async()=>({projectId:'film',turns:[turn]}),submit:async()=>turn,confirm:async()=>({state:'completed'})};
  const overrides={enabled:true,tasksEnabled:true,resolveAccess:access,serviceFactory:()=>base as never,taskAdapterFactory:()=>base as never,scheduleWorker};
  const url='https://maxvideoai.com/api/studio/projects/film/image-conversation';
  await handleStudioImageConversation(new NextRequest(url),'film','read',overrides);
  assert.equal(scheduled.length,0);
  await handleStudioImageConversation(new NextRequest(url,{method:'POST',headers:{origin:'https://maxvideoai.com'},body:'{}'}),'film','submit',overrides);
  assert.deepEqual(scheduled,[['task',{userId:'owner',projectId:'film',requestId}]]);
  const deps={resolveAccess:access,scheduleWorker,serviceFactory:()=>({read:async()=>task,resume:async()=>task,recover:async()=>task,cancel:async()=>({...task,state:'failed'})})};
  const endpoint=url.replace('image-conversation','conversation-tasks/'+requestId);
  const body={action:'continue',requestId,approvalId:requestId,expectedRevision:0,maxCredits:250,policyVersion:STUDIO_TASK_POLICY_VERSION,confirmed:true};
  await handleStudioTask(new NextRequest(endpoint,{method:'POST',headers:{origin:'https://maxvideoai.com'},body:JSON.stringify(body)}),'film',requestId,'mutate',deps);
  assert.equal(scheduled.length,2);
  await handleStudioTask(new NextRequest(endpoint),'film',requestId,'read',deps);
  assert.equal(scheduled.length,2);
});
