import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {getDb} from '../frontend/src/lib/db';
import {createPaidGenerationTestSchema,startDisposablePostgres} from './helpers/disposable-postgres';
import {createStudioAnalysisService} from '../frontend/src/server/studio/media-analysis/service';
import {runStudioAnalysisWorkerOnce} from '../frontend/src/server/studio/media-analysis/worker';
import {studioAssistancePolicy} from '../frontend/src/server/studio/assistance-policy';
import {readStudioAssistanceStatus,reserveStudioAssistanceCall,openStudioAssistanceTurn,chooseStudioAssistance} from '../frontend/src/server/studio/assistance-ledger';

const analysisPolicy={version:'test-analysis-v1',processingNanoUsdPerSecond:100_000,marginPercent:1,video:{maxInputTokens:20_000,maxOutputTokens:2200},audio:null};
test('analysis has owned quotes, shared funding and durable exactly-once provider recovery',async t=>{
  const pg=await startDisposablePostgres('studio-analysis'),previous=process.env.DATABASE_URL;
  process.env.DATABASE_URL=pg.databaseUrl;
  t.after(async()=>{await getDb().end();if(previous===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=previous;await pg.cleanup();});
  await createPaidGenerationTestSchema(pg.pool);
  await pg.pool.query(`CREATE TABLE studio_projects(id text PRIMARY KEY,user_id text NOT NULL,deleted_at timestamptz);
    CREATE TABLE job_outputs(id text PRIMARY KEY,job_id text,user_id text,kind text,url text,mime_type text,status text);
    CREATE TABLE media_assets(id text PRIMARY KEY,public_id text,user_id text,kind text,url text,mime_type text,status text,original_name text,deleted_at timestamptz,metadata jsonb,source_job_id text,source_output_id text,thumb_url text,preview_url text,size_bytes bigint);`);
  for(const name of ['54_studio_assistance_ledger.sql','62_studio_assistance_resolutions.sql','63_studio_assistance_credits.sql','64_studio_media_analysis.sql'])await pg.pool.query(readFileSync('neon/migrations/'+name,'utf8'));
  const actor={userId:'analysis-owner',projectId:'film',authMethod:'studio-session' as const,clientId:null};
  const assistancePolicy=studioAssistancePolicy({STUDIO_ASSISTANCE_ENABLED:'true'});
  await pg.pool.query("INSERT INTO studio_projects VALUES('film','analysis-owner',null),('foreign','someone-else',null)");
  const ref={type:'asset' as const,assetId:'ma_'+'a'.repeat(32),kind:'video' as const};
  await pg.pool.query(`INSERT INTO media_assets(id,public_id,user_id,kind,url,mime_type,status,size_bytes,metadata) VALUES('media',$1,$2,'video','https://cdn.maxvideoai.com/owned.mp4','video/mp4','ready',1000,$3::jsonb)`,[ref.assetId,actor.userId,JSON.stringify({mediaFacts:{source:'probe',durationSec:30,hasAudio:true}})]);
  const service=createStudioAnalysisService(actor,{policy:analysisPolicy,assistancePolicy});
  const {resolveStudioMedia}=await import('../frontend/src/server/studio/media-resolver');
  assert.equal((await resolveStudioMedia(actor.userId,ref)).durationSec,30);
  const request={ref,goal:'Find the turn',reason:'requested' as const,startSec:0,endSec:30};
  const key=randomUUID(),quote=await service.prepare(request,key);
  assert.equal((await readStudioAssistanceStatus(actor.userId,assistancePolicy)).credits?.included.reserved,0,'Preparation never reserves or grants');
  assert.equal((await pg.pool.query('SELECT count(*)::int n FROM studio_assistance_credit_lots')).rows[0].n,0);
  assert.equal((await service.prepare(request,key)).analysisId,quote.analysisId);
  await assert.rejects(service.prepare({...request,goal:'Another goal'},key),/identity|conflict/i);
  await assert.rejects(createStudioAnalysisService({...actor,projectId:'foreign'},{policy:analysisPolicy,assistancePolicy}).prepare(request,randomUUID()),/PROJECT|project/i);
  await assert.rejects(createStudioAnalysisService({...actor,userId:'intruder'},{policy:analysisPolicy,assistancePolicy}).read(quote.analysisId),/available|project/i);
  const confirmation={analysisId:quote.analysisId,maxCredits:quote.maxCredits,policyVersion:quote.policyVersion,confirmed:true};
  await assert.rejects(service.confirm({...confirmation,maxCredits:quote.maxCredits+10}),/quote|credits/i);
  const confirmed=await Promise.all([service.confirm(confirmation),service.confirm(confirmation)]);
  assert.ok(confirmed.every(value=>value.state==='queued'));
  assert.equal((await readStudioAssistanceStatus(actor.userId,assistancePolicy)).credits?.included.reserved,quote.maxCredits);
  let calls=0;
  const worker={policy:analysisPolicy,assistancePolicy,extract:async()=>({frames:[{atSec:0,imageUrl:'data:image/jpeg;base64,AAAA'}],sourceHash:'hash'}),
    provider:async()=>({inputTokens:100,dispatch:async()=>{calls++;return {id:'analysis-response',model:'gpt-6.1-sol',serviceTier:'default',usage:{input_tokens:100,input_tokens_details:{cached_tokens:0},output_tokens:20},outputText:JSON.stringify({summary:'A turn occurs.',observations:[{startSec:10,endSec:12,text:'Character turns.',kind:'observed'}]}),inputTokens:100,outputTokenBound:2200,providerNanoUsd:450_000};}})};
  await runStudioAnalysisWorkerOnce(worker);
  const done=await service.read(quote.analysisId);
  assert.equal(done.state,'completed');assert.equal(done.result?.coverage.complete,false);assert.deepEqual(done.result?.coverage.sampledAtSec,[0]);assert.ok(done.chargedCredits!<=quote.maxCredits);
  assert.equal(calls,1);await service.confirm(confirmation);await runStudioAnalysisWorkerOnce(worker);assert.equal(calls,1);
  assert.equal((await pg.pool.query('SELECT count(*)::int n FROM studio_assistance_calls')).rows[0].n,0,'Analysis never fabricates a Responses chat call');
  assert.equal((await readStudioAssistanceStatus(actor.userId,assistancePolicy)).credits?.included.reserved,0);
  const stale=await service.prepare(request,randomUUID());
  await pg.pool.query("UPDATE media_assets SET url='https://cdn.maxvideoai.com/replaced.mp4' WHERE id='media'");
  await assert.rejects(service.confirm({...confirmation,analysisId:stale.analysisId}),/source changed/i);
  await pg.pool.query("UPDATE media_assets SET url='https://cdn.maxvideoai.com/owned.mp4' WHERE id='media'");
  const recover=await service.prepare(request,randomUUID());await service.confirm({...confirmation,analysisId:recover.analysisId});
  await pg.pool.query(`CREATE FUNCTION fail_analysis_settlement() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Controlled lost settlement'; END; $$;
    CREATE TRIGGER fail_analysis_settlement BEFORE UPDATE ON studio_analysis_credit_funding FOR EACH ROW EXECUTE FUNCTION fail_analysis_settlement();`);
  await runStudioAnalysisWorkerOnce({...worker,provider:async()=>({inputTokens:100,dispatch:async()=>{calls++;return {id:'saved-response',model:'gpt-6.1-sol',serviceTier:'default',usage:{input_tokens:100,input_tokens_details:{cached_tokens:0},output_tokens:20},outputText:'{"summary":"Saved observation","observations":[]}',inputTokens:100,outputTokenBound:2200,providerNanoUsd:450_000};}})});
  assert.equal((await service.read(recover.analysisId)).state,'unknown');
  await pg.pool.query('DROP TRIGGER fail_analysis_settlement ON studio_analysis_credit_funding; DROP FUNCTION fail_analysis_settlement()');
  await runStudioAnalysisWorkerOnce({...worker,policy:null,provider:async()=>{throw new Error('Saved supplier response must not dispatch again');}});
  assert.equal((await service.read(recover.analysisId)).state,'completed');assert.equal(calls,2);
  await pg.pool.query("INSERT INTO app_receipts(user_id,type,amount_cents,currency) VALUES('analysis-owner','topup',200,'USD')");
  let funding=await readStudioAssistanceStatus(actor.userId,assistancePolicy);
  funding=await chooseStudioAssistance(actor.userId,{action:'purchase_pack',amountCents:200,tariffVersion:funding.tariff.version,expectedRevision:funding.revision,purchaseKey:randomUUID()},assistancePolicy);
  funding=await chooseStudioAssistance(actor.userId,{action:'disable_paid',expectedRevision:funding.revision},assistancePolicy);
  await pg.pool.query("UPDATE studio_assistance_credit_lots SET consumed_credits=total_credits WHERE user_id=$1 AND kind='included'",[actor.userId]);
  const paid=await service.prepare(request,randomUUID());
  await assert.rejects(service.confirm({...confirmation,analysisId:paid.analysisId}),/paused|available Sol credits/i);
  await chooseStudioAssistance(actor.userId,{action:'resume_paid',tariffVersion:funding.tariff.version,expectedRevision:funding.revision},assistancePolicy);
  await service.confirm({...confirmation,analysisId:paid.analysisId});await runStudioAnalysisWorkerOnce(worker);assert.equal(calls,3);
  const unknown=await service.prepare(request,randomUUID());await service.confirm({...confirmation,analysisId:unknown.analysisId});
  await runStudioAnalysisWorkerOnce({...worker,provider:async()=>({inputTokens:100,dispatch:async()=>{throw new Error('Lost provider reply');}})});
  assert.equal((await service.read(unknown.analysisId)).state,'unknown');
  await runStudioAnalysisWorkerOnce(worker);assert.equal(calls,3,'Unknown dispatch never retries');
  const turn=randomUUID();await openStudioAssistanceTurn(actor,turn,assistancePolicy);
  await assert.rejects(reserveStudioAssistanceCall({...actor,requestId:turn,leaseId:randomUUID(),index:0,inputTokens:100,outputTokens:20},assistancePolicy),/unresolved/i);
  assert.equal((await readStudioAssistanceStatus(actor.userId,assistancePolicy)).unresolvedCalls,1);
  funding=await readStudioAssistanceStatus(actor.userId,assistancePolicy);
  await chooseStudioAssistance(actor.userId,{action:'select_luna',expectedRevision:funding.revision},assistancePolicy);
  const lunaTurn=randomUUID();await openStudioAssistanceTurn(actor,lunaTurn,assistancePolicy);
  await assert.rejects(reserveStudioAssistanceCall({...actor,requestId:lunaTurn,leaseId:randomUUID(),index:0,inputTokens:100,outputTokens:20},assistancePolicy),/unresolved/i);
});
