import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import test from 'node:test';
import {getDb} from '../frontend/src/lib/db';
import {startDisposablePostgres,createPaidGenerationTestSchema} from './helpers/disposable-postgres';

test('Sol packs debit once, accumulate, and reserve free credits before purchased lots',async t=>{
  const credits=await import('../frontend/src/server/studio/assistance-credit-ledger').catch(()=>null);
  assert.ok(credits,'A real prepaid credit ledger is required');
  const pg=await startDisposablePostgres('studio-credit-packs'),old=process.env.DATABASE_URL;
  process.env.DATABASE_URL=pg.databaseUrl;
  t.after(async()=>{await getDb().end();if(old===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=old;await pg.cleanup();});
  await createPaidGenerationTestSchema(pg.pool);
  for(const file of ['54_studio_assistance_ledger.sql','62_studio_assistance_resolutions.sql','63_studio_assistance_credits.sql'])await pg.pool.query(readFileSync('neon/migrations/'+file,'utf8'));
  const ledger=await import('../frontend/src/server/studio/assistance-ledger');
  const {studioAssistancePolicy}=await import('../frontend/src/server/studio/assistance-policy');
  const policy=studioAssistancePolicy({STUDIO_ASSISTANCE_ENABLED:'true'});
  await pg.pool.query("INSERT INTO app_receipts(user_id,type,amount_cents,currency) VALUES('owner','topup',2000,'USD')");
  let status=await ledger.readStudioAssistanceStatus('owner',policy);
  assert.equal(status.credits?.included.remaining,500);
  const first={action:'purchase_pack' as const,amountCents:200 as const,tariffVersion:status.tariff.version,expectedRevision:0,purchaseKey:randomUUID()};
  const duplicate=await Promise.all([ledger.chooseStudioAssistance('owner',first,policy),ledger.chooseStudioAssistance('owner',first,policy)]);
  status=duplicate[0];
  assert.equal(status.credits?.purchased.remaining,2000);
  await ledger.chooseStudioAssistance('owner',first,policy);
  assert.equal((await pg.pool.query("SELECT sum(CASE WHEN type='charge' THEN -amount_cents ELSE amount_cents END)::int balance FROM app_receipts WHERE user_id='owner'")).rows[0].balance,1800);
  status=await ledger.chooseStudioAssistance('owner',{...first,amountCents:1000,purchaseKey:randomUUID(),expectedRevision:status.revision},policy);
  assert.equal(status.credits?.purchased.total,12000);
  assert.equal(status.credits?.purchased.remaining,12000);
  assert.equal(status.credits?.purchased.packs.length,2);
  const actor={userId:'owner',projectId:'film',authMethod:'studio-session' as const,clientId:null},requestId=randomUUID();
  await ledger.openStudioAssistanceTurn(actor,requestId,policy);
  const call=await ledger.reserveStudioAssistanceCall({...actor,requestId,leaseId:randomUUID(),index:0,inputTokens:0,outputTokens:2200},policy);
  status=await ledger.readStudioAssistanceStatus('owner',policy);
  assert.equal(status.credits?.included.reserved,50);
  assert.equal(status.credits?.purchased.reserved,0);
  await ledger.settleStudioAssistanceCall(call.id,'owner',{id:'credit-response',model:'gpt-6.1-sol',service_tier:'default',usage:{input_tokens:0,input_tokens_details:{cached_tokens:0},output_tokens:1000}});
  status=await ledger.readStudioAssistanceStatus('owner',policy);
  assert.equal(status.credits?.included.remaining,480);
  assert.equal(status.credits?.purchased.remaining,12000);
  assert.equal((await pg.pool.query("SELECT sum(CASE WHEN type='charge' THEN -amount_cents ELSE amount_cents END)::int balance FROM app_receipts WHERE user_id='owner'")).rows[0].balance,800,'Usage must not debit the wallet again');
  const consume=async(request:string,index:number,inputTokens:number)=>{
    const current=await ledger.reserveStudioAssistanceCall({...actor,requestId:request,leaseId:randomUUID(),index,inputTokens,outputTokens:0},policy);
    await ledger.settleStudioAssistanceCall(current.id,'owner',{id:randomUUID(),model:'gpt-6.1-sol',service_tier:'default',usage:{input_tokens:inputTokens,input_tokens_details:{cached_tokens:0},output_tokens:0}});
  };
  await consume(requestId,1,100000);
  status=await ledger.readStudioAssistanceStatus('owner',policy);
  assert.equal(status.credits?.included.remaining,0);
  assert.equal(status.credits?.purchased.packs[0].remaining,1980);
  assert.equal(status.credits?.purchased.packs[1].remaining,10000);
  const next=randomUUID();await ledger.openStudioAssistanceTurn(actor,next,policy);
  await consume(next,0,272000);await consume(next,1,272000);
  status=await ledger.readStudioAssistanceStatus('owner',policy);
  assert.equal(status.credits?.purchased.packs[0].remaining,0);
  assert.equal(status.credits?.purchased.packs[1].remaining,9260,'Consumption crosses pack boundaries in purchase order');
  status=await ledger.chooseStudioAssistance('owner',{...first,purchaseKey:randomUUID(),expectedRevision:status.revision},policy);
  assert.equal(status.credits?.purchased.total,14000);
  assert.equal(status.credits?.purchased.remaining,11260,'A later purchase must preserve prior consumption');
  await assert.rejects(ledger.chooseStudioAssistance('owner',{...first,amountCents:500},policy),/different pack/);
  await assert.rejects(ledger.chooseStudioAssistance('unfunded',{...first,purchaseKey:randomUUID()},policy),/balance|wallet/i);
  assert.equal((await pg.pool.query("SELECT count(*)::int n FROM studio_assistance_credit_lots WHERE user_id='unfunded'")).rows[0].n,0,'A failed purchase rolls its grant and account changes back');
  await pg.pool.query("INSERT INTO app_receipts(user_id,type,amount_cents,currency) VALUES('race','topup',1000,'USD')");
  const competing=await Promise.allSettled([0,1].map(()=>ledger.chooseStudioAssistance('race',{...first,purchaseKey:randomUUID()},policy)));
  assert.equal(competing.filter(result=>result.status==='fulfilled').length,1,'Distinct purchases cannot both use one stale revision');
  assert.equal((await ledger.readStudioAssistanceStatus('race',policy)).credits?.purchased.total,2000);
  const freeActor={...actor,userId:'free-race'},freeRequests=[randomUUID(),randomUUID()];
  for(const request of freeRequests)await ledger.openStudioAssistanceTurn(freeActor,request,policy);
  const simultaneous=await Promise.allSettled(freeRequests.map(request=>ledger.reserveStudioAssistanceCall({...freeActor,requestId:request,leaseId:randomUUID(),index:0,inputTokens:100000,outputTokens:0},policy)));
  assert.equal(simultaneous.filter(result=>result.status==='fulfilled').length,1,'Free credits cannot be reserved by two requests');
  assert.equal((await ledger.readStudioAssistanceStatus(freeActor.userId,policy)).credits?.included.remaining,0);
  const future={query:async<T>(sql:string,params?:unknown[])=>{const result=await pg.pool.query(sql.replaceAll("transaction_timestamp() AT TIME ZONE 'UTC'","(date_trunc('month',transaction_timestamp() AT TIME ZONE 'UTC')+interval '1 month')"),params);return result.rows as T[];}};
  const renewed=await credits.readStudioCreditBalance(future,'free-race');
  assert.equal(renewed.included.remaining,500);assert.equal(renewed.included.reserved,0);
  assert.equal(renewed.included.priorReserved,500,'An older free-credit hold remains visible separately from the new monthly grant');
  assert.equal((await pg.pool.query("SELECT sum(reserved_credits)::int held FROM studio_assistance_credit_lots WHERE user_id='free-race'")).rows[0].held,500,'Reading the next month does not erase prior holds');
  const held=(simultaneous.find(result=>result.status==='fulfilled') as PromiseFulfilledResult<Awaited<ReturnType<typeof ledger.reserveStudioAssistanceCall>>>).value;
  await ledger.settleStudioAssistanceCall(held.id,freeActor.userId,{id:randomUUID(),model:'gpt-6.1-sol',service_tier:'default',usage:{input_tokens:1000,input_tokens_details:{cached_tokens:0},output_tokens:0}});
  assert.equal((await credits.readStudioCreditBalance(future,'free-race')).included.remaining,500,'A prior-month settlement cannot consume the next grant');
  assert.equal((await ledger.readStudioAssistanceStatus('free-race',policy)).credits?.included.remaining,490);
  const lunaActor={...actor,userId:'luna-unlimited'};
  await ledger.chooseStudioAssistance(lunaActor.userId,{action:'select_luna',expectedRevision:0},{...policy,lunaAllowanceNanoUsd:1});
  const lunaRequest=randomUUID();await ledger.openStudioAssistanceTurn(lunaActor,lunaRequest,policy);
  const lunaCall=await ledger.reserveStudioAssistanceCall({...lunaActor,requestId:lunaRequest,leaseId:randomUUID(),index:0,inputTokens:128000,outputTokens:2200},{...policy,lunaAllowanceNanoUsd:1});
  assert.equal((await ledger.readStudioAssistanceStatus(lunaActor.userId,policy)).sponsoredLuna.renewal,'unlimited');
  const otherLuna=randomUUID();await ledger.openStudioAssistanceTurn(lunaActor,otherLuna,policy);
  await assert.rejects(ledger.reserveStudioAssistanceCall({...lunaActor,requestId:otherLuna,leaseId:randomUUID(),index:0,inputTokens:100,outputTokens:1},policy),error=>(error as {nextAction?:{reason:string}}).nextAction?.reason==='luna_busy');
  await assert.rejects(ledger.reserveStudioAssistanceCall({...lunaActor,requestId:otherLuna,leaseId:randomUUID(),index:0,inputTokens:128001,outputTokens:1},policy),error=>(error as {nextAction?:{reason:string}}).nextAction?.reason==='luna_request_too_large');
  await ledger.settleStudioAssistanceCall(lunaCall.id,lunaActor.userId,{id:randomUUID(),model:'gpt-6-luna',service_tier:'default',usage:{input_tokens:128000,input_tokens_details:{cached_tokens:0},output_tokens:100}});
  await ledger.reserveStudioAssistanceCall({...lunaActor,requestId:otherLuna,leaseId:randomUUID(),index:0,inputTokens:100,outputTokens:1},policy);
  const smallActor={...actor,userId:'subcent-free'},smallRequest=randomUUID();
  await ledger.openStudioAssistanceTurn(smallActor,smallRequest,policy);
  for(let index=0;index<2;index++){
    const small=await ledger.reserveStudioAssistanceCall({...smallActor,requestId:smallRequest,leaseId:randomUUID(),index,inputTokens:40,outputTokens:0},policy);
    await ledger.settleStudioAssistanceCall(small.id,smallActor.userId,{id:randomUUID(),model:'gpt-6.1-sol',service_tier:'default',usage:{input_tokens:40,input_tokens_details:{cached_tokens:0},output_tokens:0}});
  }
  assert.equal((await ledger.readStudioAssistanceStatus(smallActor.userId,policy)).credits?.included.remaining,490,'Subcent calls round once per message');
  assert.equal((await pg.pool.query('SELECT sum(f.charged_sponsored_nano_usd)::int exposure FROM studio_assistance_credit_funding f JOIN studio_assistance_calls c ON c.id=f.call_id WHERE c.user_id=$1',[smallActor.userId])).rows[0].exposure,200000,'A zero incremental credit charge must still account for supplier exposure');
  await t.test('unknown credit holds can be waived once without a second wallet refund or a late credit charge',async()=>{
    await pg.pool.query('CREATE TABLE studio_projects(id text PRIMARY KEY,user_id text NOT NULL,name text NOT NULL,deleted_at timestamptz);CREATE TABLE studio_sequences(id text PRIMARY KEY)');
    for(const file of ['50_studio_image_conversation.sql','51_studio_image_model_usage.sql','42_studio_connected_montages.sql','52_studio_conversation_runs.sql'])await pg.pool.query(readFileSync('neon/migrations/'+file,'utf8'));
    const supportActor={...actor,userId:'credit-support',projectId:randomUUID()};
    await pg.pool.query("INSERT INTO studio_projects(id,user_id,name) VALUES($1,$2,'Credit support')",[supportActor.projectId,supportActor.userId]);
    await pg.pool.query("INSERT INTO app_receipts(user_id,type,amount_cents,currency) VALUES($1,'topup',1000,'USD')",[supportActor.userId]);
    await ledger.chooseStudioAssistance(supportActor.userId,{...first,purchaseKey:randomUUID()},policy);
    const {createImageConversationService}=await import('../frontend/src/server/studio/image-conversation-service');
    const service=createImageConversationService(supportActor,{enabled:true,actionsEnabled:true,assistancePolicy:policy,countInputTokens:async()=>100000,createActionResponse:async()=>{throw new Error('unknown provider outcome');}});
    await assert.rejects(service.submit({requestId:randomUUID(),message:'Help with a scene',references:[]}),/unknown provider outcome/);
    const call=(await pg.pool.query("SELECT id,reserved_nano_usd FROM studio_assistance_calls WHERE user_id=$1 AND state='unknown'",[supportActor.userId])).rows[0];
    const {inspectStudioAssistanceResolution,applyStudioAssistanceResolution}=await import('../frontend/src/server/studio/assistance-resolution');
    const preview=await inspectStudioAssistanceResolution(call.id,'waive_unknown');
    assert.equal(preview.refundCents,0);assert.equal(preview.refundCredits,550);
    const input={callId:call.id,action:'waive_unknown' as const,expectedFingerprint:preview.fingerprint,operator:'credit-support',reason:'Unknown provider outcome in offline fixture'};
    await Promise.all([applyStudioAssistanceResolution(input),applyStudioAssistanceResolution(input)]);
    const released=await ledger.readStudioAssistanceStatus(supportActor.userId,policy);
    assert.equal(released.credits?.included.remaining,500);assert.equal(released.credits?.purchased.remaining,2000);assert.equal(released.unresolvedCalls,0);
    assert.equal((await pg.pool.query('SELECT refund_credits FROM studio_assistance_resolutions WHERE call_id=$1',[call.id])).rows[0].refund_credits,550);
    const stillUnknown=(await pg.pool.query('SELECT state,provider_max_nano_usd,reserved_nano_usd FROM studio_assistance_calls WHERE id=$1',[call.id])).rows[0];
    assert.equal(stillUnknown.state,'unknown');assert.equal(stillUnknown.provider_max_nano_usd,null);assert.equal(stillUnknown.reserved_nano_usd,call.reserved_nano_usd);
    await ledger.settleStudioAssistanceCall(call.id,supportActor.userId,{id:randomUUID(),model:'gpt-6.1-sol',service_tier:'default',usage:{input_tokens:1000,input_tokens_details:{cached_tokens:0},output_tokens:0}});
    assert.equal((await ledger.readStudioAssistanceStatus(supportActor.userId,policy)).credits?.included.remaining,500);
    assert.equal((await pg.pool.query("SELECT sum(CASE WHEN type='charge' THEN -amount_cents ELSE amount_cents END)::int balance FROM app_receipts WHERE user_id=$1",[supportActor.userId])).rows[0].balance,800);
  });
  await assert.rejects(pg.pool.query("UPDATE studio_assistance_credit_lots SET total_credits=5000,amount_cents=500 WHERE user_id='race' AND kind='purchased'"),/immutable/i,'An existing purchase cannot be silently repriced');
});

test('new credit policy keeps legacy consent inactive and projects sponsored outages consistently',async t=>{
  const pg=await startDisposablePostgres('studio-credit-status'),old=process.env.DATABASE_URL;
  process.env.DATABASE_URL=pg.databaseUrl;
  t.after(async()=>{await getDb().end();if(old===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=old;await pg.cleanup();});
  await createPaidGenerationTestSchema(pg.pool);
  for(const file of ['54_studio_assistance_ledger.sql','62_studio_assistance_resolutions.sql','63_studio_assistance_credits.sql'])await pg.pool.query(readFileSync('neon/migrations/'+file,'utf8'));
  const ledger=await import('../frontend/src/server/studio/assistance-ledger');
  const {studioAssistancePolicy}=await import('../frontend/src/server/studio/assistance-policy');
  const {STUDIO_ASSISTANCE_TARIFF}=await import('../frontend/src/lib/studio/assistance-contract');
  const policy=studioAssistancePolicy({STUDIO_ASSISTANCE_ENABLED:'true'});
  const actor={userId:'legacy-consent',projectId:'film',authMethod:'studio-session' as const,clientId:null};
  await ledger.chooseStudioAssistance(actor.userId,{action:'authorize_paid',budgetCents:200,expectedRevision:0,tariffVersion:STUDIO_ASSISTANCE_TARIFF.version},{...policy,credits:false});
  await t.test('historic authorization does not authorize new paid credits or block free Sol',async()=>{
    const status=await ledger.readStudioAssistanceStatus(actor.userId,policy);
    assert.equal(status.paid.enabled,false);assert.equal(status.mode,'included_sol');assert.equal(status.canContinue,true);
    const requestId=randomUUID(),turn=await ledger.openStudioAssistanceTurn(actor,requestId,policy);
    assert.equal(turn.mode,'included_sol');
    await ledger.reserveStudioAssistanceCall({...actor,requestId,leaseId:randomUUID(),index:0,inputTokens:100,outputTokens:0},policy);
    const stored=(await pg.pool.query('SELECT paid_enabled,tariff_version FROM studio_assistance_accounts WHERE user_id=$1',[actor.userId])).rows[0];
    assert.equal(stored.paid_enabled,true);assert.equal(stored.tariff_version,STUDIO_ASSISTANCE_TARIFF.version,'Historical authorization evidence stays intact');
  });
  const paidActor={...actor,userId:'pure-paid'};
  await pg.pool.query("INSERT INTO app_receipts(user_id,type,amount_cents,currency) VALUES($1,'topup',200,'USD')",[paidActor.userId]);
  await ledger.chooseStudioAssistance(paidActor.userId,{action:'purchase_pack',amountCents:200,expectedRevision:0,tariffVersion:policy.credits?'studio-sol-usd-2026-10-05-v2':'',purchaseKey:randomUUID()},policy);
  await pg.pool.query("UPDATE studio_assistance_credit_lots SET consumed_credits=500 WHERE user_id=$1 AND kind='included'",[paidActor.userId]);
  await pg.pool.query('UPDATE studio_assistance_campaigns SET limit_nano_usd=0');
  await t.test('unavailable free funding blocks status and dispatch, while purchased-only Sol remains usable',async()=>{
    const freeActor={...actor,userId:'outage-free'},requestId=randomUUID();
    const status=await ledger.readStudioAssistanceStatus(freeActor.userId,policy);
    assert.equal(status.canContinue,false);assert.equal(status.blockedReason,'campaign_exhausted');assert.equal(status.sponsoredAvailable,false);
    await ledger.openStudioAssistanceTurn(freeActor,requestId,policy);
    await assert.rejects(ledger.reserveStudioAssistanceCall({...freeActor,requestId,leaseId:randomUUID(),index:0,inputTokens:100,outputTokens:0},policy),error=>(error as {nextAction?:{reason:string}}).nextAction?.reason==='campaign_exhausted');
    const paidStatus=await ledger.readStudioAssistanceStatus(paidActor.userId,policy);
    assert.equal(paidStatus.canContinue,true);assert.equal(paidStatus.sponsoredAvailable,false);
    const paidRequest=randomUUID();await ledger.openStudioAssistanceTurn(paidActor,paidRequest,policy);
    await ledger.reserveStudioAssistanceCall({...paidActor,requestId:paidRequest,leaseId:randomUUID(),index:0,inputTokens:100,outputTokens:0},policy);
  });
});
