import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { createPaidGenerationTestSchema, missingDisposablePostgresCommand, startDisposablePostgres } from './helpers/disposable-postgres';
import { createFinishingJobStore } from '../frontend/src/server/tools/finishing-jobs';
import { createFinishingSourceResolver } from '../frontend/src/server/tools/finishing-source';
import { computeCanonicalFinishingBillingSnapshot } from '../frontend/server/pricing/quote-billing';
import { prepareFinishingProvider } from '../frontend/src/server/tools/finishing-providers';
import { getDb } from '../frontend/src/lib/db';
import type { ToolResult } from '../frontend/src/lib/toolbox/contract';
import type { PreparedFinishingTool } from '../frontend/src/server/tools/finishing-prepare';

test('finishing ownership, atomic wallet reservation and refunds on disposable PostgreSQL', { timeout: 60_000 }, async t => {
  const missing = missingDisposablePostgresCommand();
  if (missing) return t.skip(`Missing local PostgreSQL: ${missing}`);
  const database = await startDisposablePostgres('toolbox-finishing');
  const previousUrl = process.env.DATABASE_URL;
  process.env.DATABASE_URL = database.databaseUrl;
  t.after(async () => { await getDb().end(); if (previousUrl === undefined) delete process.env.DATABASE_URL; else process.env.DATABASE_URL = previousUrl; await database.cleanup(); });
  await createPaidGenerationTestSchema(database.pool);
  await database.pool.query(`ALTER TABLE app_jobs ALTER COLUMN thumb_url SET NOT NULL;
    CREATE TABLE media_assets (public_id text PRIMARY KEY,user_id text,url text,kind text,status text,deleted_at timestamptz,source_job_id text,created_at timestamptz DEFAULT NOW());
    CREATE TABLE job_outputs (id text PRIMARY KEY,job_id text,user_id text,url text,storage_url text,kind text,status text,created_at timestamptz DEFAULT NOW());
    INSERT INTO app_receipts (user_id,type,amount_cents,currency) VALUES ('owner','topup',100,'USD');
    INSERT INTO media_assets (public_id,user_id,url,kind,status) VALUES ('asset-owned','owner','https://media.example/original.mp4','video','ready');`);
  const jobs = createFinishingJobStore({ ensureBillingSchema: async () => {}, getUserPreferredCurrency: async () => 'USD' });
  const sources = createFinishingSourceResolver({ ensureMediaLibrarySchema: async () => {} });
  const source = { type: 'asset', assetId: 'asset-owned', kind: 'video' } as const;
  const facts = { width: 1920, height: 1080, fps: 30, durationSec: 10 };
  const provider = prepareFinishingProvider('denoise', {}, 'https://media.example/original.mp4', facts);
  await assert.rejects(computeCanonicalFinishingBillingSnapshot({ toolId: 'denoise', quality: 'standard', vendorBudgetUsd: 0.1, durationSec: 10, profileId: provider.profile.id, pricingSource: provider.profile.pricingSource }), /TOOL_PRICING_UNAVAILABLE/);
  await database.pool.query(readFileSync('neon/migrations/42_toolbox_finishing_pricing.sql','utf8'));
  const pricing = await computeCanonicalFinishingBillingSnapshot({ toolId: 'denoise', quality: 'standard', vendorBudgetUsd: 0.1, durationSec: 10, profileId: provider.profile.id, pricingSource: provider.profile.pricingSource });
  assert.equal(pricing.totalCents, 25);
  const prepared: PreparedFinishingTool = { block: { toolId: 'denoise', version: 1, inputs: [source], settings: provider.settings }, source: { source, url: 'https://media.example/original.mp4' }, facts, ...provider, pricing, released: false };
  await t.test('only owned ready originals resolve, including exact job output lineage', async () => {
    assert.equal((await sources.resolveFinishingSource('owner', source)).url, prepared.source.url);
    await assert.rejects(sources.resolveFinishingSource('other-user', source), /SOURCE_UNAVAILABLE/);
    await assert.rejects(sources.findOwnedFinishingSource('other-user', prepared.source.url), /SOURCE_UNAVAILABLE/);
    await database.pool.query(`UPDATE media_assets SET deleted_at=NOW()`);
    await assert.rejects(sources.resolveFinishingSource('owner', source), /SOURCE_UNAVAILABLE/);
    await database.pool.query(`UPDATE media_assets SET deleted_at=NULL;
      INSERT INTO app_jobs (job_id,user_id,status,thumb_url) VALUES ('source-job','owner','completed','poster');
      INSERT INTO job_outputs (id,job_id,user_id,url,storage_url,kind,status) VALUES ('exact-output','source-job','owner','https://provider.example/temporary.mp4','https://media.example/exact.mp4','video','ready')`);
    const output = { type: 'job-output', jobId: 'source-job', outputId: 'exact-output', kind: 'video' } as const;
    assert.equal((await sources.resolveFinishingSource('owner', output)).url, 'https://media.example/exact.mp4');
    await assert.rejects(sources.resolveFinishingSource('owner', { ...output, jobId: 'forged-job' }), /SOURCE_UNAVAILABLE/);
    await database.pool.query(`UPDATE app_jobs SET hidden=TRUE WHERE job_id='source-job'`);
    await assert.rejects(sources.resolveFinishingSource('owner', output), /SOURCE_UNAVAILABLE/);
  });
  await t.test('concurrent retries debit once and a job insertion failure rolls back its charge', async () => {
    const reservations = await Promise.all([jobs.reserveFinishingJob('owner','same-job','fingerprint',prepared), jobs.reserveFinishingJob('owner','same-job','fingerprint',prepared)]);
    assert.equal(reservations.filter(r => r.created).length, 1);
    assert.equal((await database.pool.query("SELECT count(*) FROM app_receipts WHERE type='charge'")).rows[0].count, '1');
    await assert.rejects(jobs.reserveFinishingJob('owner','same-job','changed-input',prepared), /REQUEST_CONFLICT/);
    await database.pool.query(`ALTER TABLE app_jobs ADD CONSTRAINT reject_test_job CHECK (job_id <> 'reject-job')`);
    await assert.rejects(jobs.reserveFinishingJob('owner','reject-job','fingerprint',prepared));
    assert.equal((await database.pool.query("SELECT count(*) FROM app_receipts WHERE job_id='reject-job'")).rows[0].count,'0');
  });
  await t.test('only one finalizer claims a result, completed jobs cannot refund, failures refund exactly once', async () => {
    await jobs.markFinishingSubmitted('owner','same-job','provider-request');
    const claims = await Promise.all([jobs.claimFinishingCompletion('owner','same-job'),jobs.claimFinishingCompletion('owner','same-job')]);
    assert.equal(claims.filter(Boolean).length,1);
    const result: ToolResult = { toolId:'denoise',version:1,jobId:'same-job',sourceAssets:[source],outputs:[{asset:{type:'job-output',jobId:'same-job',outputId:'same-job:video:0',kind:'video'},originalUrl:'https://media.example/result.mp4',kind:'video'}] };
    await jobs.completeFinishingJob('owner','same-job',result,'provider-request');
    await jobs.failFinishingJob('owner','same-job','late error','provider-request');
    assert.equal((await jobs.readFinishingJob('owner','same-job')).status,'completed');
    assert.equal((await database.pool.query("SELECT count(*) FROM app_receipts WHERE type='refund'")).rows[0].count,'0');
    await jobs.reserveFinishingJob('owner','failed-job','fingerprint',prepared);
    await Promise.all([jobs.failFinishingJob('owner','failed-job','failure',null),jobs.failFinishingJob('owner','failed-job','failure',null)]);
    assert.deepEqual((await database.pool.query("SELECT amount_cents,currency FROM app_receipts WHERE type='refund'")).rows,[{amount_cents:pricing.totalCents,currency:'USD'}]);
    await assert.rejects(jobs.readFinishingJob('other-user','same-job'),/JOB_UNAVAILABLE/);
  });
});
