import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const root = process.cwd();
const pagePath = join(root, 'frontend/app/(core)/video/[id]/page.tsx');
const contentPath = join(root, 'frontend/app/(core)/video/[id]/_components/VideoWatchContent.tsx');
const cardPath = join(root, 'frontend/app/(core)/video/[id]/_components/VideoWatchCard.tsx');
const relatedPath = join(root, 'frontend/app/(core)/video/[id]/_components/VideoWatchRelatedExamples.tsx');
const sidebarPath = join(root, 'frontend/app/(core)/video/[id]/_components/VideoWatchSidebar.tsx');
const sourceImagesPath = join(root, 'frontend/app/(core)/video/[id]/_components/VideoWatchSourceImages.tsx');
const sourceImagesClientPath = join(root, 'frontend/app/(core)/video/[id]/_components/VideoWatchSourceImages.client.tsx');
const unavailablePath = join(root, 'frontend/app/(core)/video/[id]/_components/VideoUnavailableState.tsx');
const utilsPath = join(root, 'frontend/app/(core)/video/[id]/_lib/video-watch-page-utils.ts');

const pageSource = readFileSync(pagePath, 'utf8');
const contentSource = readFileSync(contentPath, 'utf8');
const cardSource = readFileSync(cardPath, 'utf8');
const relatedSource = readFileSync(relatedPath, 'utf8');
const sidebarSource = readFileSync(sidebarPath, 'utf8');
const sourceImagesSource = existsSync(sourceImagesPath) ? readFileSync(sourceImagesPath, 'utf8') : '';
const sourceImagesClientSource = existsSync(sourceImagesClientPath) ? readFileSync(sourceImagesClientPath, 'utf8') : '';
const unavailableSource = readFileSync(unavailablePath, 'utf8');
const utilsSource = readFileSync(utilsPath, 'utf8');

test('video watch page stays a route orchestrator', () => {
  assert.ok(existsSync(pagePath), 'video watch page should exist');
  assert.ok(existsSync(contentPath), 'video watch content component should exist');
  assert.ok(existsSync(cardPath), 'video watch card shell should exist');
  assert.ok(existsSync(relatedPath), 'video watch related examples component should exist');
  assert.ok(existsSync(sidebarPath), 'video watch sidebar component should exist');
  assert.ok(existsSync(sourceImagesPath), 'video watch source images server wrapper should exist');
  assert.ok(existsSync(sourceImagesClientPath), 'video watch source images lightbox should exist');
  assert.ok(existsSync(unavailablePath), 'video unavailable component should exist');
  assert.ok(existsSync(utilsPath), 'video watch helper module should exist');

  assert.match(pageSource, /export async function generateMetadata/, 'route should keep metadata orchestration');
  assert.match(pageSource, /export default async function VideoPage/, 'route should keep page orchestration');
  assert.match(pageSource, /from '\.\/_components\/VideoWatchContent'/, 'route should import watch content');
  assert.match(pageSource, /from '\.\/_components\/VideoUnavailableState'/, 'route should import unavailable state');
  assert.match(pageSource, /from '\.\/_lib\/video-watch-page-utils'/, 'route should import helper module');
  assert.doesNotMatch(pageSource, /WatchVideoPlayer/, 'watch player rendering belongs in VideoWatchContent');
  assert.doesNotMatch(pageSource, /CopyPromptButton/, 'prompt copy UI belongs in VideoWatchContent');
  assert.doesNotMatch(pageSource, /WatchKeyFrames/, 'keyframe UI belongs in VideoWatchContent');
  assert.doesNotMatch(pageSource, /dangerouslySetInnerHTML/, 'JSON-LD script rendering belongs in VideoWatchContent');
  assert.doesNotMatch(pageSource, /function WatchCard/, 'watch card UI belongs in VideoWatchContent');
  assert.doesNotMatch(pageSource, /function serializeJsonLd/, 'JSON-LD serialization belongs in helper module');
  assert.doesNotMatch(pageSource, /function parseAspectRatio/, 'aspect parsing belongs in helper module');

  const lineCount = pageSource.split('\n').length;
  assert.ok(lineCount <= 100, `video watch page should stay below 100 lines after extraction, got ${lineCount}`);
});

test('video watch modules own rendering and helper contracts', () => {
  const readerSource = readFileSync(join(root,'frontend/components/examples/ExampleReaderContent.tsx'),'utf8');
  const contextSource = readFileSync(join(root,'frontend/components/examples/ExampleReaderContext.tsx'),'utf8');
  assert.match(contentSource,/export async function VideoWatchContent/);
  assert.match(contentSource,/ExampleReaderContent/,'direct page shares the gallery reader');
  assert.match(contentSource,/buildExampleWatchDetail/,'server owns public projection and quotes');
  assert.match(contentSource,/headingLevel="h1"/,'standalone reader owns one page heading');
  assert.match(contentSource,/videoJsonLd/);assert.match(contentSource,/breadcrumbJsonLd/);
  assert.match(readerSource,/DiscoveryVideoPlayer/);assert.match(readerSource,/clipboard.writeText\(detail.prompt\)/);
  assert.match(readerSource,/promptExpanded/);assert.match(readerSource,/historicalCost/);
  assert.match(contextSource,/Prompt improvement notes/);assert.match(contextSource,/Compare this model/);
  assert.match(contextSource,/Visual workflow context/);assert.match(contextSource,/<details>/);
  assert.match(contextSource,/WatchKeyFrames/);assert.match(contextSource,/context.details/);
  assert.doesNotMatch(contentSource,/VideoWatchSidebar|WatchVideoPlayer/,'no second reader presentation');
  assert.ok(contentSource.split('\n').length <= 120,'watch wrapper stays a server orchestrator');
  assert.match(cardSource, /export function VideoWatchCard/, 'watch card shell should be exported');
  assert.match(relatedSource, /export function VideoWatchRelatedExamples/, 'related examples component should be exported');
  assert.match(relatedSource, /\{item\.engineLabel\}/, 'related example badges should use each related video engine label');
  assert.doesNotMatch(relatedSource, /engineLabel:\s*string/, 'related examples should not accept a shared engine label prop');
  assert.match(sidebarSource, /export function VideoWatchSidebar/, 'sidebar component should be exported');
  assert.match(sourceImagesSource, /VideoWatchSourceImagesClient/, 'server source image wrapper should compose the client lightbox');
  assert.doesNotMatch(sourceImagesSource, /'use client'/, 'source image URL normalization should stay server-renderable');
  assert.match(sourceImagesClientSource, /'use client'/, 'source image lightbox should own client interaction state');
  assert.match(sourceImagesClientSource, /role="dialog"/, 'source image lightbox should use dialog semantics');
  assert.match(sourceImagesClientSource, /aria-modal="true"/, 'source image lightbox should be modal to assistive tech');
  assert.match(sourceImagesClientSource, /setSelectedIndex\(index\)/, 'source image thumbnails should open the selected image');
  assert.match(sourceImagesClientSource, /setSelectedIndex\(null\)/, 'source image lightbox should expose close actions');
  assert.match(sourceImagesClientSource, /Escape/, 'source image lightbox should close from the keyboard');
  assert.match(sourceImagesClientSource, /ArrowLeft/, 'source image lightbox should support previous-image keyboard navigation');
  assert.match(sourceImagesClientSource, /ArrowRight/, 'source image lightbox should support next-image keyboard navigation');
  assert.match(sourceImagesClientSource, /View larger/, 'source image thumbnails should advertise the enlarged view affordance');
  assert.match(sourceImagesSource, /thumbnailUrl:\s*sourceImage\.thumbUrl/, 'server wrapper should keep thumbnail and original image URLs distinct');
  assert.match(sourceImagesClientSource, /const thumbnailUrl = sourceImage\.thumbnailUrl \?\? sourceImage\.imageUrl/, 'source image grid should prefer the lightweight thumbnail URL');
  assert.match(sourceImagesClientSource, /src=\{thumbnailUrl\}/, 'source image grid should render thumbnails without changing the original lightbox URL');
  assert.match(sourceImagesClientSource, /object-contain/, 'source image previews should preserve storyboard and frame aspect ratios');
  assert.match(sourceImagesClientSource, /Open original/, 'source image lightbox should expose the original asset URL');
  assert.match(sidebarSource, /function buildHighlightItems/, 'sidebar should own highlight view model');
  assert.match(sidebarSource, /function getDetailIcon/, 'sidebar should own detail icon mapping');
  assert.match(unavailableSource, /export function VideoUnavailableState/, 'unavailable component should be exported');
  assert.match(utilsSource, /export function buildMetaTitle/, 'helper module should own metadata title building');
  assert.match(utilsSource, /export function parseAspectRatio/, 'helper module should own aspect parsing');
  assert.match(utilsSource, /export function serializeJsonLd/, 'helper module should own JSON-LD serialization');
  assert.match(utilsSource, /export function isRenderable/, 'helper module should own renderability guard');
  assert.match(utilsSource, /export type WatchPageData/, 'helper module should export route data type');
});
