'use client';
import Link from 'next/link';
import type {StudioTaskStatus} from '@/lib/studio/task-budget-contract';
import {useConversationTask} from '../_hooks/useConversationTask';
import styles from './conversation-task.module.css';
export function ConversationTask({task,projectId,accountKey,locale,onChanged,onSimplify,onAssistance}:{task:StudioTaskStatus;projectId:string;accountKey:string;locale:'en'|'fr';onChanged:()=>void;onSimplify:()=>void;onAssistance:()=>void}) {
  const control=useConversationTask(projectId,accountKey,task,onChanged),t=(en:string,fr:string)=>locale==='fr'?fr:en;
  const phases={queued:t('Waiting for Studio','En attente de Studio'),thinking:t('Working on your request','Préparation de votre demande'),reading:t('Checking the project','Lecture du projet'),preparing:t('Preparing your media','Préparation du média'),editing:t('Editing the timeline','Modification de la timeline'),recovering:t('Recovering saved work','Récupération du travail enregistré'),done:t('Request complete','Demande terminée'),paused:t('Request paused','Demande en pause'),unknown:t('Result needs verification','Résultat à vérifier')};
  const reasons={closed:t('Support closed this request after releasing its unverified reservation. Earlier recorded usage and work are preserved. You can send a new request.','Le support a clôturé cette demande et libéré sa réservation non vérifiée. L’utilisation et le travail déjà enregistrés sont conservés. Vous pouvez envoyer une nouvelle demande.'),budget:t('The approved ceiling is reached.','Le plafond autorisé est atteint.'),steps:t('More steps are needed to finish.','Des étapes supplémentaires sont nécessaires.'),output:t('The response needs a smaller scope or a complex request.','La réponse nécessite une demande plus ciblée ou un mode complexe.'),deadline:t('The working time is reached. Saved work is preserved.','Le temps de travail est atteint. Le travail enregistré est conservé.'),context:t('There is too much material to process together. Choose fewer references or a focused request.','Il y a trop de matière à traiter ensemble. Réduisez les références ou ciblez la demande.'),funding:t('Review your assistance balance or enable your purchased credits.','Vérifiez votre solde d’assistance ou activez vos crédits achetés.'),provider:t('Studio could not finish. Check its saved response before continuing.','Studio n’a pas pu terminer. Vérifiez la réponse enregistrée avant de continuer.'),usage:t('The provider usage is not yet verified. No new paid call will be made by recovery.','L’utilisation du fournisseur reste à vérifier. La récupération ne lance aucun nouvel appel payant.'),permission:t('The project or supplied media changed. Review your request.','Le projet ou les médias fournis ont changé. Revoyez votre demande.'),unavailable:t('This task is temporarily unavailable. Check its saved result.','Cette demande est temporairement indisponible. Vérifiez son résultat enregistré.'),cancelled:t('Waiting request cancelled. Recorded usage is preserved.','Demande en attente annulée. L’utilisation enregistrée est conservée.')};
  const remaining=Math.max(0,task.maxCredits-task.consumedCredits-task.reservedCredits);
  const canContinue=task.canContinue&&remaining>0&&['steps','deadline','funding','provider','unavailable'].includes(task.error??'');
  const canExtend=task.canContinue&&task.model==='gpt-6.1-sol'&&task.error==='budget'&&task.maxCredits+100<=2000;
  return <section className={styles.card} aria-label={t('Studio task','Demande Studio')} data-state={task.state}>
    <strong role="status">{phases[task.phase]}</strong>
    <p>{task.model==='gpt-6-luna'?t('Luna · Included assistance','Luna · Assistance incluse'):`${task.consumedCredits} ${t('credits used','crédits consommés')} / ${task.maxCredits} ${t('maximum','maximum')}`}{task.reservedCredits>0&&` · ${task.reservedCredits} ${t('reserved','réservés')}`}</p>
    {task.model==='gpt-6-luna'&&task.consumedCredits>0&&<p>{task.consumedCredits} {t('Sol credits already used','crédits Sol déjà consommés')}</p>}
    {task.error&&<p>{reasons[task.error]}</p>}
    {task.state==='queued'&&<p>{t('You can leave this page. Your request stays saved. If the wait continues, cancel it and try later.','Vous pouvez quitter cette page. Votre demande reste enregistrée. Si l’attente se prolonge, annulez-la et réessayez plus tard.')}</p>}
    <div className={styles.actions}>
      {canContinue&&<button disabled={control.busy} onClick={()=>void control.mutate('continue',task.maxCredits)}>{t('Continue · same ceiling','Continuer · même plafond')}</button>}
      {canExtend&&<button disabled={control.busy} onClick={()=>void control.mutate('extend',task.maxCredits+100)}>{t('Authorize +100 credits · new total ','Autoriser +100 crédits · nouveau total ')+`${task.maxCredits+100} ($${((task.maxCredits+100)/1000).toFixed(2)})`}</button>}
      {(['unknown','failed'].includes(task.state)||task.state==='paused'&&task.error==='provider')&&!['cancelled','closed'].includes(task.error??'')&&<button disabled={control.busy} onClick={()=>void control.mutate('recover')}>{t('Recover saved result · no new call','Récupérer le résultat · aucun nouvel appel')}</button>}
      {task.state==='queued'&&<button disabled={control.busy} onClick={()=>void control.mutate('cancel')}>{t('Cancel waiting request','Annuler la demande en attente')}</button>}
      {task.state==='paused'&&<button disabled={control.busy} onClick={onSimplify}>{t('Simplify the request','Simplifier la demande')}</button>}
      {task.error==='funding'&&<button onClick={onAssistance}>{t('Manage assistance','Gérer l’assistance')}</button>}
      {task.state==='unknown'&&<Link href="/contact" prefetch={false}>{t('Contact support','Contacter le support')}</Link>}
    </div>
    {control.error&&<p role="alert">{t('The action could not be verified. Refresh the result or contact support before retrying.','L’action n’a pas pu être vérifiée. Actualisez le résultat ou contactez le support avant de réessayer.')} <button onClick={onChanged}>{t('Check result','Vérifier le résultat')}</button></p>}
  </section>;
}
