'use client';

import {useEffect,useId,useRef,useState,type RefObject} from 'react';
import {ArrowLeft,ArrowUpRight,Check,ChevronDown,MessageCircle,Sparkles,X} from 'lucide-react';
import {STUDIO_SOL_PACK_CENTS,type StudioAssistanceChoice} from '@/lib/studio/assistance-contract';
import {getMcpIntegration} from '@/lib/mcp-integration-registry';
import {localizePathFromEnglish} from '@/lib/i18n/paths';
import type {StudioAssistanceProps} from './StudioAssistance.client';
import styles from './studio-assistance-credits.module.css';

const setupLinks=(['chatgpt','claude','codex'] as const).map(getMcpIntegration).filter(integration=>integration.site.publication==='live'&&integration.installation.directMcp==='available');
type Review={amountCents:200|500|1000;expectedRevision:number;tariffVersion:string;purchaseKey:string;remaining:number};

export function StudioAssistanceCreditsDialog({status,busy,error,locale,conversationBusy,choose,refresh,onChoice,trigger,onClose}:StudioAssistanceProps&{trigger:RefObject<HTMLButtonElement>;onClose:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null),back=useRef<HTMLButtonElement>(null),id=useId();
  const [view,setView]=useState<'sol'|'luna'>(status?.selectedModel==='gpt-6-luna'?'luna':'sol');
  const [pack,setPack]=useState<200|500|1000>(200),[review,setReview]=useState<Review|null>(null);
  const t=(en:string,fr:string)=>locale==='fr'?fr:en;
  const quantity=(value:number)=>new Intl.NumberFormat(locale==='fr'?'fr-FR':'en-US').format(value);
  const price=(cents:number)=>'$'+cents/100;
  useEffect(()=>{const element=dialog.current,opener=trigger.current;element?.showModal();return()=>{element?.close();opener?.focus();};},[trigger]);
  useEffect(()=>{dialog.current?.scrollTo?.({top:0});if(review)back.current?.focus();},[view,review]);
  const credits=status?.credits,locked=busy||conversationBusy||!!status?.unresolvedCalls||!!error;
  async function select(choice:StudioAssistanceChoice){if(!(choice.action==='disable_paid'?busy||!!error:locked)&&await choose(choice)){onChoice();onClose();}}
  function startReview(){if(locked||!status||!credits)return;setReview({amountCents:pack,expectedRevision:status.revision,tariffVersion:status.tariff.version,purchaseKey:crypto.randomUUID(),remaining:credits.purchased.remaining});}
  return <dialog ref={dialog} className={styles.dialog} aria-labelledby={id} onCancel={event=>{event.preventDefault();if(!busy)onClose();}} onClick={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}>
    <header className={styles.heading}><div><span className={styles.eyebrow}>STUDIO ASSISTANCE</span><h2 id={id}>{review?t('A little more Sol.','Un peu plus de Sol.'):locale==='fr'?<>Donnez vie à vos <em>idées.</em></>:<>Keep your ideas <em>moving.</em></>}</h2></div><button autoFocus className={styles.close} disabled={busy} aria-label={t('Close assistance','Fermer l’assistance')} onClick={onClose}><X size={18}/></button></header>
    {error&&<div role="alert" className={styles.notice}><p>{error==='STALE'?t('Your credits or tariff changed. Refresh, then review your choice again.','Vos crédits ou le tarif ont changé. Actualisez puis vérifiez votre choix.'):error==='WALLET_INSUFFICIENT'?t('Your MaxVideoAI balance cannot fund this pack. Top up your balance to continue.','Votre solde MaxVideoAI ne suffit pas pour ce pack. Rechargez-le pour continuer.'):t('We could not verify this operation. Refresh your credits before trying again.','Nous n’avons pas pu vérifier cette opération. Actualisez vos crédits avant de réessayer.')}</p><button disabled={busy} onClick={()=>void refresh()}>{t('Refresh usage','Actualiser l’utilisation')}</button>{error==='WALLET_INSUFFICIENT'&&<a href="/billing" target="_blank" rel="noopener noreferrer">{t('Top up balance','Recharger le solde')}</a>}</div>}
    {!!status?.unresolvedCalls&&<p className={styles.notice} role="status">{t('A previous assistance cost needs verification. Its reserved credits stay held until settlement or a support release.','Un coût d’assistance précédent doit être vérifié. Les crédits réservés restent bloqués jusqu’à confirmation ou restitution par le support.')} <a href="/contact" target="_blank" rel="noopener noreferrer">{t('Contact support','Contacter le support')}</a></p>}
    {status&&credits&&(review?<section className={styles.purchase}>
      <button ref={back} className={styles.back} disabled={busy} onClick={()=>setReview(null)}><ArrowLeft size={13}/>{t('Back to assistance','Retour à l’assistance')}</button>
      <div className={styles.purchaseSummary}><div><Sparkles size={18}/><h3>{quantity(review.amountCents*10)} {t('Sol credits','crédits Sol')}</h3><p>{t('For GPT‑6.1 Sol creative direction and planning.','Pour la direction créative et la planification avec GPT‑6.1 Sol.')}</p></div><strong>{price(review.amountCents)}<small>{t('one-time','achat unique')}</small></strong></div>
      <dl className={styles.purchaseTotals}><div><dt>{t('Purchased credits left','Crédits achetés restants')}</dt><dd>{quantity(review.remaining)}</dd></div><div><dt>{t('This pack adds','Ce pack ajoute')}</dt><dd>+{quantity(review.amountCents*10)}</dd></div><div><dt>{t('New purchased balance','Nouveau solde acheté')}</dt><dd>{quantity(review.remaining+review.amountCents*10)} {t('credits','crédits')}</dd></div></dl>
      <p>{t('Your free credits are always used first. This pack adds to your existing balance.','Vos crédits gratuits sont toujours utilisés en premier. Ce pack s’ajoute à votre solde actuel.')}</p>
      <p className={styles.purchaseDisclosure}>{t('This purchase deducts ','Cet achat prélève ')}<strong>{price(review.amountCents)}</strong>{t(' from your MaxVideoAI balance and enables purchased Sol usage after your free credits. No subscription or automatic refill.',' sur votre solde MaxVideoAI et active l’utilisation des crédits Sol achetés après les gratuits. Sans abonnement ni recharge automatique.')}</p>
      <button className={styles.primary} disabled={locked} onClick={()=>void select({action:'purchase_pack',amountCents:review.amountCents,expectedRevision:review.expectedRevision,tariffVersion:review.tariffVersion,purchaseKey:review.purchaseKey})}>{busy?t('Purchasing…','Achat en cours…'):t('Confirm purchase · ','Confirmer l’achat · ')+price(review.amountCents)}<ArrowUpRight size={15}/></button>
    </section>:<>
      <p className={styles.intro}>{t('Choose the right partner for the work ahead.','Choisissez le partenaire adapté à vos idées.')}</p>
      <div className={styles.models} role="group" aria-label={t('Assistant model','Modèle d’assistance')}>
        <button aria-pressed={view==='sol'} onClick={()=>setView('sol')}><div><Sparkles size={15}/><span>GPT‑6.1 Sol</span>{status.selectedModel==='gpt-6.1-sol'&&<Check size={14}/>}</div><small>{t('Creative direction & detailed planning','Direction créative et plans détaillés')}</small></button>
        <button aria-pressed={view==='luna'} onClick={()=>setView('luna')}><div><MessageCircle size={15}/><span>GPT‑6 Luna</span>{status.selectedModel==='gpt-6-luna'&&<Check size={14}/>}</div><small>{t('Everyday chat & simple edits','Conversations et retouches simples')}</small></button>
      </div>
      {view==='sol'?<>
        <div className={styles.usage}><div className={styles.usageTitle}><h3>{t('Your Sol credits','Vos crédits Sol')}</h3><span>{quantity(credits.creditsPerDollar)} {t('credits = $1','crédits = $1')}</span></div>
          <section><div><span>{t('Included this month','Inclus ce mois-ci')}</span></div><p className={styles.creditCount}><strong>{quantity(credits.included.remaining)}</strong><span>/ {quantity(credits.included.total)} {t('credits left','crédits restants')}</span></p><progress max={credits.included.total} value={credits.included.remaining} aria-label={t('Monthly included Sol credits remaining','Crédits Sol mensuels restants')}/><small>{t('Used first · renews ','Utilisés en premier · renouvellement le ')}{new Intl.DateTimeFormat(locale,{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(credits.included.renewsAt))}</small>{credits.included.reserved>0&&<small className={styles.held}>{quantity(credits.included.reserved)} {t('reserved','réservés')}</small>}</section>
          <section><div><span>{t('Purchased balance','Solde acheté')}</span></div><p className={styles.creditCount}><strong>{quantity(credits.purchased.remaining)}</strong><span>/ {quantity(credits.purchased.total)} {t('credits left','crédits restants')}</span></p><progress max={credits.purchased.total||1} value={credits.purchased.remaining} aria-label={t('Purchased Sol credits remaining','Crédits Sol achetés restants')}/><small>{quantity(credits.purchased.total)} {t('bought','achetés')} · {quantity(credits.purchased.total-credits.purchased.remaining-credits.purchased.reserved)} {t('used','utilisés')}</small>{credits.purchased.reserved>0&&<small className={styles.held}>{quantity(credits.purchased.reserved)} {t('reserved','réservés')}</small>}</section>
        </div>
        {credits.purchased.packs.length>0&&<details className={`${styles.details} ${styles.packHistory}`}><summary>{t('Purchased packs','Packs achetés')} · {credits.purchased.packs.length}<ChevronDown size={13}/></summary><ol>{credits.purchased.packs.map((item,index)=><li key={item.id}><div><span>{t('Pack','Pack')} {index+1} · {price(item.amountCents)}</span><span>{quantity(item.remaining)} / {quantity(item.total)} · {Math.round(item.remaining/item.total*100)}%</span></div><progress max={item.total} value={item.remaining} aria-label={t('Sol pack ','Pack Sol ')+(index+1)+t(' credits remaining',' : crédits restants')}/>{item.reserved>0&&<small>{quantity(item.reserved)} {t('reserved','réservés')}</small>}</li>)}</ol><p>{t('Free credits first, then purchased packs in purchase order.','Les crédits gratuits en premier, puis les packs dans l’ordre d’achat.')}</p></details>}
        <section className={styles.packs}><h3>{t('A little more room to create.','Un peu plus de liberté pour créer.')}</h3><div className={styles.packOptions} role="group" aria-label={t('Sol pack price','Prix du pack Sol')}>{STUDIO_SOL_PACK_CENTS.map(amount=><button key={amount} disabled={locked} aria-pressed={pack===amount} onClick={()=>setPack(amount)}>{price(amount)}{' '}<small>{quantity(amount*10)} {t('credits','crédits')}</small></button>)}</div><button className={styles.primary} disabled={locked} onClick={startReview}>{t('Buy ','Acheter le pack Sol à ')+price(pack)+t(' Sol pack','')}<ArrowUpRight size={15}/></button><small>{t('Packs add up · no automatic refill','Les packs se cumulent · sans recharge automatique')}</small></section>
        {(status.selectedModel!=='gpt-6.1-sol'||(!status.paid.enabled&&credits.purchased.remaining>0))&&<button className={styles.primary} disabled={locked} onClick={()=>void select(!status.paid.enabled&&credits.purchased.remaining>0?{action:'resume_paid',expectedRevision:status.revision,tariffVersion:status.tariff.version}:{action:'select_sol',expectedRevision:status.revision})}>{t('Continue with GPT‑6.1 Sol','Continuer avec GPT‑6.1 Sol')}<ArrowUpRight size={15}/></button>}
        {status.paid.enabled&&<button className={styles.link} disabled={busy||!!error} onClick={()=>void select({action:'disable_paid',expectedRevision:status.revision})}>{t('Pause purchased Sol usage','Suspendre les crédits Sol achetés')}</button>}
        <div className={styles.lunaNudge}><span>{t('Keep going with Luna, free.','Continuez gratuitement avec Luna.')}</span><button onClick={()=>setView('luna')}>{t('Explore Luna','Découvrir Luna')}<ArrowUpRight size={12}/></button></div>
      </>:<section className={styles.lunaView}><span className={styles.free}>{t('INCLUDED','INCLUS')}</span><h3>{t('Unlimited everyday chat.','Échangez sans quota mensuel.')}</h3><p>{t('Talk through an idea, refine a prompt, or make a simple edit. Luna keeps the conversation flowing.','Explorez une idée, affinez un prompt ou faites une retouche simple. Luna vous accompagne au quotidien.')}</p><div className={styles.fairUse}><strong>{t('Plenty of room for a conversation.','De la place pour vos conversations.')}</strong><p>{t('One message at a time, with a generous request-size limit. Fair use and service availability apply.','Un message à la fois, avec une limite de taille généreuse. Selon un usage raisonnable et la disponibilité du service.')}</p></div><p className={styles.complex}>{t('For intricate creative direction or detailed plans, choose ','Pour une direction créative complexe ou des plans détaillés, choisissez ')}<strong>GPT‑6.1 Sol.</strong></p><button className={styles.primary} disabled={locked} onClick={()=>void select({action:'select_luna',expectedRevision:status.revision})}>{t('Continue with GPT‑6 Luna','Continuer avec GPT‑6 Luna')}<ArrowUpRight size={15}/></button><button className={styles.link} onClick={()=>setView('sol')}>{t('Explore GPT‑6.1 Sol','Découvrir GPT‑6.1 Sol')}</button></section>}
      <details className={styles.details}><summary>{t('How credits & pricing work','Crédits et tarifs : comment ça marche')}<ChevronDown size={13}/></summary><p>{t('1,000 credits = $1 of Sol usage. Input, cached input and output have different costs; credits express that usage in one unit. All calls within a message are added together, then rounded up to the next cent.','1 000 crédits = $1 d’utilisation de Sol. L’entrée, l’entrée en cache et la sortie ont des coûts différents ; les crédits les expriment dans une seule unité. Les appels d’un message sont additionnés, puis arrondis au centime supérieur.')}</p><p>{t('Per million tokens: ','Par million de tokens : ')}${status.tariff.noncachedInputUsdPerMillion} {t('input','entrée')} · ${status.tariff.cachedInputUsdPerMillion} {t('cached input','entrée en cache')} · ${status.tariff.outputUsdPerMillion} {t('output, including reasoning.','sortie, raisonnement compris.')}</p><p>{t('500 free credits renew each calendar month in UTC and do not accumulate. Purchased credits accumulate without expiry. No subscription or automatic refill.','500 crédits gratuits sont renouvelés chaque mois calendaire en UTC, sans report. Les crédits achetés se cumulent sans expiration. Sans abonnement ni recharge automatique.')}</p><p>{t('Long conversations and references use more input. Up to four model calls per message, including retries.','Les longues conversations et les références utilisent davantage d’entrée. Jusqu’à quatre appels par message, nouvelles tentatives comprises.')}</p><small>{status.tariff.version}</small></details>
      <footer className={styles.footer}><p>{t('Images, videos & exports are priced and confirmed separately.','Images, vidéos et exports ont leurs propres tarifs et confirmations.')}</p><div className={styles.mcp}><a href={`https://maxvideoai.com${localizePathFromEnglish(locale,'/mcp')}`} target="_blank" rel="noopener noreferrer">{t('Use your own assistant via MCP','Utilisez votre propre assistant via MCP')}<ArrowUpRight size={11}/></a><nav aria-label={t('MCP connection guides','Guides de connexion MCP')}>{setupLinks.map(integration=><a key={integration.id} href={`https://maxvideoai.com${localizePathFromEnglish(locale,integration.englishPath)}#setup`} target="_blank" rel="noopener noreferrer">{integration.label}</a>)}</nav></div><p className={styles.mcpNote}>{t('Your assistant’s plan and usage limits apply.','Les conditions et limites de votre assistant s’appliquent.')}</p></footer>
    </>)}
  </dialog>;
}
