import type { AiStrategistModelEntry, AiStrategistModelId, AiStrategistTierPosition } from './types';

export const AI_STRATEGIST_KNOWLEDGE_VERSION = '0.1.0';

export const AI_STRATEGIST_MODELS: readonly AiStrategistModelEntry[] = [
  {
    id: 'seedance-2-0-fast',
    label: 'Seedance 2.0 Fast',
    tierPosition: 'value',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video'],
    bestFor: ['Fast iteration loops', 'paid social variants', 'timing tests', 'motion-first drafts'],
    avoidFor: ['Final hero product ads', 'precise packaging text', '4K product detail', 'high-control brand films'],
    strengths: ['Very fast draft speed', 'good motion energy', 'strong value for testing multiple concepts'],
    weaknesses: ['Less fine detail than premium models', 'lower final polish for product closeups'],
    promptStyle:
      'Use a concise action-first prompt with the subject, camera move, setting, duration, and one clear visual priority.',
    recommendedUseCases: ['social-ad', 'character-scene', 'cinematic-scene'],
    relativeCostLevel: 'low',
    relativeSpeedLevel: 'very-fast',
    qualityLevel: 'standard',
    realismScore: 4,
    motionScore: 4,
    productDetailScore: 3,
    socialAdScore: 4,
    promptGuidance: [
      'State the main subject and action in the first sentence.',
      'Use one camera move and one lighting direction instead of stacking many controls.',
      'Keep product claims simple and visual for fast A/B tests.',
    ],
    negativePromptGuidance: [
      'Avoid asking for exact small text or labels.',
      'Avoid dense multi-shot continuity requirements in a single prompt.',
    ],
    appEngineAliases: ['seedance-2-0-fast'],
    personImageToVideoCompatibility: 'conditional',
    routingNotes: [
      'Avoid for uploaded real-person image-to-video preservation; use only when the person or character image was generated in a compatible workflow first.',
    ],
  },
  {
    id: 'seedance-2-0',
    label: 'Seedance 2.0',
    tierPosition: 'medium',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video', 'video-to-video'],
    bestFor: ['Balanced production drafts', 'character motion', 'reference-guided scenes', 'social ad variants'],
    avoidFor: ['Strict packshot precision', 'premium 4K detail', 'strict typography recreation'],
    strengths: ['Strong motion', 'balanced realism', 'good creative range', 'useful reference handling'],
    weaknesses: ['Less product-detail authority than Kling 4K', 'not the cheapest option for bulk drafts'],
    promptStyle:
      'Write a complete scene prompt with subject, motivation, action, shot language, and reference anchors when available.',
    recommendedUseCases: ['cinematic-scene', 'character-scene', 'social-ad'],
    relativeCostLevel: 'medium',
    relativeSpeedLevel: 'fast',
    qualityLevel: 'high',
    realismScore: 4,
    motionScore: 5,
    productDetailScore: 4,
    socialAdScore: 4,
    promptGuidance: [
      'Use continuity anchors such as wardrobe, prop, expression, and location.',
      'Describe motion beats in sequence when the scene has character action.',
      'Include reference-image priorities before style language.',
    ],
    negativePromptGuidance: [
      'Avoid excessive lens and grading jargon that competes with the main action.',
      'Avoid using Seedance for exact product-label reproduction.',
    ],
    appEngineAliases: ['seedance-2-0'],
    personImageToVideoCompatibility: 'conditional',
    routingNotes: [
      'Better for generated character/person references than uploaded real-person preservation.',
    ],
  },
  {
    id: 'kling-3-standard',
    label: 'Kling 3 Standard',
    tierPosition: 'value',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video'],
    bestFor: ['Value product ads', 'vertical social creative', 'creator-style demos', 'commercial motion tests'],
    avoidFor: ['Premium 4K packshots', 'complex cinematic storytelling', 'strict brand asset recreation'],
    strengths: ['Good ad-readiness for cost', 'solid product motion', 'fast enough for variant testing', 'native audio and lip-sync workflows where available'],
    weaknesses: ['Less detail control than Kling Pro or 4K', 'less premium finish on hero assets'],
    promptStyle:
      'Use commercial direction: product, surface, camera path, lighting, background, and a single conversion-focused mood.',
    recommendedUseCases: ['product-ad', 'social-ad', 'brand-asset'],
    relativeCostLevel: 'low',
    relativeSpeedLevel: 'fast',
    qualityLevel: 'high',
    realismScore: 4,
    motionScore: 4,
    productDetailScore: 4,
    socialAdScore: 5,
    promptGuidance: [
      'Lead with the product and the intended ad format.',
      'Specify the surface, reflections, and camera move for product clarity.',
      'Use concise social platform language such as hook, reveal, and loop.',
      'Keep dialogue short when using audio or lip-sync workflows.',
    ],
    negativePromptGuidance: [
      'Avoid premium claims that depend on tiny label accuracy.',
      'Avoid overloading the shot with many secondary props.',
    ],
    appEngineAliases: ['kling-3-standard'],
    personImageToVideoCompatibility: 'safe',
  },
  {
    id: 'kling-3-pro',
    label: 'Kling 3 Pro',
    tierPosition: 'medium',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video'],
    bestFor: ['Product ads', 'brand social campaigns', 'controlled camera moves', 'commercial hero drafts'],
    avoidFor: ['Lowest-cost bulk tests', 'long narrative scenes with many emotional beats'],
    strengths: ['Strong product detail', 'commercial polish', 'reliable social ad composition', 'native audio and lip-sync workflows where available'],
    weaknesses: ['Higher cost than value models', 'not as cinematic as Veo for human drama'],
    promptStyle:
      'Use a polished ad brief with product hierarchy, camera path, lighting design, material detail, and end-frame intent.',
    recommendedUseCases: ['product-ad', 'social-ad', 'brand-asset'],
    relativeCostLevel: 'high',
    relativeSpeedLevel: 'medium',
    qualityLevel: 'high',
    realismScore: 4,
    motionScore: 4,
    productDetailScore: 5,
    socialAdScore: 5,
    promptGuidance: [
      'Name the hero product and its material details early.',
      'Describe the camera move as one clean commercial reveal.',
      'Use brand-safe words for lighting, color, and background rather than vague style prompts.',
      'Add concise ambience, SFX, or short dialogue when the commercial needs audio.',
    ],
    negativePromptGuidance: [
      'Avoid asking for too many scene changes in one output.',
      'Avoid contradictory surfaces, lighting directions, or camera paths.',
    ],
    appEngineAliases: ['kling-3-pro'],
    personImageToVideoCompatibility: 'safe',
  },
  {
    id: 'kling-3-4k',
    label: 'Kling 3 4K',
    tierPosition: 'best',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video'],
    bestFor: ['Premium product hero videos', '4K brand assets', 'ecommerce detail', 'high-end social ads'],
    avoidFor: ['Low-budget exploration', 'throwaway meme variants', 'very fast timing tests'],
    strengths: ['Excellent product detail', 'native 4K output', 'premium finish', 'high-resolution brand polish', 'native audio where available'],
    weaknesses: ['Premium relative cost', 'slower iteration than value models'],
    promptStyle:
      'Use a high-control product brief with exact materials, lighting, reflections, lens feel, camera path, and final frame.',
    recommendedUseCases: ['product-ad', 'brand-asset', 'social-ad'],
    relativeCostLevel: 'premium',
    relativeSpeedLevel: 'slow',
    qualityLevel: 'premium',
    realismScore: 5,
    motionScore: 4,
    productDetailScore: 5,
    socialAdScore: 4,
    promptGuidance: [
      'Describe materials, finish, reflections, and scale with concrete nouns.',
      'Use a simple camera move that protects product readability.',
      'Include end-frame composition for brand and ecommerce uses.',
      'Use subtle ambience or SFX for product reveals unless the approval pass should stay silent.',
    ],
    negativePromptGuidance: [
      'Avoid cluttered prop styling that hides the product.',
      'Avoid asking for unreadably small typography or legal copy.',
    ],
    appEngineAliases: ['kling-3-4k'],
    personImageToVideoCompatibility: 'safe',
  },
  {
    id: 'veo-3-1-fast',
    label: 'Veo 3.1 Fast',
    tierPosition: 'medium',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video', 'video-to-video'],
    bestFor: ['Fast realistic previews', 'cinematic social drafts', 'client review options', 'natural motion scenes', '4K-capable Veo tests'],
    avoidFor: ['Lowest-cost volume testing', 'strict packaging ecommerce closeups', 'strict logo reconstruction'],
    strengths: ['Strong realism at better speed', 'good cinematic framing', 'natural motion feel', 'native audio with 4K option where exposed'],
    weaknesses: ['Less premium than full Veo 3.1', 'less product-detail focused than Kling Pro'],
    promptStyle:
      'Use cinematic language with a clear subject, grounded action, location, natural light, camera behavior, and concise audio cues.',
    recommendedUseCases: ['cinematic-scene', 'character-scene', 'social-ad'],
    relativeCostLevel: 'high',
    relativeSpeedLevel: 'fast',
    qualityLevel: 'high',
    realismScore: 5,
    motionScore: 4,
    productDetailScore: 4,
    socialAdScore: 4,
    promptGuidance: [
      'Ground the scene in observable physical action.',
      'Use natural camera and lighting language instead of abstract style stacks.',
      'Keep the prompt focused on one emotional or visual beat.',
      'Add ambience, SFX, or a short spoken line when audio or lip-sync is part of the brief.',
    ],
    negativePromptGuidance: [
      'Avoid treating the fast model as the final product-detail path.',
      'Avoid asking for several unrelated shots at once.',
    ],
    appEngineAliases: ['veo-3-1-fast'],
    personImageToVideoCompatibility: 'conditional',
  },
  {
    id: 'veo-3-1-lite',
    label: 'Veo 3.1 Lite',
    tierPosition: 'value',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video', 'video-to-video'],
    bestFor: ['Budget Veo drafts', 'low-cost realistic tests', 'audio-ready social previews', 'fast cinematic iteration'],
    avoidFor: ['4K delivery', 'premium final hero shots', 'strict product preservation', 'complex reference-to-video control', 'general source-video restyling outside extend workflows'],
    strengths: ['Very low Veo-family cost', 'realistic motion language', 'native audio', 'good value for budget previews'],
    weaknesses: ['No 4K output in the Lite route', 'lower fidelity than Veo 3.1 or Veo 3.1 Fast', 'less product-detail control than Kling'],
    promptStyle:
      'Use a short Veo-style shot brief with subject, action, camera, look, format, duration, and one audio cue.',
    recommendedUseCases: ['cinematic-scene', 'social-ad', 'character-scene'],
    relativeCostLevel: 'low',
    relativeSpeedLevel: 'fast',
    qualityLevel: 'standard',
    realismScore: 4,
    motionScore: 4,
    productDetailScore: 3,
    socialAdScore: 4,
    promptGuidance: [
      'Use it when the brief wants a budget Veo-family pass before a higher-fidelity render.',
      'Keep the action simple and visible within 4-8 seconds.',
      'Use native audio for ambience, SFX, or one short line when timing matters.',
      'Treat source-video usage as an extend workflow, not a general video restyle route.',
    ],
    negativePromptGuidance: [
      'Avoid 4K delivery expectations on Lite.',
      'Avoid strict packaging, logo, or tiny text preservation.',
    ],
    appEngineAliases: ['veo-3-1-lite'],
    personImageToVideoCompatibility: 'conditional',
    routingNotes: [
      'Treat as a major value/budget option alongside LTX for realistic audio-ready drafts.',
    ],
  },
  {
    id: 'veo-3-1',
    label: 'Veo 3.1',
    tierPosition: 'best',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video', 'video-to-video'],
    bestFor: ['Cinematic realism', 'premium brand films', 'human emotion', 'natural camera movement', 'audio-ready 4K Veo outputs'],
    avoidFor: ['Low-cost ad variant batches', 'exact packaging text', 'rapid throwaway drafts'],
    strengths: ['Top realism', 'natural motion', 'cinematic lighting', 'strong human-scene credibility', 'native audio with 4K option where exposed'],
    weaknesses: ['Premium relative cost', 'less direct product-ad specialization than Kling 4K'],
    promptStyle:
      'Write like a director: subject, intention, physical action, setting, camera behavior, light, mood, audio cues, and realism constraints.',
    recommendedUseCases: ['cinematic-scene', 'character-scene', 'social-ad'],
    relativeCostLevel: 'premium',
    relativeSpeedLevel: 'slow',
    qualityLevel: 'premium',
    realismScore: 5,
    motionScore: 5,
    productDetailScore: 4,
    socialAdScore: 4,
    promptGuidance: [
      'Describe the human or physical motivation behind the action.',
      'Use realistic camera and lighting details that support the scene.',
      'Prefer one coherent cinematic moment over a list of visual effects.',
      'Use concise ambience, SFX, or dialogue cues when native audio or lip-sync matters.',
    ],
    negativePromptGuidance: [
      'Avoid exact text, label, or UI reproduction requests.',
      'Avoid mixing multiple genre styles in one short prompt.',
    ],
    appEngineAliases: ['veo-3-1'],
    personImageToVideoCompatibility: 'conditional',
  },
  {
    id: 'happy-horse-1-0',
    label: 'Happy Horse 1.0',
    tierPosition: 'medium',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'text-to-image-then-image-to-video', 'video-to-video'],
    bestFor: ['Native-audio clips', 'lip-sync and dialogue support', 'talking-avatar experiments', 'unified text/image/reference/video-edit workflows'],
    avoidFor: ['Strict product packshots', '4K delivery', 'lowest-cost bulk drafts', 'raw realism comparisons against Veo or Kling', 'real-person image-to-video preservation as the primary route'],
    strengths: ['Native synchronized audio', 'lip-sync', 'text-to-video, image-to-video, reference-to-video and video edit in one model family'],
    weaknesses: ['No 4K output route', 'higher cost than budget value models', 'less product-detail authority than Kling', 'limited for real-person image-to-video preservation'],
    promptStyle:
      'Use subject, action, camera, audio cue, and workflow-specific references; keep spoken lines short for more reliable lip-sync.',
    recommendedUseCases: ['character-scene', 'social-ad', 'cinematic-scene'],
    relativeCostLevel: 'high',
    relativeSpeedLevel: 'medium',
    qualityLevel: 'high',
    realismScore: 4,
    motionScore: 4,
    productDetailScore: 3,
    socialAdScore: 4,
    promptGuidance: [
      'Strong candidate for compatible audio/lip-sync/spokesperson workflows, but do not promote it as the automatic Best model only because dialogue is present.',
      'Keep dialogue short and tied to one clear on-camera performance beat.',
      'For reference workflows, assign each uploaded image or source clip one clear job.',
    ],
    negativePromptGuidance: [
      'Avoid long monologues or fast speech for lip-sync.',
      'Avoid exact logos, legal copy, packaging text, or 4K delivery expectations.',
    ],
    appEngineAliases: ['happy-horse-1-0'],
    personImageToVideoCompatibility: 'conditional',
    routingNotes: [
      'Strong candidate for compatible audio/lip-sync/spokesperson workflows; keep Seedance, Veo, Kling, and LTX competitive for dialogue quality.',
      'Do not use as the default Best route for uploaded real-person image-to-video preservation.',
    ],
  },
  {
    id: 'ltx-2-3',
    label: 'LTX 2.3',
    tierPosition: 'value',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'video-to-video'],
    bestFor: ['Prompt testing', 'low-cost drafts', 'vertical social exploration', 'animatics', 'audio-ready storyboard timing'],
    avoidFor: ['Photoreal final heroes', 'fine product detail', 'premium cinematic realism'],
    strengths: ['Very fast exploration', 'low relative cost', 'good for learning prompt direction', 'useful native-audio timing for drafts'],
    weaknesses: ['Lower realism ceiling', 'weaker product fidelity than Kling or Veo'],
    promptStyle:
      'Use a compact creative brief with a clear subject, action, format, and visual reference direction for fast iteration.',
    recommendedUseCases: ['social-ad', 'character-scene', 'cinematic-scene'],
    relativeCostLevel: 'low',
    relativeSpeedLevel: 'very-fast',
    qualityLevel: 'standard',
    realismScore: 3,
    motionScore: 4,
    productDetailScore: 3,
    socialAdScore: 4,
    promptGuidance: [
      'Use it to test the idea, timing, and visual language before a premium render.',
      'Keep prompts short and revise one variable at a time.',
      'State vertical, square, or landscape framing explicitly.',
      'Include simple ambience, SFX, or a short dialogue cue when audio/lip-sync timing matters.',
    ],
    negativePromptGuidance: [
      'Avoid relying on it for final photoreal product detail.',
      'Avoid long prompts with many nested constraints.',
    ],
    appEngineAliases: ['ltx-2-3-fast', 'ltx-2-3-pro'],
    personImageToVideoCompatibility: 'safe',
  },
  {
    id: 'hailuo',
    label: 'MiniMax Hailuo 02 Standard',
    tierPosition: 'value',
    supportedWorkflows: ['text-to-video', 'image-to-video'],
    bestFor: ['Budget motion tests', 'low-stakes creative drafts', 'playful social experiments', 'silent motion concepts'],
    avoidFor: ['Premium commercial recommendations', 'serious product detail', 'strict brand assets', 'hero-quality realism'],
    strengths: ['Budget-friendly testing', 'quick concept coverage', 'useful for experimental social motion'],
    weaknesses: ['Lower premium ceiling than Kling, Veo, Seedance, or LTX', 'less reliable for serious commercial detail'],
    promptStyle:
      'Use a short motion test prompt with one subject, one action, one environment, and a simple style or pacing direction.',
    recommendedUseCases: ['social-ad', 'cinematic-scene'],
    relativeCostLevel: 'low',
    relativeSpeedLevel: 'fast',
    qualityLevel: 'standard',
    realismScore: 3,
    motionScore: 3,
    productDetailScore: 2,
    socialAdScore: 3,
    promptGuidance: [
      'Use it for low-stakes creative testing before committing to a main commercial model.',
      'Keep the scene simple and motion-led.',
      'Treat the output as an exploratory direction, not final brand production.',
    ],
    negativePromptGuidance: [
      'Avoid premium product fidelity expectations.',
      'Avoid exact logos, small text, or complex character continuity.',
    ],
    appEngineAliases: ['minimax-hailuo-02-text'],
    personImageToVideoCompatibility: 'experimental',
    routingNotes: [
      'Rank below Kling, Veo, Seedance, and LTX for serious commercial or premium recommendations.',
    ],
  },
  {
    id: 'pika',
    label: 'Pika',
    tierPosition: 'value',
    supportedWorkflows: ['text-to-video', 'image-to-video'],
    bestFor: ['Playful social videos', 'stylized short clips', 'creator experiments', 'lightweight visual concepts'],
    avoidFor: ['Strict photorealism', 'premium product assets', 'complex camera continuity'],
    strengths: ['Accessible creative range', 'good short-form energy', 'useful for playful brand moments'],
    weaknesses: ['Lower realism and product-detail ceiling', 'less predictable for premium commercial work'],
    promptStyle:
      'Use a short creator-style prompt with subject, playful transformation or action, format, and a simple visual mood.',
    recommendedUseCases: ['social-ad', 'character-scene'],
    relativeCostLevel: 'low',
    relativeSpeedLevel: 'fast',
    qualityLevel: 'standard',
    realismScore: 3,
    motionScore: 3,
    productDetailScore: 2,
    socialAdScore: 4,
    promptGuidance: [
      'Use it for quick social hooks and stylized motion concepts.',
      'Keep transformations simple and visually legible.',
      'Specify the short-form context when relevant.',
    ],
    negativePromptGuidance: [
      'Avoid exact product, logo, or typography reproduction.',
      'Avoid asking for realistic multi-person continuity.',
    ],
    appEngineAliases: ['pika-text-to-video', 'pika-image-to-video'],
    personImageToVideoCompatibility: 'experimental',
    routingNotes: [
      'Rank below Kling, Veo, Seedance, and LTX except for playful transformations, effects, or low-stakes creative tests.',
    ],
  },
  {
    id: 'sora',
    label: 'Sora',
    tierPosition: 'best',
    supportedWorkflows: ['text-to-video', 'image-to-video', 'video-to-video'],
    bestFor: ['Narrative scenes', 'imaginative concepts', 'complex prompt following', 'premium cinematic ideas'],
    avoidFor: ['Lowest-cost production', 'exact product packaging', 'strict ecommerce packshots'],
    strengths: ['Strong scene coherence', 'high creative range', 'premium story and motion quality'],
    weaknesses: ['Premium relative cost', 'less focused on exact product detail than Kling 4K'],
    promptStyle:
      'Use rich scene direction with narrative intent, environment, camera movement, visual continuity, and a clear ending state.',
    recommendedUseCases: ['cinematic-scene', 'character-scene', 'social-ad'],
    relativeCostLevel: 'premium',
    relativeSpeedLevel: 'medium',
    qualityLevel: 'premium',
    realismScore: 5,
    motionScore: 5,
    productDetailScore: 3,
    socialAdScore: 4,
    promptGuidance: [
      'Give the model a coherent scene arc and ending frame.',
      'Use vivid but non-conflicting visual details.',
      'Reserve it for ideas where story and continuity matter.',
    ],
    negativePromptGuidance: [
      'Avoid exact label, logo, or small text requirements.',
      'Avoid using it as the cheapest path for simple variant testing.',
    ],
    appEngineAliases: ['sora-2', 'sora-2-pro'],
    personImageToVideoCompatibility: 'avoid',
    routingNotes: [
      'Do not use as the default best-tier pick for social ads, cheap drafts, generic fantasy prompts, or person-reference image-to-video.',
    ],
  },
];

export function getAiStrategistModel(id: AiStrategistModelId): AiStrategistModelEntry {
  const model = AI_STRATEGIST_MODELS.find((entry) => entry.id === id);
  if (!model) {
    throw new Error(`Unknown AI Strategist model: ${id}`);
  }
  return model;
}

export function getAiStrategistModelsByTier(tierPosition: AiStrategistTierPosition): readonly AiStrategistModelEntry[] {
  return AI_STRATEGIST_MODELS.filter((model) => model.tierPosition === tierPosition);
}
