import type {
  WorkspaceChatSettings,
  WorkspaceGenerationFamily,
  WorkspaceGenerationPresetId,
  WorkspaceNodeKind,
  WorkspaceShotSettings,
  WorkspaceToolKind,
  WorkspaceWorkflowType,
} from './workspace-types';
import { createWorkspaceCharacterBuilderSettings } from './workspace-tool-settings';

export type WorkspaceBlockPreset = {
  id: WorkspaceGenerationPresetId;
  menu: 'audio' | 'image' | 'text' | 'video';
  nodeKind: WorkspaceNodeKind;
  labelKey: string;
  descriptionKey: string;
  titleKey: string;
  subtitleKey: string;
  accent: string;
  family: WorkspaceGenerationFamily;
  outputKind: 'audio' | 'image' | 'text' | 'video';
  defaultModelId: string;
  defaultWorkflowType: WorkspaceWorkflowType;
  defaultShot?: WorkspaceShotSettings;
  defaultChat?: WorkspaceChatSettings;
};

function shotDefaults(input: {
  presetId: WorkspaceGenerationPresetId;
  family: WorkspaceGenerationFamily;
  outputKind: 'audio' | 'image' | 'video';
  modelId: string;
  workflowType: WorkspaceWorkflowType;
  outputName: string;
  durationSec?: number;
  toolKind?: WorkspaceToolKind;
  toolSettings?: WorkspaceShotSettings['toolSettings'];
}): WorkspaceShotSettings {
  return {
    presetId: input.presetId,
    family: input.family,
    outputKind: input.outputKind,
    toolKind: input.toolKind,
    toolSettings: input.toolSettings,
    modelId: input.modelId,
    workflowType: input.workflowType,
    durationSec: input.durationSec ?? 7,
    aspectRatio: '16:9',
    resolution: '1080p',
    fps: 24,
    seed: null,
    audioEnabled: false,
    lipSyncEnabled: false,
    referenceStrength: 0.65,
    outputName: input.outputName,
    status: 'draft',
  };
}

export const WORKSPACE_BLOCK_PRESETS: WorkspaceBlockPreset[] = [
  {
    id: 'generate-image',
    menu: 'image',
    nodeKind: 'shot',
    labelKey: 'generateImage',
    descriptionKey: 'generateImageDescription',
    titleKey: 'imageGenerationTitle',
    subtitleKey: 'imageGenerationSubtitle',
    accent: '#6366f1',
    family: 'image',
    outputKind: 'image',
    defaultModelId: 'seedream',
    defaultWorkflowType: 'text_to_image',
    defaultShot: shotDefaults({
      presetId: 'generate-image',
      family: 'image',
      outputKind: 'image',
      modelId: 'seedream',
      workflowType: 'text_to_image',
      outputName: 'Image output',
      durationSec: 1,
    }),
  },
  {
    id: 'modify-image',
    menu: 'image',
    nodeKind: 'shot',
    labelKey: 'modifyImage',
    descriptionKey: 'modifyImageDescription',
    titleKey: 'modifyImageTitle',
    subtitleKey: 'modifyImageSubtitle',
    accent: '#7c3aed',
    family: 'image',
    outputKind: 'image',
    defaultModelId: 'seedream',
    defaultWorkflowType: 'image_to_image',
    defaultShot: shotDefaults({
      presetId: 'modify-image',
      family: 'image',
      outputKind: 'image',
      modelId: 'seedream',
      workflowType: 'image_to_image',
      outputName: 'Modified image',
      durationSec: 1,
    }),
  },
  {
    id: 'generate-video',
    menu: 'video',
    nodeKind: 'shot',
    labelKey: 'generateVideo',
    descriptionKey: 'generateVideoDescription',
    titleKey: 'videoGenerationTitle',
    subtitleKey: 'videoGenerationSubtitle',
    accent: '#f97316',
    family: 'video',
    outputKind: 'video',
    defaultModelId: 'seedance-2-0',
    defaultWorkflowType: 'image_to_video',
    defaultShot: shotDefaults({
      presetId: 'generate-video',
      family: 'video',
      outputKind: 'video',
      modelId: 'seedance-2-0',
      workflowType: 'image_to_video',
      outputName: 'Video output',
    }),
  },
  {
    id: 'storyboard',
    menu: 'image',
    nodeKind: 'shot',
    labelKey: 'storyboard',
    descriptionKey: 'storyboardDescription',
    titleKey: 'storyboardGenerationTitle',
    subtitleKey: 'storyboardGenerationSubtitle',
    accent: '#38bdf8',
    family: 'image',
    outputKind: 'image',
    defaultModelId: 'storyboard-gpt-image-2',
    defaultWorkflowType: 'storyboard_generation',
    defaultShot: shotDefaults({
      presetId: 'storyboard',
      family: 'image',
      outputKind: 'image',
      modelId: 'storyboard-gpt-image-2',
      workflowType: 'storyboard_generation',
      outputName: 'Storyboard board',
      durationSec: 1,
      toolKind: 'storyboard',
      toolSettings: {
        storyboard: {
          targetModel: 'seedance',
          lengthPreset: 'medium',
          frameCount: 6,
          durationSec: 10,
          orientation: 'landscape',
          tier: '4k',
        },
      },
    }),
  },
  {
    id: 'character-builder',
    menu: 'image',
    nodeKind: 'shot',
    labelKey: 'character',
    descriptionKey: 'characterDescription',
    titleKey: 'characterGenerationTitle',
    subtitleKey: 'characterGenerationSubtitle',
    accent: '#ec4899',
    family: 'image',
    outputKind: 'image',
    defaultModelId: 'character-builder-tool',
    defaultWorkflowType: 'character_builder',
    defaultShot: shotDefaults({
      presetId: 'character-builder',
      family: 'image',
      outputKind: 'image',
      modelId: 'character-builder-tool',
      workflowType: 'character_builder',
      outputName: 'Character reference',
      durationSec: 1,
      toolKind: 'character-builder',
      toolSettings: {
        characterBuilder: createWorkspaceCharacterBuilderSettings(),
      },
    }),
  },
  {
    id: 'angle',
    menu: 'image',
    nodeKind: 'shot',
    labelKey: 'angle',
    descriptionKey: 'angleDescription',
    titleKey: 'angleGenerationTitle',
    subtitleKey: 'angleGenerationSubtitle',
    accent: '#06b6d4',
    family: 'image',
    outputKind: 'image',
    defaultModelId: 'angle-flux-multiple-angles',
    defaultWorkflowType: 'angle_generation',
    defaultShot: shotDefaults({
      presetId: 'angle',
      family: 'image',
      outputKind: 'image',
      modelId: 'angle-flux-multiple-angles',
      workflowType: 'angle_generation',
      outputName: 'Angle output',
      durationSec: 1,
      toolKind: 'angle',
      toolSettings: {
        angle: {
          rotation: 35,
          tilt: 0,
          zoom: 1,
          safeMode: true,
          generateBestAngles: false,
        },
      },
    }),
  },
  {
    id: 'modify-video',
    menu: 'video',
    nodeKind: 'shot',
    labelKey: 'modifyVideo',
    descriptionKey: 'modifyVideoDescription',
    titleKey: 'modifyVideoTitle',
    subtitleKey: 'modifyVideoSubtitle',
    accent: '#2563eb',
    family: 'video',
    outputKind: 'video',
    defaultModelId: 'luma-ray-3-2',
    defaultWorkflowType: 'video_to_video',
    defaultShot: shotDefaults({
      presetId: 'modify-video',
      family: 'video',
      outputKind: 'video',
      modelId: 'luma-ray-3-2',
      workflowType: 'video_to_video',
      outputName: 'Modified video',
    }),
  },
  {
    id: 'upscale-image',
    menu: 'image',
    nodeKind: 'shot',
    labelKey: 'upscaleImage',
    descriptionKey: 'upscaleImageDescription',
    titleKey: 'imageUpscaleTitle',
    subtitleKey: 'imageUpscaleSubtitle',
    accent: '#0ea5e9',
    family: 'upscale',
    outputKind: 'image',
    defaultModelId: 'upscale-image-seedvr',
    defaultWorkflowType: 'image_upscale',
    defaultShot: shotDefaults({
      presetId: 'upscale-image',
      family: 'upscale',
      outputKind: 'image',
      modelId: 'upscale-image-seedvr',
      workflowType: 'image_upscale',
      outputName: 'Upscaled image',
      durationSec: 1,
    }),
  },
  {
    id: 'upscale-video',
    menu: 'video',
    nodeKind: 'shot',
    labelKey: 'upscaleVideo',
    descriptionKey: 'upscaleVideoDescription',
    titleKey: 'videoUpscaleTitle',
    subtitleKey: 'videoUpscaleSubtitle',
    accent: '#0ea5e9',
    family: 'upscale',
    outputKind: 'video',
    defaultModelId: 'upscale-video-seedvr',
    defaultWorkflowType: 'video_upscale',
    defaultShot: shotDefaults({
      presetId: 'upscale-video',
      family: 'upscale',
      outputKind: 'video',
      modelId: 'upscale-video-seedvr',
      workflowType: 'video_upscale',
      outputName: 'Upscaled video',
    }),
  },
  {
    id: 'audio-music',
    menu: 'audio',
    nodeKind: 'shot',
    labelKey: 'generateMusic',
    descriptionKey: 'musicGenerationDescription',
    titleKey: 'musicGenerationTitle',
    subtitleKey: 'musicGenerationSubtitle',
    accent: '#16a34a',
    family: 'audio',
    outputKind: 'audio',
    defaultModelId: 'audio-music-only',
    defaultWorkflowType: 'music_generation',
    defaultShot: shotDefaults({
      presetId: 'audio-music',
      family: 'audio',
      outputKind: 'audio',
      modelId: 'audio-music-only',
      workflowType: 'music_generation',
      outputName: 'Music output',
      durationSec: 30,
    }),
  },
  {
    id: 'audio-voiceover',
    menu: 'audio',
    nodeKind: 'shot',
    labelKey: 'voiceOver',
    descriptionKey: 'voiceOverDescription',
    titleKey: 'voiceOverGenerationTitle',
    subtitleKey: 'voiceOverGenerationSubtitle',
    accent: '#14b8a6',
    family: 'audio',
    outputKind: 'audio',
    defaultModelId: 'audio-voice-only',
    defaultWorkflowType: 'voiceover_generation',
    defaultShot: shotDefaults({
      presetId: 'audio-voiceover',
      family: 'audio',
      outputKind: 'audio',
      modelId: 'audio-voice-only',
      workflowType: 'voiceover_generation',
      outputName: 'Voice-over output',
      durationSec: 15,
    }),
  },
  {
    id: 'audio-sfx',
    menu: 'audio',
    nodeKind: 'shot',
    labelKey: 'sfx',
    descriptionKey: 'sfxDescription',
    titleKey: 'sfxGenerationTitle',
    subtitleKey: 'sfxGenerationSubtitle',
    accent: '#7c3aed',
    family: 'audio',
    outputKind: 'audio',
    defaultModelId: 'audio-sfx-only',
    defaultWorkflowType: 'sfx_generation',
    defaultShot: shotDefaults({
      presetId: 'audio-sfx',
      family: 'audio',
      outputKind: 'audio',
      modelId: 'audio-sfx-only',
      workflowType: 'sfx_generation',
      outputName: 'SFX output',
      durationSec: 8,
    }),
  },
  {
    id: 'audio-sound-design',
    menu: 'audio',
    nodeKind: 'shot',
    labelKey: 'soundDesign',
    descriptionKey: 'soundDesignDescription',
    titleKey: 'soundDesignGenerationTitle',
    subtitleKey: 'soundDesignGenerationSubtitle',
    accent: '#f59e0b',
    family: 'audio',
    outputKind: 'audio',
    defaultModelId: 'audio-cinematic',
    defaultWorkflowType: 'cinematic_audio',
    defaultShot: shotDefaults({
      presetId: 'audio-sound-design',
      family: 'audio',
      outputKind: 'audio',
      modelId: 'audio-cinematic',
      workflowType: 'cinematic_audio',
      outputName: 'Sound design output',
      durationSec: 10,
    }),
  },
  {
    id: 'audio-sound-design-voice',
    menu: 'audio',
    nodeKind: 'shot',
    labelKey: 'soundDesignVoice',
    descriptionKey: 'soundDesignVoiceDescription',
    titleKey: 'soundDesignVoiceGenerationTitle',
    subtitleKey: 'soundDesignVoiceGenerationSubtitle',
    accent: '#f43f5e',
    family: 'audio',
    outputKind: 'audio',
    defaultModelId: 'audio-cinematic-voice',
    defaultWorkflowType: 'cinematic_voiceover',
    defaultShot: shotDefaults({
      presetId: 'audio-sound-design-voice',
      family: 'audio',
      outputKind: 'audio',
      modelId: 'audio-cinematic-voice',
      workflowType: 'cinematic_voiceover',
      outputName: 'Sound design + voice output',
      durationSec: 10,
    }),
  },
  {
    id: 'chat-box',
    menu: 'text',
    nodeKind: 'chat',
    labelKey: 'chatBox',
    descriptionKey: 'chatBoxDescription',
    titleKey: 'chatBoxTitle',
    subtitleKey: 'chatBoxSubtitle',
    accent: '#64748b',
    family: 'chat',
    outputKind: 'text',
    defaultModelId: 'studio-chat-openai',
    defaultWorkflowType: 'chat_completion',
    defaultChat: {
      mode: 'chatbot',
      botName: 'Studio assistant',
      provider: 'openai',
      modelId: 'gpt-4.1-mini',
      systemPrompt: '',
      draftMessage: '',
      messages: [],
      status: 'idle',
    },
  },
];

const LEGACY_WORKSPACE_BLOCK_PRESET_ALIASES: Record<string, WorkspaceGenerationPresetId> = {
  'character-video': 'character-builder',
  'storyboard-video': 'storyboard',
};

export function getWorkspaceBlockPreset(id?: string | null): WorkspaceBlockPreset | null {
  const resolvedId = id ? LEGACY_WORKSPACE_BLOCK_PRESET_ALIASES[id] ?? id : null;
  return WORKSPACE_BLOCK_PRESETS.find((preset) => preset.id === resolvedId) ?? null;
}
