export const DEFAULT_STORYBOARD_COPY = {
  disabledTitle: 'Tools are disabled',
  disabledBody: 'Enable `FEATURES.workflows.toolsSection` to access this area.',
  backToTools: 'Tools',
  title: 'Storyboarder',
  subtitle: 'Create a clean reference board before sending the direction to Seedance or Kling.',
  subjectLabel: 'Subject',
  subjectPlaceholder: 'Product launch, cooking scene, anime beat...',
  actionLabel: 'Action',
  actionPlaceholder: 'Reveal, pour, walk-in, product rotation...',
  dialogueLabel: 'Dialogues',
  dialoguePlaceholder: 'Voiceover: Ready in thirty seconds.\nTalent: This texture stays rich.',
  referenceImageLabel: 'Reference images',
  referenceImageTitle: 'Character, product or scene references',
  referenceImageBody: 'Upload up to 4 images to keep the same person, product, prop, packaging, style or location across the board.',
  referenceImageUpload: 'Choose image',
  referenceUploading: 'Uploading...',
  removeReferenceImage: 'Remove',
  referenceSlotNameFallback: 'Reference image',
  targetLabel: 'Video target',
  targetSeedance: 'Seedance',
  targetKling: 'Kling',
  styleLabel: 'Style',
  durationLabel: 'Duration',
  frameCountLabel: 'Frames',
  tierLabel: 'Price',
  normalTier: 'Normal',
  hqTier: 'HQ',
  generate: 'Generate storyboard',
  generating: 'Generating...',
  editLabel: 'Edit request',
  editPlaceholder: 'Change framing, product color, lighting...',
  editAction: 'Apply edit',
  shotMapTitle: 'Shot map',
  shotMapEmptyTitle: 'Planned storyboard beats',
  shotMapEmptyBody: 'Adjust the brief, dialogue, style, duration, or frame count to shape the planned storyboard.',
  emptyTitle: 'Storyboard preview',
  emptyBody: 'Fill the short brief and generate a reference board.',
  outputTitle: 'Generated storyboard',
  download: 'Download',
  editImage: 'Edit image',
  saveToLibrary: 'Save to Storyboard library',
  savedToLibrary: 'Saved to Storyboard library.',
  missingSubject: 'Add a subject first.',
  uploadFailed: 'Unable to upload the selected reference image. Try again.',
  uploadTooLarge: 'The selected image is too large. Use an image under {maxMB} MB.',
  generationFailed: 'Storyboard generation failed.',
  authTitle: 'Sign in to generate',
  authBody: 'Storyboard generation and library saves use your MaxVideoAI wallet.',
  authPrimary: 'Log in',
  authSecondary: 'Sign in',
  close: 'Close',
  targetNotes: {
    seedance: 'Seedance: no real people. Best for product, cooking, film objects, animation and stylized scenes.',
    kling: 'Kling: use this when the storyboard needs real people or realistic human scenes.',
  },
  styles: {
    realistic: 'Realistic',
    anime: 'Anime',
    ugc: 'UGC',
    cinema: 'Cinema',
  },
} as const;

export type StoryboardCopy = typeof DEFAULT_STORYBOARD_COPY;
