import React from 'react';

// One scoped style owner for the SSR watch page and the on-demand dialog.
// Keeping it in the reader removes a separate render-blocking CSS request.
const styles = {
  action: 'video-reader-action',
  backdrop: 'video-reader-backdrop',
  centerPlay: 'video-reader-centerPlay',
  close: 'video-reader-close',
  comparison: 'video-reader-comparison',
  comparisonNote: 'video-reader-comparisonNote',
  context: 'video-reader-context',
  contextGrid: 'video-reader-contextGrid',
  controlRow: 'video-reader-controlRow',
  controls: 'video-reader-controls',
  copyStatus: 'video-reader-copyStatus',
  current: 'video-reader-current',
  dialog: 'video-reader-dialog',
  editorial: 'video-reader-editorial',
  errorNavigation: 'video-reader-errorNavigation',
  expand: 'video-reader-expand',
  footnote: 'video-reader-footnote',
  frame: 'video-reader-frame',
  heading: 'video-reader-heading',
  layout: 'video-reader-layout',
  links: 'video-reader-links',
  loading: 'video-reader-loading',
  meta: 'video-reader-meta',
  model: 'video-reader-model',
  navigationError: 'video-reader-navigationError',
  note: 'video-reader-note',
  player: 'video-reader-player',
  playerNavigation: 'video-reader-playerNavigation',
  playerStatus: 'video-reader-playerStatus',
  portrait: 'video-reader-portrait',
  price: 'video-reader-price',
  primary: 'video-reader-primary',
  prompt: 'video-reader-prompt',
  promptExpanded: 'video-reader-promptExpanded',
  promptHeading: 'video-reader-promptHeading',
  promptText: 'video-reader-promptText',
  quote: 'video-reader-quote',
  quotes: 'video-reader-quotes',
  recorded: 'video-reader-recorded',
  references: 'video-reader-references',
  scenario: 'video-reader-scenario',
  quoteIdentity: 'video-reader-quoteIdentity',
  quoteSettings: 'video-reader-quoteSettings',
  share: 'video-reader-share',
  shareFallback: 'video-reader-shareFallback',
  shareFeedback: 'video-reader-shareFeedback',
  shareRow: 'video-reader-shareRow',
  spacer: 'video-reader-spacer',
  standalone: 'video-reader-standalone',
} as const;

const readerCss = String.raw`
.video-reader-backdrop{position:fixed;inset:0;z-index:100;background:#101511b8;backdrop-filter:blur(6px);display:grid;place-items:center;padding:32px}
.video-reader-dialog{--ink:#f1f0e9;--muted:#b2b7ad;--canvas:#181a1a;--panel:#222524;--line:#3b3f3b;--gold:#e6bf76;position:relative;background:var(--canvas);color:var(--ink);color-scheme:dark;border:1px solid var(--line);border-radius:14px;padding:32px;width:min(1360px,100%);max-height:calc(100dvh - 64px);overflow:auto;overscroll-behavior:contain;box-shadow:0 30px 120px #0008}
.video-reader-dialog :is(button,a,input,select):focus-visible{outline:2px solid var(--gold);outline-offset:4px}
.video-reader-dialog button{cursor:pointer;font:inherit}.video-reader-dialog button:disabled{cursor:default;opacity:.4}.video-reader-dialog a{text-decoration:none}.video-reader-dialog button,.video-reader-dialog a{transition:background .15s,color .15s,border-color .15s}
.video-reader-close{position:absolute;top:7px;right:7px;z-index:4;display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:var(--canvas);color:var(--muted)}.video-reader-close:hover{background:var(--panel);color:var(--ink)}
.video-reader-layout{display:grid;grid-template-columns:minmax(0,1fr) 312px;gap:26px 30px;align-items:start}.video-reader-player{grid-area:1/1;position:relative;min-width:0}.video-reader-frame{position:relative;width:100%;aspect-ratio:var(--ratio);background:#101211;overflow:hidden;border-radius:8px;border:1px solid #ffffff28;isolation:isolate}.video-reader-frame video{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}.video-reader-centerPlay{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);display:grid;place-items:center;width:68px;height:68px;border:1px solid #fff6;border-radius:50%;background:#181a1a9c;backdrop-filter:blur(8px);color:#fff}.video-reader-centerPlay:hover{background:#181a1acc}
.video-reader-playerNavigation{position:absolute;inset:0;display:flex;align-items:center;justify-content:space-between;padding:12px;pointer-events:none}.video-reader-playerNavigation button{pointer-events:auto;width:40px;height:40px;display:grid;place-items:center;border:1px solid #ffffff38;border-radius:50%;background:#151916c9;backdrop-filter:blur(8px)}.video-reader-playerNavigation button:disabled{visibility:hidden}.video-reader-playerNavigation button:hover{background:var(--panel)}
.video-reader-controls{position:absolute;bottom:0;left:0;right:0;padding:7px 12px;background:#151916e8;display:grid;gap:2px}.video-reader-controls input{width:100%;height:12px;accent-color:var(--gold);cursor:pointer}.video-reader-controlRow{display:flex;align-items:center;gap:8px}.video-reader-controlRow button{display:grid;place-items:center;width:32px;min-height:32px;border-radius:5px}.video-reader-controlRow button:hover{background:var(--panel)}.video-reader-controlRow span{font-size:11px;font-variant-numeric:tabular-nums;white-space:nowrap}.video-reader-spacer{flex:1}.video-reader-controlRow select{font-size:11px;background:var(--canvas);border:1px solid var(--line);border-radius:5px;padding:4px;max-width:95px}.video-reader-playerStatus{position:absolute;top:35%;left:50%;transform:translate(-50%,-50%);background:#151916e8;padding:10px 14px;border-radius:8px;font-size:12px;text-align:center;pointer-events:none;max-width:90%}.video-reader-frame:fullscreen{height:100%;width:100%;aspect-ratio:auto;border:0;border-radius:0}
.video-reader-editorial{grid-area:1/2/3/3;min-width:0;padding-top:8px}.video-reader-model{display:inline-flex;align-items:center;gap:7px;color:var(--gold);font-size:13px;font-weight:550;margin-bottom:14px}.video-reader-heading :is(h1,h2){font-size:28px;font-weight:580;line-height:1.18;letter-spacing:-.04em;margin:0 0 12px;overflow-wrap:anywhere}.video-reader-meta{font-size:13px;line-height:1.6;color:var(--muted)}
.video-reader-action{margin-top:22px;padding-top:20px;border-top:1px solid var(--line)}.video-reader-recorded{display:flex;align-items:center;gap:10px;font-size:12px;color:var(--muted);margin-bottom:16px}.video-reader-recorded strong{font-size:17px;font-weight:600;color:var(--ink);font-variant-numeric:tabular-nums}.video-reader-primary{display:flex;align-items:center;justify-content:center;gap:10px;background:var(--gold);color:#231c12;border:1px solid var(--gold);min-height:48px;padding:10px 12px;border-radius:8px;font-size:14px;font-weight:600;line-height:1.4;text-align:center}.video-reader-primary svg{flex-shrink:0}.video-reader-primary:hover{background:#f3d394}.video-reader-note{font-size:12px;line-height:1.6;color:var(--muted);margin-top:9px}
.video-reader-prompt{padding-top:22px;margin-top:22px;border-top:1px solid var(--line)}.video-reader-promptHeading{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px;gap:8px}.video-reader-promptHeading h3,.video-reader-references h3{font-size:13px;font-weight:550}.video-reader-promptHeading button{display:flex;align-items:center;gap:6px;min-height:32px;font-size:12px;border-radius:5px;padding:0 5px}.video-reader-promptHeading button:hover{background:var(--panel)}.video-reader-promptText,.video-reader-promptExpanded{font-size:13px;line-height:1.75;color:var(--muted);white-space:pre-wrap;overflow-wrap:anywhere}.video-reader-promptText{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:5;overflow:hidden}.video-reader-promptExpanded{max-height:360px;overflow:auto}.video-reader-expand{padding:9px 0;display:flex;align-items:center;gap:8px;color:var(--gold);font-size:12px!important}.video-reader-copyStatus{font-size:11px;color:var(--gold)}.video-reader-copyStatus:empty{display:none}.video-reader-links{border-top:1px solid var(--line);margin-top:20px;padding-top:12px}.video-reader-links a{display:flex;align-items:center;gap:9px;color:var(--muted);font-size:12px;padding:10px 0;border-radius:4px}.video-reader-links a:hover{color:var(--ink)}.video-reader-references{margin-top:20px}.video-reader-references>div{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}.video-reader-references img{width:70px;height:70px;object-fit:cover;border-radius:6px}
.video-reader-comparison{grid-area:2/1;min-width:0}.video-reader-comparison>h3{font-size:22px;line-height:1.3;letter-spacing:-.025em;margin:0 0 9px;font-weight:560}.video-reader-scenario{display:flex;flex-wrap:wrap;gap:5px 13px;font-size:12px;margin-bottom:6px}.video-reader-scenario strong{font-weight:500}.video-reader-comparisonNote{color:var(--muted);font-size:12px;line-height:1.55;margin:8px 0 18px}.video-reader-quotes{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));row-gap:20px}.video-reader-quote{padding:2px 14px;border-left:1px solid var(--line);display:flex;flex-direction:column;align-items:start;gap:9px}.video-reader-quote:first-child{border-left:0;padding-left:0}.video-reader-quote:last-child{padding-right:0}.video-reader-quote>div{min-height:36px}.video-reader-quoteIdentity{display:flex;align-items:center;gap:9px;min-height:32px}.video-reader-quoteIdentity h4{min-width:0;line-height:1.4}.video-reader-quote h4{font-size:14px;font-weight:550}.video-reader-current{font-size:10px;color:var(--muted);margin-top:2px}.video-reader-quoteSettings{display:flex;flex-wrap:wrap;gap:4px 8px;font-size:11px;line-height:1.6;color:var(--muted);margin-top:8px}.video-reader-quoteSettings [data-adjusted]{color:var(--gold)}.video-reader-price{font-size:23px;letter-spacing:-.04em;font-weight:550;line-height:1.15;font-variant-numeric:tabular-nums}.video-reader-quote a{display:flex;align-items:center;gap:6px;color:var(--gold);font-size:12px;min-height:32px;margin-top:auto}.video-reader-quote a:hover{text-decoration:underline}.video-reader-footnote{font-size:11px;line-height:1.6;color:var(--muted);margin-top:16px}
.video-reader-portrait{grid-template-columns:minmax(210px,1fr) auto minmax(230px,1fr);grid-template-rows:auto 1fr}.video-reader-portrait .video-reader-player{grid-area:1/2/3/3;align-self:start}.video-reader-portrait .video-reader-frame{height:min(740px,calc(100dvh - 132px));width:auto;aspect-ratio:var(--ratio)}.video-reader-portrait .video-reader-editorial{grid-area:1/1/3/2;padding-top:16px}.video-reader-portrait .video-reader-heading :is(h1,h2){font-size:32px}.video-reader-portrait>.video-reader-action{grid-area:1/3;margin-top:16px;border:0;padding:0}.video-reader-portrait .video-reader-recorded{display:block}.video-reader-portrait .video-reader-recorded strong{display:block;font-size:34px;letter-spacing:-.04em;margin-top:6px}.video-reader-portrait .video-reader-comparison{grid-area:2/3;padding-top:22px;border-top:1px solid var(--line)}.video-reader-portrait .video-reader-comparison>h3{font-size:21px}.video-reader-portrait .video-reader-quotes{display:flex;flex-direction:column;gap:0}.video-reader-portrait .video-reader-quote{display:grid;grid-template-columns:1fr auto;gap:7px 8px;border:0;border-top:1px solid var(--line);padding:14px 0}.video-reader-portrait .video-reader-price{font-size:20px;grid-area:2/1}.video-reader-portrait .video-reader-quote a{grid-area:1/2/3/3;align-self:center;max-width:110px;margin:0}
.video-reader-loading{min-height:360px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:20px;font-size:14px;color:var(--muted)}.video-reader-loading button{padding:10px 16px;border:1px solid var(--line);border-radius:8px;color:var(--ink)}.video-reader-errorNavigation{display:flex;gap:12px}.video-reader-errorNavigation button{display:flex;align-items:center;gap:8px}.video-reader-navigationError{margin:20px 0 0;color:var(--gold);font-size:12px}
.video-reader-share{min-width:0}.video-reader-shareRow{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:44px}.video-reader-shareRow>span{color:var(--muted);font-size:12px;line-height:1.5}.video-reader-shareRow button{display:inline-flex;align-items:center;justify-content:center;gap:7px;flex-shrink:0;min-width:118px;min-height:40px;padding:8px 11px;border:1px solid var(--line);border-radius:7px;background:var(--panel);color:var(--ink);font-size:12px;font-weight:550;white-space:nowrap}.video-reader-shareRow button svg{flex-shrink:0}.video-reader-shareRow button:hover{border-color:var(--gold);background:#2b2c27}.video-reader-shareRow button[data-copied]{color:var(--gold);border-color:#e6bf7666}.video-reader-shareFeedback{color:var(--gold);font-size:12px;line-height:1.6;margin:8px 0}.video-reader-shareFallback{display:block;width:100%;min-width:0;min-height:40px;background:var(--panel);border:1px solid var(--line);border-radius:7px;color:var(--ink);font-size:12px;padding:8px 10px}
@media(max-width:1099px) and (min-width:761px){.video-reader-backdrop{padding:16px}.video-reader-dialog{padding:24px;max-height:calc(100dvh - 32px)}.video-reader-layout{grid-template-columns:minmax(0,1fr) 270px;gap:24px}.video-reader-heading :is(h1,h2){font-size:23px}.video-reader-portrait{grid-template-columns:auto minmax(240px,1fr)}.video-reader-portrait .video-reader-player{grid-area:1/1/4/2}.video-reader-portrait .video-reader-frame{height:min(670px,calc(100dvh - 98px));max-width:40vw}.video-reader-portrait .video-reader-editorial{grid-area:1/2}.video-reader-portrait>.video-reader-action{grid-area:2/2;margin:0}.video-reader-portrait .video-reader-comparison{grid-area:3/2}.video-reader-portrait .video-reader-recorded{display:flex}.video-reader-portrait .video-reader-recorded strong{font-size:20px;margin:0}.video-reader-quotes{grid-template-columns:1fr}.video-reader-quote{display:grid;grid-template-columns:1fr auto;border-left:0;border-top:1px solid var(--line);padding:12px 0;gap:6px}.video-reader-price{grid-area:2/1;font-size:21px}.video-reader-quote a{grid-area:1/2/3/3}}
@media(max-width:760px){.video-reader-backdrop{padding:0}.video-reader-dialog{padding:0 0 max(22px,env(safe-area-inset-bottom));border-radius:0;border:0;width:100%;height:100dvh;max-height:100dvh}.video-reader-close{position:fixed;right:8px;top:max(8px,env(safe-area-inset-top));width:36px;height:36px}.video-reader-layout,.video-reader-portrait{display:flex;flex-direction:column;gap:0}.video-reader-player,.video-reader-portrait .video-reader-player{order:0;align-self:center;width:100%;padding-top:52px;background:#101211}.video-reader-frame{border:0;border-radius:0}.video-reader-portrait .video-reader-frame{width:auto;height:min(64dvh,660px);margin:auto;max-width:100%}.video-reader-editorial,.video-reader-portrait .video-reader-editorial{display:contents}.video-reader-heading{order:1;padding:22px 20px 0;width:100%}.video-reader-heading :is(h1,h2),.video-reader-portrait .video-reader-heading :is(h1,h2){font-size:25px}.video-reader-model{margin-bottom:9px;font-size:12px}.video-reader-action,.video-reader-portrait>.video-reader-action{order:2;width:calc(100% - 40px);margin:16px 20px 0;padding:16px 0 0;border-top:1px solid var(--line)}.video-reader-recorded,.video-reader-portrait .video-reader-recorded{display:flex;font-size:12px}.video-reader-portrait .video-reader-recorded strong{font-size:17px;margin:0}.video-reader-primary{min-height:50px}.video-reader-comparison,.video-reader-portrait .video-reader-comparison{order:7;width:calc(100% - 40px);margin:24px 20px 0;padding-top:22px;border-top:1px solid var(--line)}.video-reader-comparison>h3,.video-reader-portrait .video-reader-comparison>h3{font-size:21px}.video-reader-quotes{display:flex;flex-direction:column;gap:0}.video-reader-quote,.video-reader-portrait .video-reader-quote{display:grid;grid-template-columns:1fr auto;gap:7px 10px;border:0;border-top:1px solid var(--line);padding:16px 0}.video-reader-price,.video-reader-portrait .video-reader-price{grid-area:2/1;font-size:22px}.video-reader-quote a,.video-reader-portrait .video-reader-quote a{grid-area:1/2/3/3;min-height:44px;align-self:center;max-width:135px;margin:0}.video-reader-prompt{order:4;width:calc(100% - 40px);margin:24px 20px 0;padding-top:20px}.video-reader-references{order:5;margin:20px}.video-reader-links{order:6;width:calc(100% - 40px);margin:20px 20px 0}.video-reader-expand{min-height:44px}.video-reader-promptHeading button{min-height:44px}.video-reader-loading{min-height:70dvh;padding:40px 20px}.video-reader-errorNavigation{flex-direction:column}.video-reader-navigationError{padding:0 20px}.video-reader-controlRow button{min-height:36px}}
@media(prefers-reduced-motion:reduce){.video-reader-dialog *{transition:none!important}}

.video-reader-standalone{width:100%;max-height:none;overflow:visible;box-shadow:none}.video-reader-standalone .video-reader-player{padding-top:0}
.video-reader-context{margin-top:28px;padding-top:20px;border-top:1px solid var(--line);color:var(--muted);font-size:13px;line-height:1.75}.video-reader-context>p{max-width:85ch}.video-reader-context details{margin-top:14px}.video-reader-context summary{color:var(--ink);font-weight:550;cursor:pointer;padding:8px 0}.video-reader-contextGrid{display:grid;grid-template-columns:1fr 1fr;gap:32px;padding:8px 0}.video-reader-context h3{color:var(--ink);font-size:14px;font-weight:550;margin:18px 0 8px}.video-reader-context ul{list-style:disc;padding-left:18px}.video-reader-context li{margin:6px 0}.video-reader-context a{color:var(--gold)}.video-reader-context a:hover{text-decoration:underline}.video-reader-context dl>div{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid var(--line);padding:7px 0}.video-reader-context dd{text-align:right}
@media(max-width:760px){.video-reader-standalone{height:auto;max-height:none;border-radius:0}.video-reader-context{margin:24px 20px 0}.video-reader-contextGrid{grid-template-columns:1fr;gap:0}}
`;

export function ExampleReaderStyles() {
  // Authored static CSS only; preserve combinators in both React SSR runtimes.
  return <style data-video-reader-styles dangerouslySetInnerHTML={{ __html: readerCss }} />;
}

export default styles;
