export const DEFAULT_BACKGROUND_REMOVAL_COPY = {
  disabledTitle: 'Tools are disabled',
  disabledBody: 'Enable `FEATURES.workflows.toolsSection` to access this area.',
  back: 'Back to tools',
  eyebrow: 'Video cleanup',
  title: 'Video Background Remover',
  subtitle: 'Remove backgrounds from short videos, export transparent WebM or solid-color clips, and reuse results from your media library.',
  sourceTitle: 'Source video',
  sourceBody: 'Upload a short clip, paste an HTTPS video URL, or reuse a saved library video.',
  upload: 'Upload video',
  urlLabel: 'Video URL',
  urlPlaceholder: 'https://example.com/source.mp4',
  library: 'Library',
  libraryAll: 'All videos',
  libraryUploaded: 'Uploaded',
  libraryGenerated: 'Generated',
  libraryBackgroundRemoval: 'Background removal',
  metadataLoading: 'Reading video metadata...',
  metadataRequired: 'Add a readable video source to estimate price.',
  durationTooLong: 'This tool supports clips up to 60 seconds.',
  settingsTitle: 'Video settings',
  backgroundColor: 'Background',
  outputCodec: 'Output',
  outputCodecHint: 'Use MOV ProRes for Premiere/Finder. Use WebM VP9 only for transparent web playback.',
  preserveAudio: 'Preserve audio',
  priceLoading: 'Loading price...',
  priceUnavailable: 'Price unavailable',
  priceReady: 'Estimated for this clip',
  run: 'Remove Background',
  running: 'Processing...',
  previewTitle: 'Preview',
  sourcePreview: 'Source',
  resultPreview: 'Result',
  compareSource: 'Show source',
  compareResult: 'Show result',
  noPreview: 'Add a video to preview the source.',
  checkerboard: 'Transparent output preview',
  save: 'Save',
  saved: 'Saved to library.',
  saveFailed: 'Could not save this result.',
  download: 'Download',
  copyLink: 'Copy link',
  copied: 'Link copied.',
  recentTitle: 'Recent background removals',
  recentEmpty: 'Finished results will appear here.',
  recentFailed: 'Failed',
  authTitle: 'Sign in to use the tool',
  authBody: 'Background removal uses wallet billing and private library storage.',
} as const;

export type BackgroundRemovalWorkspaceCopy = typeof DEFAULT_BACKGROUND_REMOVAL_COPY;
