import type {ImageDraft} from '@/lib/studio/image-conversation-contract';
import type {StudioGenerationActor} from '@/server/agent-api/generation-actor';
import {AgentApiError} from '@/server/agent-api/errors';
import type {StudioTaskExecution} from './execution';
import {StudioTaskStop} from './policy';
import {readStudioTaskRow,readStudioTaskUsage} from './repository';
export async function studioTaskStopDraft(actor:StudioGenerationActor,execution:StudioTaskExecution,error:unknown):Promise<ImageDraft> {
  const reason=error instanceof StudioTaskStop?error.reason:error instanceof AgentApiError&&error.code==='ACCOUNT_RESTRICTED'?'permission':'funding';
  const usage=await readStudioTaskUsage(await readStudioTaskRow(actor,execution.taskRequestId));
  const explanations={budget:'The next call would exceed this task credit ceiling.',steps:'This task reached its current step allowance.',output:'This task reached its output allowance.',deadline:'This task reached its time allowance.',context:'The current context needs a smaller selection or a more focused request.',funding:'Available assistance credits need attention; purchased usage remains paused unless you enable it.',provider:'Previous provider usage needs recovery before another call.',usage:'Previous provider usage remains unresolved.',permission:'A source, project or account permission needs attention.',unavailable:'New task dispatch is currently unavailable.'};
  const fr={budget:'Le prochain appel dépasserait le plafond de crédits de cette demande.',steps:'Cette demande a atteint son nombre d’étapes actuel.',output:'Cette demande a atteint sa limite de réponse.',deadline:'Cette demande a atteint sa durée autorisée.',context:'Le contexte nécessite une sélection plus courte ou une demande plus ciblée.',funding:'Les crédits disponibles nécessitent votre attention ; les crédits achetés restent suspendus tant que vous ne les réactivez pas.',provider:'Une réponse précédente doit être récupérée avant un nouvel appel.',usage:'Le coût d’un appel précédent reste à vérifier.',permission:'Un média, le projet ou les droits du compte nécessitent votre attention.',unavailable:'Les nouveaux appels sont temporairement indisponibles.'};
  const es={budget:'La siguiente llamada superaría el límite de créditos de esta solicitud.',steps:'La solicitud alcanzó su límite actual de pasos.',output:'La solicitud alcanzó su límite de respuesta.',deadline:'La solicitud alcanzó su tiempo permitido.',context:'El contexto necesita una selección menor o una solicitud más concreta.',funding:'Revisa los créditos disponibles; los créditos comprados siguen suspendidos hasta que los reactives.',provider:'Es necesario recuperar una respuesta anterior.',usage:'El coste de una llamada anterior sigue pendiente.',permission:'Revisa el medio, proyecto o permisos de la cuenta.',unavailable:'Las nuevas llamadas no están disponibles temporalmente.'};
  const reply=execution.locale==='fr'?`${usage.completedCalls} étapes sont enregistrées ; ${usage.consumedCredits} crédits d’assistance ont été consommés. ${fr[reason]} Le travail déjà enregistré est conservé. Continuez à partir du projet actuel ou simplifiez la demande ; la demande complète n’est pas encore terminée.`
    :execution.locale==='es'?`${usage.completedCalls} pasos registrados; ${usage.consumedCredits} créditos consumidos. ${es[reason]} El trabajo guardado se conserva. Continúa desde el proyecto actual o simplifica la solicitud; todavía no está terminada.`
    :`${usage.completedCalls} model steps are recorded; ${usage.consumedCredits} assistance credits were consumed. ${explanations[reason]} Some work may already be saved. Continue from the current project or simplify the request; the full request is not yet verified as finished.`;
  return {reply,image:null,
    continuation:{reason:reason==='output'?'output_limit':'action_limit',completedEdits:0,lastError:{code:'TASK_'+reason.toUpperCase(),message:explanations[reason]}}};
}
