import React from '../../../frontend/node_modules/react';
import {renderToStaticMarkup} from '../../../frontend/node_modules/react-dom/server';
import {randomBytes,randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import path from 'node:path';
import {EditorialArticle} from '../../../frontend/app/(core)/admin/editorial/_components/EditorialArticle';
import type {EditorialVersion} from '../../../frontend/src/server/editorial/repository';
const css=readFileSync(path.resolve('frontend/components/editorial/editorial-article.css'),'utf8');
const shellCss=`*{box-sizing:border-box}body{margin:0;background:#e7ebdf;color:#253025;font:16px/1.5 Arial,sans-serif}a{color:inherit}.review-bar,.review-form,.review-empty{max-width:1000px;margin:0 auto;padding:24px;background:#fffdf7}.review-bar nav{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.review-bar a,button{border:1px solid #48623b;border-radius:24px;padding:12px 18px;display:inline-block;text-decoration:none;font:inherit}.review-bar a[aria-current=page],button{background:#263e29;color:white}button{cursor:pointer;min-height:48px}button:disabled{opacity:.6}.review-bar p{margin:8px 0}.review-form{border-top:1px solid #cbd5bf}.review-form label{display:block;font-weight:bold;margin:16px 0 8px}.review-form select,.review-form textarea{width:100%;font:inherit;padding:12px;border:1px solid #9da995;border-radius:10px;background:white}.review-form textarea{min-height:130px}.review-form button{margin-top:16px}.review-history{padding:18px;background:#e9eddf;border-radius:12px;margin:12px 0;overflow-wrap:anywhere}.review-empty{margin:8vh auto;max-width:600px}details{overflow-wrap:anywhere}`;
const script=`const token=location.hash.startsWith('#token=')?location.hash.slice(7):null;if(token){history.replaceState(null,'',location.pathname+location.search);fetch('/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}).then(async r=>{if(r.ok)location.reload();else document.getElementById('access-message').textContent='Ce lien est expiré ou révoqué. Demande un nouvel accès.'}).catch(()=>document.getElementById('access-message').textContent='Connexion interrompue. Rouvre ton lien WhatsApp.');}const f=document.getElementById('correction-form');if(f)f.addEventListener('submit',async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;const data=Object.fromEntries(new FormData(f));data.version=Number(data.version);if(!data.blockId)delete data.blockId;try{const r=await fetch('/corrections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});document.getElementById('correction-status').textContent=r.ok?'Demande enregistrée. Cette version reste en brouillon ; la retouche attend son traitement.':r.status===409?'Cette version a été remplacée. Utilise le dernier lien reçu.':'Demande non enregistrée. Vérifie ta connexion et réessaie.';b.disabled=r.ok;}catch{document.getElementById('correction-status').textContent='Connexion interrompue. Tu peux réessayer sans créer de doublon.';b.disabled=false;}});document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#source-"]');if(a)document.querySelector('.ed-sources').open=true;});`;
export function reviewPage(record?:EditorialVersion,locale:'en'|'fr'|'es'='en',corrections:Array<{detail:{message:string;locale:string;blockId?:string}}> = []) {
 const nonce=randomBytes(18).toString('base64url');
 const body=record?<><header className="review-bar"><strong>MaxVideoAI · Atelier éditorial</strong><p>Brouillon privé · Version {record.version} · Aucune publication</p><nav aria-label="Langue">{(['en','fr','es'] as const).map(l=><a key={l} href={`/?locale=${l}`} aria-current={l===locale?'page':undefined}>{l==='es'?'Español LATAM':l==='fr'?'Français':'English master'}</a>)}<a href="#correction-form">Demander une retouche</a></nav><details><summary>Contrôles et version</summary><p>Les contrôles de publication du site restent à finaliser. Ce lien autorise la lecture et les demandes de correction.</p><small>{record.digest}</small></details></header>
 <EditorialArticle draft={record.draft} locale={locale} articleId={record.articleId} version={record.version} mediaUrl={id=>`/media/${id}`} />
 <section className="review-form"><h2>Ce qu’on améliore</h2><p>Précise le passage et le résultat souhaité. Ta demande reste liée à cette version.</p>{corrections.map((c,i)=><div className="review-history" key={i}><strong>{c.detail.locale.toUpperCase()} · {c.detail.blockId??'Article entier'}</strong><p>{c.detail.message}</p></div>)}<form id="correction-form">
 <input type="hidden" name="articleId" value={record.articleId}/><input type="hidden" name="version" value={record.version}/><input type="hidden" name="digest" value={record.digest}/><input type="hidden" name="requestId" value={randomUUID()}/><input type="hidden" name="locale" value={locale}/>
 <label htmlFor="blockId">Passage concerné</label><select name="blockId" id="blockId"><option value="">L’article entier</option>{record.draft.locales[locale].blocks.map(b=><option value={b.id} key={b.id}>{b.heading??b.id}</option>)}</select>
 <label htmlFor="message">Ta demande</label><textarea name="message" id="message" minLength={8} maxLength={3000} required placeholder="Par exemple : rendre cette introduction plus directe…"/><button type="submit">Enregistrer ma demande</button><p id="correction-status" role="status" aria-live="polite"/></form></section></>:<main className="review-empty"><h1>MaxVideoAI · Lecture privée</h1><p id="access-message">Ouvre le lien privé reçu sur WhatsApp pour lire ton brouillon.</p></main>;
 const html='<!doctype html>'+renderToStaticMarkup(<html lang="fr"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="robots" content="noindex,nofollow,noarchive"/><title>MaxVideoAI · Brouillon privé</title><style nonce={nonce}>{css+shellCss}</style></head><body>{body}<script nonce={nonce} dangerouslySetInnerHTML={{__html:script}}/></body></html>);
 return {html,nonce};
}
