const en = {
  library: 'Library', close: 'Close', select: 'Select', emptyLibrary: 'No saved audio.', import: 'Import',
  quality: 'Quality', highQuality: 'High quality', soon: 'Coming soon', qualityPending: 'This offer is being qualified. Pricing will be announced before it opens.',
  title: 'Audio', subtitle: 'Give your idea a sound.',
  intents: { voice: ['Voice over', 'A voice for your words'], music: ['Instrumental', 'Music without vocals'], song: ['Song', 'Lyrics, sung to music'], sfx: ['Sound effects', 'An impact. A gesture. A detail.'], ambience: ['Ambiences', 'A place you can hear'] },
  video: 'Soundtrack a video', back: 'Create audio', script: 'Your script', prompt: 'Describe the sound', style: 'Musical direction', lyrics: 'Lyrics',
  scriptHint: 'Write exactly what the voice should say.', promptHint: 'The sound, its texture, and how it develops.', styleHint: 'Genre, instruments, mood, vocal style. At least 10 characters.', lyricsHint: 'Keep your verses and chorus on separate lines.',
  examples: 'Try an idea', examplesByIntent: { voice: ['Welcome to a new way of creating. Every idea starts with a first step.'], music: ['Warm analog synths, a soft pulsing bass, cinematic build, no vocals.'], song: ['Intimate acoustic folk, gentle guitar, warm female singing, slow tempo.'], sfx: ['A heavy metal door slams shut, followed by a short echo in a stone hallway.', 'A quick airy whoosh followed by a crisp digital click.'], ambience: ['Steady rain on leaves in a quiet forest, distant wind, continuous natural background.'] },
  model: 'Model', voice: 'Voice', language: 'Language', duration: 'Duration', tempo: 'Tempo', options: 'Voice settings', speed: 'Speed', volume: 'Volume', pitch: 'Pitch', reference: 'Voice reference', addReference: 'Add audio reference', remove: 'Remove', referenceHint: 'MP3 or WAV · up to 30s / 10MB',
  auto: 'Automatic', fullSong: 'Full song · duration follows the lyrics', ambienceHint: 'Continuous background. A seamless loop is not guaranteed.', seedHint: 'Preset voices and an audio reference.', minimaxHint: 'Speech from your script. Billed by character.',
  generate: 'Generate', quoteLoading: 'Updating price…', quoteIdle: 'Complete your idea to see the price', quoteError: 'Price unavailable', retry: 'Retry', currentPrice: 'Current price', signIn: 'Sign in to generate', saved: 'Draft saved on this device', unsaved: 'Draft stays in this session',
  listen: 'Listen', empty: 'Your next sound starts here', emptyHint: 'Generate, listen, then bring it into your project.', generating: 'Creating your audio…', generatingHint: 'You can keep writing while it runs.', failed: 'Audio creation failed', download: 'Download original', reuse: 'Reuse settings', history: 'Recent creations', details: 'Details', measured: 'Measured duration', requested: 'Requested duration', output: 'Original audio', preview: 'Preview voice', stop: 'Stop', loading: 'Loading…', error: 'Something went wrong. Try again.', uploadError: 'Use an MP3 or WAV file of at most 30 seconds and 10MB.', loadingHistory: 'Loading your creations…', emptyHistory: 'Your audio creations will appear here.',
};
type Copy = typeof en;
const fr: Copy = { ...en,
  library: 'Bibliothèque', close: 'Fermer', select: 'Sélectionner', emptyLibrary: 'Aucun audio enregistré.', import: 'Importer',
  quality: 'Qualité', highQuality: 'Haute qualité', soon: 'À venir', qualityPending: 'Cette offre est en qualification. Le tarif sera annoncé avant son ouverture.',
  title: 'Audio', subtitle: 'Donnez un son à votre idée.',
  intents: { voice: ['Voix off', 'Une voix pour vos mots'], music: ['Instrumentale', 'La musique sans chant'], song: ['Musique chantée', 'Vos paroles en musique'], sfx: ['Effets sonores', 'Un impact. Un geste. Un détail.'], ambience: ['Ambiances', 'Un lieu qui s’entend'] },
  video: 'Sonoriser une vidéo', back: 'Créer un son', script: 'Votre script', prompt: 'Décrivez le son', style: 'Direction musicale', lyrics: 'Paroles', scriptHint: 'Écrivez exactement ce que la voix doit dire.', promptHint: 'Le son, sa matière et son évolution.', styleHint: 'Genre, instruments, atmosphère, style vocal. 10 caractères minimum.', lyricsHint: 'Séparez les couplets et le refrain par des retours à la ligne.',
  examples: 'Essayer une idée', examplesByIntent: { voice: ['Bienvenue dans une nouvelle façon de créer. Chaque idée commence par un premier pas.'], music: ['Synthétiseurs analogiques chaleureux, basse douce et pulsée, progression cinématographique, sans chant.'], song: ['Folk acoustique intimiste, guitare délicate, chant féminin chaleureux, tempo lent.'], sfx: ['Une lourde porte métallique claque, suivie d’un bref écho dans un couloir de pierre.', 'Un souffle rapide suivi d’un clic numérique net.'], ambience: ['Pluie régulière sur les feuilles d’une forêt calme, vent lointain, fond naturel continu.'] },
  model: 'Modèle', voice: 'Voix', language: 'Langue', duration: 'Durée', tempo: 'Tempo', options: 'Réglages de voix', speed: 'Vitesse', volume: 'Volume', pitch: 'Hauteur', reference: 'Référence vocale', addReference: 'Ajouter une référence audio', remove: 'Retirer', referenceHint: 'MP3 ou WAV · 30 s / 10 Mo maximum', auto: 'Automatique', fullSong: 'Morceau complet · la durée suit les paroles', ambienceHint: 'Fond continu. Une boucle parfaite n’est pas garantie.', seedHint: 'Voix prédéfinies et référence audio.', minimaxHint: 'Lecture de votre script. Tarif par caractère.', generate: 'Générer', quoteLoading: 'Actualisation du prix…', quoteIdle: 'Complétez votre idée pour voir le prix', quoteError: 'Prix indisponible', retry: 'Réessayer', currentPrice: 'Prix actuel', signIn: 'Se connecter pour générer', saved: 'Brouillon enregistré sur cet appareil', unsaved: 'Brouillon conservé dans cette session', listen: 'Écouter', empty: 'Votre prochain son commence ici', emptyHint: 'Créez, écoutez, puis ajoutez-le à votre projet.', generating: 'Création de votre audio…', generatingHint: 'Vous pouvez continuer à écrire.', failed: 'La création audio a échoué', download: 'Télécharger l’original', reuse: 'Réutiliser les réglages', history: 'Créations récentes', details: 'Détails', measured: 'Durée mesurée', requested: 'Durée demandée', output: 'Audio original', preview: 'Écouter la voix', stop: 'Arrêter', loading: 'Chargement…', error: 'Une erreur est survenue. Réessayez.', uploadError: 'Choisissez un MP3 ou WAV de 30 secondes et 10 Mo maximum.', loadingHistory: 'Chargement des créations…', emptyHistory: 'Vos créations audio apparaîtront ici.',
};
const es: Copy = { ...en,
  library: 'Biblioteca', close: 'Cerrar', select: 'Seleccionar', emptyLibrary: 'No hay audio guardado.', import: 'Importar',
  quality: 'Calidad', highQuality: 'Alta calidad', soon: 'Próximamente', qualityPending: 'Esta oferta está en evaluación. El precio se anunciará antes de abrirla.',
  title: 'Audio', subtitle: 'Dale sonido a tu idea.', intents: { voice: ['Voz en off', 'Una voz para tus palabras'], music: ['Instrumental', 'Música sin voces'], song: ['Canción', 'Tu letra hecha música'], sfx: ['Efectos sonoros', 'Un impacto. Un gesto. Un detalle.'], ambience: ['Ambientes', 'Un lugar que se escucha'] },
  video: 'Sonorizar un vídeo', back: 'Crear audio', script: 'Tu guion', prompt: 'Describe el sonido', style: 'Dirección musical', lyrics: 'Letra', scriptHint: 'Escribe exactamente lo que dirá la voz.', promptHint: 'El sonido, su textura y cómo evoluciona.', styleHint: 'Género, instrumentos, ambiente, estilo vocal. Al menos 10 caracteres.', lyricsHint: 'Separa las estrofas y el estribillo con saltos de línea.',
  examples: 'Probar una idea', examplesByIntent: { voice: ['Bienvenido a una nueva forma de crear. Cada idea comienza con un primer paso.'], music: ['Sintetizadores analógicos cálidos, bajo suave y pulsante, progresión cinematográfica, sin voces.'], song: ['Folk acústico íntimo, guitarra suave, voz femenina cálida, tempo lento.'], sfx: ['Una pesada puerta metálica se cierra de golpe, con un breve eco en un pasillo de piedra.', 'Un soplido rápido seguido de un clic digital nítido.'], ambience: ['Lluvia constante sobre las hojas de un bosque tranquilo, viento lejano, fondo natural continuo.'] },
  model: 'Modelo', voice: 'Voz', language: 'Idioma', duration: 'Duración', tempo: 'Tempo', options: 'Ajustes de voz', speed: 'Velocidad', volume: 'Volumen', pitch: 'Tono', reference: 'Referencia vocal', addReference: 'Añadir referencia de audio', remove: 'Quitar', referenceHint: 'MP3 o WAV · hasta 30 s / 10 MB', auto: 'Automático', fullSong: 'Canción completa · la duración sigue la letra', ambienceHint: 'Fondo continuo. No se garantiza un bucle perfecto.', seedHint: 'Voces predefinidas y referencia de audio.', minimaxHint: 'Lectura de tu guion. Precio por carácter.', generate: 'Generar', quoteLoading: 'Actualizando precio…', quoteIdle: 'Completa tu idea para ver el precio', quoteError: 'Precio no disponible', retry: 'Reintentar', currentPrice: 'Precio actual', signIn: 'Inicia sesión para generar', saved: 'Borrador guardado en este dispositivo', unsaved: 'Borrador conservado en esta sesión', listen: 'Escuchar', empty: 'Tu próximo sonido empieza aquí', emptyHint: 'Crea, escucha y añádelo a tu proyecto.', generating: 'Creando tu audio…', generatingHint: 'Puedes seguir escribiendo.', failed: 'La creación de audio ha fallado', download: 'Descargar original', reuse: 'Reutilizar ajustes', history: 'Creaciones recientes', details: 'Detalles', measured: 'Duración medida', requested: 'Duración solicitada', output: 'Audio original', preview: 'Escuchar voz', stop: 'Detener', loading: 'Cargando…', error: 'Ha ocurrido un error. Inténtalo de nuevo.', uploadError: 'Elige un MP3 o WAV de hasta 30 segundos y 10 MB.', loadingHistory: 'Cargando tus creaciones…', emptyHistory: 'Tus creaciones de audio aparecerán aquí.',
};
export type AudioCreationCopy = Copy;
export const audioCreationCopy = (locale: string): Copy => locale.startsWith('fr') ? fr : locale.startsWith('es') ? es : en;
