import type { WorkspaceGraphEdge, WorkspaceGraphNode, WorkspaceTemplate, WorkspaceTimelineItem } from '../workspace-types';
import { WORKSPACE_DEMO_AUDIO_URL } from '../workspace-library-assets';
import {
  generatedCopyReference,
  generatedTextReference,
  localizeWorkspaceTemplateGeneratedState,
} from '../workspace-generated-copy';
import { createWorkspaceEdge, shotSettings } from './template-core';
import type { WorkspaceTemplateBuildCopy } from './registry';

const PRODUCT_AD_SHOT_01_DURATION_SEC = 5;
const PRODUCT_AD_SHOT_02_DURATION_SEC = 8;

function productAdTimeline(): WorkspaceTimelineItem[] {
  return [
    {
      id: 'timeline-output-01',
      outputNodeId: 'output-01',
      track: 'video',
      title: 'Shot 01 - Hero Reveal',
      generatedCopy: {
        title: generatedTextReference('Shot 01 - Hero Reveal'),
      },
      durationSec: PRODUCT_AD_SHOT_01_DURATION_SEC,
      startSec: 0,
      sourceStartSec: 0,
      sourceDurationSec: PRODUCT_AD_SHOT_01_DURATION_SEC,
      linkedGroupId: 'timeline-output-01',
      mediaKind: 'video',
      mediaUrl: '/hero/pika-22.mp4',
      thumbnailUrl: '/hero/showcase-kling-3-pro.webp',
      modelId: 'kling-3-pro',
      status: 'completed',
    },
    {
      id: 'timeline-output-02',
      outputNodeId: 'output-02',
      track: 'video',
      title: 'Shot 02 - Macro Details',
      generatedCopy: {
        title: generatedTextReference('Shot 02 - Macro Details'),
      },
      durationSec: PRODUCT_AD_SHOT_02_DURATION_SEC,
      startSec: PRODUCT_AD_SHOT_01_DURATION_SEC,
      sourceStartSec: 0,
      sourceDurationSec: PRODUCT_AD_SHOT_02_DURATION_SEC,
      linkedGroupId: 'timeline-output-02',
      mediaKind: 'video',
      hasEmbeddedAudio: true,
      mediaUrl: '/hero/veo3.mp4',
      thumbnailUrl: '/hero/showcase-veo-3-1.webp',
      modelId: 'veo-3-1',
      status: 'completed',
    },
    {
      id: 'timeline-output-02-audio',
      outputNodeId: 'output-02',
      track: 'audio',
      title: 'Shot 02 - Macro Details Audio',
      generatedCopy: {
        title: generatedTextReference('Shot 02 - Macro Details Audio'),
      },
      durationSec: PRODUCT_AD_SHOT_02_DURATION_SEC,
      startSec: PRODUCT_AD_SHOT_01_DURATION_SEC,
      sourceStartSec: 0,
      sourceDurationSec: PRODUCT_AD_SHOT_02_DURATION_SEC,
      linkedGroupId: 'timeline-output-02',
      mediaKind: 'audio',
      mediaUrl: '/hero/veo3.mp4',
      modelId: 'veo-3-1',
      status: 'completed',
    },
    {
      id: 'timeline-music-01',
      outputNodeId: 'audio-music-01',
      track: 'audio-2',
      title: 'ambient_moody.mp3',
      durationSec: 28,
      startSec: 0,
      sourceStartSec: 0,
      sourceDurationSec: 28,
      mediaKind: 'audio',
      status: 'ready',
    },
  ];
}

export function createProductAdWorkspaceTemplate(copy?: WorkspaceTemplateBuildCopy): WorkspaceTemplate {
  const nodes: WorkspaceGraphNode[] = [
    {
      id: 'asset-product-image',
      type: 'asset-image',
      position: { x: -330, y: -220 },
      data: {
        kind: 'asset-image',
        title: 'Product Image',
        subtitle: 'chrono_watch.png',
        accent: '#8b5cf6',
        generatedCopy: {
          title: generatedCopyReference('templateProductImage'),
        },
        asset: {
          id: 'product-image',
          kind: 'image',
          filename: 'chrono_watch.png',
          subtitle: 'Image · 2048x2048',
          url: '/storyboard/examples/storyboarder-product-reference.jpg',
          thumbUrl: '/storyboard/examples/storyboarder-product-reference.jpg',
          dimensions: '2048x2048',
        },
        sourceHandles: ['reference'],
      },
    },
    {
      id: 'asset-style-reference',
      type: 'asset-video',
      position: { x: -330, y: -50 },
      data: {
        kind: 'asset-video',
        title: 'Style Reference',
        subtitle: 'product_turntable.mp4',
        accent: '#d946ef',
        generatedCopy: {
          title: generatedCopyReference('templateStyleReference'),
        },
        asset: {
          id: 'style-video',
          kind: 'video',
          filename: 'product_turntable.mp4',
          subtitle: 'Video · 12s',
          url: '/hero/pika-22.mp4',
          thumbUrl: '/hero/kling-3-4k-demo.jpg',
          durationSec: 12,
        },
        sourceHandles: ['video_reference'],
      },
    },
    {
      id: 'prompt-camera',
      type: 'text-prompt',
      position: { x: -330, y: 145 },
      data: {
        kind: 'text-prompt',
        title: 'Camera Movement',
        subtitle: 'camera_move.txt',
        accent: '#38bdf8',
        generatedCopy: {
          title: generatedCopyReference('templateCameraMovement'),
          promptText: generatedCopyReference('templateProductAdCameraPromptText'),
        },
        promptRole: 'camera',
        promptText: 'Smooth cinematic orbit around product, slow push in, premium macro lighting.',
        sourceHandles: ['prompt'],
      },
    },
    {
      id: 'audio-music-01',
      type: 'asset-audio',
      position: { x: -380, y: 350 },
      data: {
        kind: 'asset-audio',
        title: 'Audio Reference',
        subtitle: 'ambient_moody.mp3',
        accent: '#22c55e',
        generatedCopy: {
          title: generatedCopyReference('templateAudioReference'),
        },
        asset: {
          id: 'ambient-music',
          kind: 'audio',
          filename: 'ambient_moody.mp3',
          subtitle: 'Audio · 28s',
          url: WORKSPACE_DEMO_AUDIO_URL,
          durationSec: 28,
        },
        sourceHandles: ['audio'],
      },
    },
    {
      id: 'shot-01',
      type: 'shot',
      position: { x: -20, y: -220 },
      data: {
        kind: 'shot',
        title: 'Shot 01',
        subtitle: 'Hero Reveal',
        accent: '#8b5cf6',
        generatedCopy: {
          title: generatedCopyReference('templateShotName', { index: '01' }),
          subtitle: generatedCopyReference('templateHeroReveal'),
          shotOutputName: generatedCopyReference('templateHeroReveal'),
        },
        shot: shotSettings({ outputName: 'Hero Reveal', modelId: 'kling-3-pro', durationSec: PRODUCT_AD_SHOT_01_DURATION_SEC }),
        targetHandles: ['prompt', 'start_image', 'reference', 'camera', 'previous_shot'],
        sourceHandles: ['video_reference'],
      },
    },
    {
      id: 'output-01',
      type: 'output',
      position: { x: 220, y: -220 },
      data: {
        kind: 'output',
        title: 'Output 01',
        subtitle: '5s · 16:9',
        accent: '#f97316',
        generatedCopy: {
          title: generatedCopyReference('templateOutputName', { index: '01' }),
        },
        output: {
          kind: 'video',
          modelId: 'kling-3-pro',
          modelLabel: 'Kling 3 Pro',
          workflowType: 'image_to_video',
          durationSec: PRODUCT_AD_SHOT_01_DURATION_SEC,
          aspectRatio: '16:9',
          resolution: '1080p',
          createdAt: new Date('2026-06-05T09:00:00.000Z').toISOString(),
          sourceShotId: 'shot-01',
          thumbUrl: '/hero/showcase-kling-3-pro.webp',
          url: '/hero/pika-22.mp4',
          jobId: 'template-output-01',
        },
        targetHandles: ['generated_output'],
        sourceHandles: ['video_reference'],
      },
    },
    {
      id: 'shot-02',
      type: 'shot',
      position: { x: 460, y: -220 },
      data: {
        kind: 'shot',
        title: 'Shot 02',
        subtitle: 'Macro Details',
        accent: '#3b82f6',
        generatedCopy: {
          title: generatedCopyReference('templateShotName', { index: '02' }),
          subtitle: generatedCopyReference('templateMacroDetails'),
          shotOutputName: generatedCopyReference('templateMacroDetails'),
        },
        shot: shotSettings({ outputName: 'Macro Details', modelId: 'veo-3-1', durationSec: PRODUCT_AD_SHOT_02_DURATION_SEC }),
        targetHandles: ['prompt', 'start_image', 'reference', 'camera', 'previous_shot'],
        sourceHandles: ['video_reference'],
      },
    },
    {
      id: 'output-02',
      type: 'output',
      position: { x: 700, y: -220 },
      data: {
        kind: 'output',
        title: 'Output 02',
        subtitle: '8s · 16:9',
        accent: '#3b82f6',
        generatedCopy: {
          title: generatedCopyReference('templateOutputName', { index: '02' }),
        },
        output: {
          kind: 'video',
          modelId: 'veo-3-1',
          modelLabel: 'Veo 3.1',
          workflowType: 'image_to_video',
          durationSec: PRODUCT_AD_SHOT_02_DURATION_SEC,
          aspectRatio: '16:9',
          resolution: '1080p',
          createdAt: new Date('2026-06-05T09:03:00.000Z').toISOString(),
          sourceShotId: 'shot-02',
          thumbUrl: '/hero/showcase-veo-3-1.webp',
          url: '/hero/veo3.mp4',
          hasAudio: true,
          jobId: 'template-output-02',
        },
        targetHandles: ['generated_output'],
        sourceHandles: ['video_reference'],
      },
    },
    {
      id: 'shot-03',
      type: 'shot',
      position: { x: -20, y: 180 },
      data: {
        kind: 'shot',
        title: 'Shot 03',
        subtitle: 'Exploded View',
        accent: '#22c55e',
        generatedCopy: {
          title: generatedCopyReference('templateShotName', { index: '03' }),
          subtitle: generatedCopyReference('templateExplodedView'),
          shotOutputName: generatedCopyReference('templateExplodedView'),
        },
        shot: shotSettings({ outputName: 'Exploded View', modelId: 'veo-3-1', durationSec: 7 }),
        targetHandles: ['prompt', 'start_image', 'reference', 'camera', 'previous_shot'],
        sourceHandles: ['video_reference'],
      },
    },
    {
      id: 'shot-04',
      type: 'shot',
      position: { x: 460, y: 180 },
      data: {
        kind: 'shot',
        title: 'Shot 04',
        subtitle: 'Final Packshot',
        accent: '#f97316',
        generatedCopy: {
          title: generatedCopyReference('templateShotName', { index: '04' }),
          subtitle: generatedCopyReference('templateFinalPackshot'),
          shotOutputName: generatedCopyReference('templateFinalPackshot'),
        },
        shot: shotSettings({ outputName: 'Final Packshot', modelId: 'kling-3-pro', durationSec: 7 }),
        targetHandles: ['prompt', 'start_image', 'reference', 'logo', 'camera', 'previous_shot', 'narration'],
        sourceHandles: ['video_reference'],
      },
    },
    {
      id: 'asset-logo',
      type: 'asset-image',
      position: { x: 700, y: 245 },
      data: {
        kind: 'asset-image',
        title: 'Logo',
        subtitle: 'brand_logo.png',
        accent: '#facc15',
        asset: {
          id: 'brand-logo',
          kind: 'logo',
          filename: 'brand_logo.png',
          subtitle: 'Logo · 1024x1024',
          thumbUrl: '/assets/branding/logo-mark.svg',
          url: '/assets/branding/logo-mark.svg',
        },
        sourceHandles: ['reference'],
      },
    },
    {
      id: 'prompt-voiceover',
      type: 'text-prompt',
      position: { x: 640, y: 25 },
      data: {
        kind: 'text-prompt',
        title: 'Voice Over',
        subtitle: 'vo_final.txt',
        accent: '#14b8a6',
        generatedCopy: {
          title: generatedCopyReference('templateVoiceOver'),
          promptText: generatedCopyReference('templateProductAdVoiceoverPromptText'),
        },
        promptRole: 'narration',
        promptText: 'Precision in motion. A modern chronograph built for every second that matters.',
        sourceHandles: ['prompt'],
      },
    },
  ];

  const edges: WorkspaceGraphEdge[] = [
    createWorkspaceEdge({ source: 'asset-product-image', target: 'shot-01', sourceHandle: 'reference', targetHandle: 'start_image', kind: 'start_image' }),
    createWorkspaceEdge({ source: 'asset-style-reference', target: 'shot-01', sourceHandle: 'video_reference', targetHandle: 'reference', kind: 'reference' }),
    createWorkspaceEdge({ source: 'prompt-camera', target: 'shot-01', sourceHandle: 'prompt', targetHandle: 'camera', kind: 'camera' }),
    createWorkspaceEdge({ source: 'shot-01', target: 'output-01', sourceHandle: 'video_reference', targetHandle: 'generated_output', kind: 'generated_output' }),
    createWorkspaceEdge({ source: 'output-01', target: 'shot-02', sourceHandle: 'video_reference', targetHandle: 'previous_shot', kind: 'previous_shot' }),
    createWorkspaceEdge({ source: 'asset-product-image', target: 'shot-02', sourceHandle: 'reference', targetHandle: 'start_image', kind: 'start_image' }),
    createWorkspaceEdge({ source: 'prompt-camera', target: 'shot-02', sourceHandle: 'prompt', targetHandle: 'camera', kind: 'camera' }),
    createWorkspaceEdge({ source: 'shot-02', target: 'output-02', sourceHandle: 'video_reference', targetHandle: 'generated_output', kind: 'generated_output' }),
    createWorkspaceEdge({ source: 'output-01', target: 'shot-03', sourceHandle: 'video_reference', targetHandle: 'previous_shot', kind: 'previous_shot' }),
    createWorkspaceEdge({ source: 'asset-product-image', target: 'shot-03', sourceHandle: 'reference', targetHandle: 'start_image', kind: 'start_image' }),
    createWorkspaceEdge({ source: 'asset-style-reference', target: 'shot-03', sourceHandle: 'video_reference', targetHandle: 'reference', kind: 'reference' }),
    createWorkspaceEdge({ source: 'prompt-camera', target: 'shot-03', sourceHandle: 'prompt', targetHandle: 'camera', kind: 'camera' }),
    createWorkspaceEdge({ source: 'shot-03', target: 'shot-04', sourceHandle: 'video_reference', targetHandle: 'previous_shot', kind: 'continuity' }),
    createWorkspaceEdge({ source: 'asset-product-image', target: 'shot-04', sourceHandle: 'reference', targetHandle: 'start_image', kind: 'start_image' }),
    createWorkspaceEdge({ source: 'prompt-camera', target: 'shot-04', sourceHandle: 'prompt', targetHandle: 'camera', kind: 'camera' }),
    createWorkspaceEdge({ source: 'asset-logo', target: 'shot-04', sourceHandle: 'reference', targetHandle: 'logo', kind: 'logo' }),
    createWorkspaceEdge({ source: 'prompt-voiceover', target: 'shot-04', sourceHandle: 'prompt', targetHandle: 'narration', kind: 'narration' }),
  ];

  return localizeWorkspaceTemplateGeneratedState({
    id: 'product-ad',
    name: 'Product Ad',
    nodes,
    edges,
    timelineItems: productAdTimeline(),
  }, copy);
}
