import type { RawFalEngineEntry } from './types';
import { createKling3TurboEngine, KLING_3_TURBO_ENDPOINTS } from './kling-3-turbo-shared';

export const KLING_3_TURBO_PRO_ENGINE = createKling3TurboEngine({
  id: 'kling-3-turbo-pro',
  label: 'Kling 3.0 Turbo Pro',
  version: '3.0 Turbo Pro',
  resolution: '1080p',
});

export const KLING_3_TURBO_PRO_FAL_ENGINE_REGISTRY: RawFalEngineEntry[] = [{
  id: 'kling-3-turbo-pro',
  marketingName: 'Kling 3.0 Turbo Pro',
  provider: 'Kling by Kuaishou',
  brandId: 'kling',
  versionLabel: '3.0 Turbo Pro',
  availability: 'limited',
  logoPolicy: 'textOnly',
  billingNote: 'Private fallback contract. Provider cost is capped at $0.140/s until direct Kling pricing is proven lower.',
  engine: KLING_3_TURBO_PRO_ENGINE,
  modes: [
    {
      mode: 't2v',
      falModelId: KLING_3_TURBO_ENDPOINTS['kling-3-turbo-pro'].t2v,
      ui: {
        modes: ['t2v'],
        duration: { options: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], default: 5 },
        resolution: ['1080p'],
        resolutionLocked: true,
        aspectRatio: ['16:9', '9:16', '1:1'],
        notes: 'Native audio is generated by Kling. Single prompts and multi-shot prompts are mutually exclusive.',
      },
    },
    {
      mode: 'i2v',
      falModelId: KLING_3_TURBO_ENDPOINTS['kling-3-turbo-pro'].i2v,
      ui: {
        modes: ['i2v'],
        duration: { options: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], default: 5 },
        resolution: ['1080p'],
        resolutionLocked: true,
        acceptsImageFormats: ['jpg', 'jpeg', 'png'],
        maxUploadMB: 50,
        notes: 'Native audio is generated by Kling. One start image is required.',
      },
    },
  ],
  defaultFalModelId: KLING_3_TURBO_ENDPOINTS['kling-3-turbo-pro'].t2v,
  seo: {
    title: 'Kling 3.0 Turbo Pro',
    description: 'Private Kling 3.0 Turbo Pro fallback contract.',
    canonicalPath: '/models/kling-3-turbo-pro',
  },
  prompts: [],
}];
