import type { EngineCaps } from '../../../types/engines';
import type { RawFalEngineEntry } from './types';

const LUMA_RAY32_DURATION_VALUES = ['5s', '10s'] as const;
const LUMA_RAY32_RESOLUTION_VALUES = ['540p', '720p', '1080p'] as const;
const LUMA_RAY32_ASPECT_RATIO_VALUES = ['9:16', '3:4', '1:1', '4:3', '16:9', '21:9'] as const;
const LUMA_RAY32_EDIT_STRENGTH_VALUES = [
  'adhere_1',
  'adhere_2',
  'adhere_3',
  'flex_1',
  'flex_2',
  'flex_3',
  'reimagine_1',
  'reimagine_2',
  'reimagine_3',
] as const;

const LUMA_RAY32_ENGINE: EngineCaps = {
  id: 'lumaRay3_2',
  label: 'Luma Ray 3.2',
  provider: 'Luma AI',
  version: 'Ray 3.2',
  status: 'live',
  latencyTier: 'standard',
  queueDepth: 0,
  region: 'global',
  modes: ['t2v', 'i2v', 'v2v', 'reframe'],
  maxDurationSec: 10,
  resolutions: [...LUMA_RAY32_RESOLUTION_VALUES],
  aspectRatios: [...LUMA_RAY32_ASPECT_RATIO_VALUES],
  fps: [24],
  audio: false,
  upscale4k: false,
  extend: false,
  motionControls: true,
  keyframes: true,
  params: {},
  inputLimits: {
    imageMaxMB: 50,
    videoMaxMB: 200,
    videoMaxDurationSec: 30,
    promptMaxChars: 6000,
    promptMaxCharsSource: 'official',
  },
  inputSchema: {
    required: [
      {
        id: 'prompt',
        type: 'text',
        label: 'Prompt',
        modes: ['t2v', 'i2v', 'v2v', 'reframe'],
        requiredInModes: ['t2v', 'i2v', 'v2v', 'reframe'],
      },
      {
        id: 'image_url',
        type: 'image',
        label: 'Start frame',
        description: 'Use one still image to anchor the opening frame.',
        modes: ['i2v'],
        requiredInModes: ['i2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'video_url',
        type: 'video',
        label: 'Source video',
        description: 'Video to modify or reframe with Luma Ray 3.2.',
        modes: ['v2v', 'reframe'],
        requiredInModes: ['v2v', 'reframe'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
    ],
    optional: [
      {
        id: 'duration',
        type: 'enum',
        label: 'Duration',
        values: [...LUMA_RAY32_DURATION_VALUES],
        default: '5s',
        modes: ['t2v', 'i2v'],
      },
      {
        id: 'aspect_ratio',
        type: 'enum',
        label: 'Aspect ratio',
        values: [...LUMA_RAY32_ASPECT_RATIO_VALUES],
        default: '16:9',
        modes: ['t2v', 'i2v', 'reframe'],
      },
      {
        id: 'resolution',
        type: 'enum',
        label: 'Resolution',
        values: [...LUMA_RAY32_RESOLUTION_VALUES],
        default: '720p',
        modes: ['t2v', 'i2v', 'v2v', 'reframe'],
      },
      {
        id: 'loop',
        type: 'boolean',
        label: 'Loop video',
        default: false,
        modes: ['t2v', 'i2v'],
      },
      {
        id: 'hdr',
        type: 'boolean',
        label: 'HDR',
        description: 'HDR requires 720p or 1080p and is not compatible with 10s or loop.',
        default: false,
        modes: ['t2v', 'i2v', 'v2v'],
      },
      {
        id: 'exr_export',
        type: 'boolean',
        label: 'EXR export',
        description: 'Exports an EXR alongside HDR outputs for color-grading workflows.',
        default: false,
        modes: ['t2v', 'i2v', 'v2v'],
      },
      {
        id: 'end_image_url',
        type: 'image',
        label: 'End frame',
        modes: ['i2v'],
        minCount: 1,
        maxCount: 1,
        source: 'either',
      },
      {
        id: 'keyframes',
        type: 'image',
        label: 'Keyframes',
        description: 'Pin guide frames at explicit frame indexes for Ray 3.2 control.',
        modes: ['i2v', 'v2v'],
        minCount: 1,
        maxCount: 64,
        source: 'either',
      },
      {
        id: 'keyframe_indexes',
        type: 'text',
        label: 'Keyframe indexes',
        description: 'Comma-separated frame indexes matching the keyframe list.',
        modes: ['i2v', 'v2v'],
      },
      {
        id: 'edit_strength',
        type: 'enum',
        label: 'Edit strength',
        description: 'Controls how much the output adheres to the source clip.',
        values: [...LUMA_RAY32_EDIT_STRENGTH_VALUES],
        default: 'flex_2',
        modes: ['v2v'],
      },
      {
        id: 'auto_controls',
        type: 'boolean',
        label: 'Auto controls',
        description: 'Let Luma infer pose, depth, trajectory, normals, and face controls.',
        default: true,
        modes: ['v2v'],
      },
      {
        id: 'controls',
        type: 'text',
        label: 'Advanced controls',
        description: 'JSON for pose, depth, normals, trajectory, or face controls.',
        modes: ['v2v'],
      },
      {
        id: 'source_position',
        type: 'text',
        label: 'Source position',
        description: 'JSON normalized rectangle for video_reframe placement.',
        modes: ['reframe'],
      },
    ],
    constraints: {
      supportedFormats: ['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'webm', 'm4v', 'gif'],
      maxImageSizeMB: 50,
      maxVideoSizeMB: 200,
    },
  },
  pricing: {
    unit: 'video',
    currency: 'USD',
    notes:
      'Direct Luma Ray 3.2 pricing varies by duration, resolution and dynamic range. HDR is 2x SDR; HDR + EXR is 3x SDR.',
  },
  updatedAt: '2026-06-09T00:00:00Z',
  ttlSec: 600,
  providerMeta: {
    provider: 'luma',
    modelSlug: 'ray-3.2',
  },
  availability: 'available',
  brandId: 'luma',
};

export const LUMA_RAY_3_2_FAL_ENGINE_REGISTRY: RawFalEngineEntry[] = [
  {
    id: 'lumaRay3_2',
    modelSlug: 'luma-ray-3-2',
    marketingName: 'Luma Ray 3.2',
    cardTitle: 'Ray 3.2',
    provider: 'Luma AI',
    brandId: 'luma',
    family: 'luma',
    versionLabel: 'Ray 3.2',
    availability: 'available',
    logoPolicy: 'logoAllowed',
    engine: LUMA_RAY32_ENGINE,
    modes: [
      {
        mode: 't2v',
        falModelId: 'luma/agent/ray/v3.2/text-to-video',
        ui: {
          modes: ['t2v'],
          duration: { options: [...LUMA_RAY32_DURATION_VALUES], default: '5s' },
          resolution: [...LUMA_RAY32_RESOLUTION_VALUES],
          aspectRatio: [...LUMA_RAY32_ASPECT_RATIO_VALUES],
          audioToggle: false,
          notes: 'Direct Luma Ray 3.2 text-to-video with HDR, EXR and multi-keyframe fallback metadata.',
        },
      },
      {
        mode: 'i2v',
        falModelId: 'luma/agent/ray/v3.2/image-to-video',
        ui: {
          modes: ['i2v'],
          duration: { options: [...LUMA_RAY32_DURATION_VALUES], default: '5s' },
          resolution: [...LUMA_RAY32_RESOLUTION_VALUES],
          aspectRatio: [...LUMA_RAY32_ASPECT_RATIO_VALUES],
          acceptsImageFormats: ['jpg', 'jpeg', 'png', 'webp'],
          maxUploadMB: 50,
          audioToggle: false,
          notes: 'Animate a start frame, optional end frame, or multi-keyframe shot through direct Luma Ray 3.2.',
        },
      },
      {
        mode: 'v2v',
        falModelId: 'luma/agent/ray/v3.2/video-to-video',
        ui: {
          modes: ['v2v'],
          resolution: [...LUMA_RAY32_RESOLUTION_VALUES],
          notes: 'Modify a source clip with Ray 3.2 edit strength, auto controls, guide frames, HDR and EXR options.',
        },
      },
      {
        mode: 'reframe',
        falModelId: 'luma/agent/ray/v3.2/reframe',
        ui: {
          modes: ['reframe'],
          resolution: [...LUMA_RAY32_RESOLUTION_VALUES],
          aspectRatio: [...LUMA_RAY32_ASPECT_RATIO_VALUES],
          notes: 'Reframe an existing clip to a new aspect ratio through Luma Ray 3.2 outpainting.',
        },
      },
    ],
    defaultFalModelId: 'luma/agent/ray/v3.2/text-to-video',
    seo: {
      title: 'Luma Ray 3.2 - Direct AI Video Generation',
      description:
        'Use Luma Ray 3.2 in MaxVideoAI Studio for direct cinematic video generation, image-to-video, video editing, reframing, HDR, EXR, and keyframe-guided control.',
      canonicalPath: '/models/luma-ray-3-2',
    },
    type: 'Text, image, edit, reframe',
    seoText:
      'Luma Ray 3.2 brings direct Luma video generation, source-video editing, reframing, HDR, EXR export, and keyframe control into MaxVideoAI Studio.',
    demoUrl: '/hero/luma-dream.mp4',
    media: {
      videoUrl: '/hero/luma-dream.mp4',
      imagePath: '/hero/luma-dream.jpg',
      altText: 'Cinematic demo render from Luma Ray 3.2',
    },
    prompts: [
      {
        title: 'Greenhouse dolly',
        prompt: 'A slow dolly shot through a misty greenhouse at sunrise, dew on glass, cinematic HDR lighting.',
        mode: 't2v',
      },
    ],
    surfaces: {
      modelPage: { indexable: false, includeInSitemap: false },
      examples: { includeInFamilyResolver: false, includeInFamilyCopy: false },
      compare: { suggestOpponents: ['veo-3-1', 'kling-3-pro', 'sora-2'], publishedPairs: [], includeInHub: false },
      app: { enabled: true, discoveryRank: 2, variantGroup: 'luma-ray', variantLabel: 'Ray 3.2' },
      pricing: { includeInEstimator: true },
    },
  },
];
