const en = {
  optionalAudio: 'Optional',
  includedAudio: 'Always on',
  noAudio: 'No audio',
  authPending: 'Checking account…',
  close: 'Close',
  compare: 'Compare',
  compareIntro: 'Exact prices recalculated from the settings and references currently in the composer.',
  currentSetup: 'Your model',
  alternatives: 'Compatible alternatives',
  sameSettings: 'Same settings',
  adjustedSettings: 'Adjusted settings',
  reviewAlternative: 'Select',
  browseAll: 'Explore all models',
  backToAlternatives: 'All alternatives',
  noAlternatives: 'No other model can reproduce this setup without changing its required inputs.',
  switchPreserved: (count: number) =>
    `${count} incompatible ${count === 1 ? 'reference stays' : 'references stay'} with the previous model configuration.`,
  oneChange: '1 adjustment',
  manyChanges: 'adjustments',
  saved: 'Previous settings',
  title: 'Compare models',
  current: 'Current',
  candidate: 'Selected',
  choose: 'Choose a model',
  cancel: 'Cancel',
  apply: 'Apply model',
  configurationOnly: 'Apply configuration',
  configurationReason: 'Add the required inputs before generating.',
  equivalent: 'Same conditions',
  adapted: 'Adapted settings',
  changes: 'Changes',
  references: 'References',
  preserved: 'Saved with previous settings',
  empty: 'No previous settings yet.',
  restore: 'Review',
  remove: 'Remove',
  unavailable: 'Model unavailable',
  invalid: 'This configuration cannot be read. Remove it to free its space.',
  oversized: 'Configuration storage is full. Remove a saved configuration and try again.',
  incomplete: 'Finish uploading or replace incomplete references before switching.',
  account: 'Sign in to preserve configurations.',
  clear: 'Remove unreadable configurations',
  memoryShort: 'Page only',
  memory: 'Saved in memory for this page only. Browser storage is unavailable.',
  loading: 'Calculating…',
  quoteError: 'Price unavailable',
  retry: 'Retry',
  noQuote: 'No quote',
  details: 'Details',
  on: 'On',
  off: 'Off',
  inactive: 'Inactive',
  items: 'items',
  characters: 'characters',
  image: 'Image',
  video: 'Video',
  audio: 'Audio',
  start: 'Start frame',
  end: 'End frame',
  primary: 'Source',
  reference: 'Reference',
  frame: 'Frame',
  generic: 'Media',
  unknown: 'Other role',
  'subject-frontal': 'Subject · front',
  'subject-reference': 'Subject · reference',
  'subject-video': 'Subject · video',
  reasons: {
    'not-stable': 'This configuration cannot be prepared.',
    'unsupported-workflow': 'This workflow is unavailable for the selected model.',
    'uploading-reference': 'Wait for reference uploads to finish.',
    'invalid-reference': 'Saved references no longer fit this model. Your configuration is preserved.',
    'prompt-too-long': 'The prompt exceeds this model’s limit. It remains intact.',
    'missing-input': 'Required inputs are missing.',
    'invalid-input': 'Review the required media before generating.',
  },
  fields: {
    mode: 'Mode',
    effectiveDurationSec: 'Duration',
    durationSec: 'Duration',
    durationOption: 'Duration option',
    numFrames: 'Frames',
    resolution: 'Resolution',
    aspectRatio: 'Ratio',
    fps: 'FPS',
    iterations: 'Quantity',
    seedLocked: 'Locked seed',
    seed: 'Seed',
    loop: 'Loop',
    audio: 'Audio',
    cameraFixed: 'Fixed camera',
    safetyChecker: 'Safety check',
    supportsAudioToggle: 'Audio',
    multiPromptEnabled: 'Multi-shot',
    multiPromptScenes: 'Scenes',
    shotType: 'Shot type',
    cfgScale: 'CFG',
    voiceControlEnabled: 'Voice control',
    voiceIdsInput: 'Voices',
    negativePrompt: 'Negative prompt',
    prompt: 'Prompt',
    klingElements: 'Subjects',
    resolutionSupported: 'Adjustable resolution',
    aspect_ratioSupported: 'Adjustable ratio',
  },
};
type Copy = typeof en;
const fr: Copy = {
  ...en,
  optionalAudio: 'Au choix',
  includedAudio: 'Toujours activé',
  noAudio: 'Sans audio',
  authPending: 'Vérification du compte…',
  close: 'Fermer',
  compare: 'Comparer',
  compareIntro: 'Prix exacts recalculés depuis les réglages et références présents dans le composeur.',
  currentSetup: 'Votre modèle',
  alternatives: 'Alternatives compatibles',
  sameSettings: 'Mêmes réglages',
  adjustedSettings: 'Réglages adaptés',
  reviewAlternative: 'Choisir',
  browseAll: 'Explorer tous les modèles',
  backToAlternatives: 'Toutes les alternatives',
  noAlternatives: 'Aucun autre modèle ne peut reprendre cette configuration sans modifier ses entrées requises.',
  switchPreserved: (count: number) =>
    `${count} ${count === 1 ? 'référence incompatible reste' : 'références incompatibles restent'} dans la configuration du modèle précédent.`,
  oneChange: '1 ajustement',
  manyChanges: 'ajustements',
  saved: 'Réglages précédents',
  title: 'Comparer les modèles',
  current: 'Actuel',
  candidate: 'Sélection',
  choose: 'Choisir un modèle',
  cancel: 'Annuler',
  apply: 'Appliquer le modèle',
  configurationOnly: 'Appliquer la configuration',
  configurationReason: 'Ajoutez les entrées requises avant de générer.',
  equivalent: 'Mêmes conditions',
  adapted: 'Réglages adaptés',
  changes: 'Modifications',
  references: 'Références',
  preserved: 'Conservées avec les réglages précédents',
  empty: 'Aucun réglage précédent.',
  restore: 'Examiner',
  remove: 'Retirer',
  unavailable: 'Modèle indisponible',
  invalid: 'Cette configuration est illisible. Retirez-la pour libérer sa place.',
  oversized: 'Stockage des configurations plein. Retirez une configuration puis réessayez.',
  incomplete: 'Terminez les imports ou remplacez les références incomplètes avant de changer.',
  account: 'Connectez-vous pour conserver les configurations.',
  clear: 'Retirer les configurations illisibles',
  memoryShort: 'Cette page',
  memory: 'Conservation en mémoire pour cette page uniquement. Le stockage du navigateur est indisponible.',
  loading: 'Calcul…',
  quoteError: 'Prix indisponible',
  retry: 'Réessayer',
  noQuote: 'Sans devis',
  details: 'Détails',
  on: 'Oui',
  off: 'Non',
  inactive: 'Inactif',
  items: 'éléments',
  characters: 'caractères',
  image: 'Image',
  video: 'Vidéo',
  audio: 'Audio',
  start: 'Image de départ',
  end: 'Image de fin',
  primary: 'Source',
  reference: 'Référence',
  frame: 'Image clé',
  generic: 'Média',
  unknown: 'Autre rôle',
  'subject-frontal': 'Sujet · face',
  'subject-reference': 'Sujet · référence',
  'subject-video': 'Sujet · vidéo',
  reasons: {
    'not-stable': 'Impossible de préparer cette configuration.',
    'unsupported-workflow': 'Ce mode est indisponible pour le modèle choisi.',
    'uploading-reference': 'Attendez la fin des imports.',
    'invalid-reference':
      'Des références enregistrées ne conviennent plus à ce modèle. La configuration est conservée.',
    'prompt-too-long': 'Le prompt dépasse la limite de ce modèle. Son texte reste intact.',
    'missing-input': 'Des entrées requises manquent.',
    'invalid-input': 'Vérifiez les médias requis avant de générer.',
  },
  fields: {
    mode: 'Mode',
    effectiveDurationSec: 'Durée',
    durationSec: 'Durée',
    durationOption: 'Option de durée',
    numFrames: 'Images',
    resolution: 'Résolution',
    aspectRatio: 'Format',
    fps: 'FPS',
    iterations: 'Quantité',
    seedLocked: 'Seed verrouillée',
    seed: 'Seed',
    loop: 'Boucle',
    audio: 'Son',
    cameraFixed: 'Caméra fixe',
    safetyChecker: 'Contrôle de sécurité',
    supportsAudioToggle: 'Son',
    multiPromptEnabled: 'Multi-plan',
    multiPromptScenes: 'Plans',
    shotType: 'Type de plan',
    cfgScale: 'CFG',
    voiceControlEnabled: 'Contrôle vocal',
    voiceIdsInput: 'Voix',
    negativePrompt: 'Prompt négatif',
    prompt: 'Prompt',
    klingElements: 'Sujets',
    resolutionSupported: 'Résolution modifiable',
    aspect_ratioSupported: 'Format modifiable',
  },
};
const es: Copy = {
  ...en,
  optionalAudio: 'Opcional',
  includedAudio: 'Siempre activado',
  noAudio: 'Sin audio',
  authPending: 'Verificando la cuenta…',
  close: 'Cerrar',
  compare: 'Comparar',
  compareIntro: 'Precios exactos recalculados desde los ajustes y referencias actuales del compositor.',
  currentSetup: 'Configuración actual',
  alternatives: 'Alternativas compatibles',
  sameSettings: 'Mismos ajustes',
  adjustedSettings: 'Ajustes adaptados',
  reviewAlternative: 'Revisar',
  browseAll: 'Explorar todos los modelos',
  backToAlternatives: 'Todas las alternativas',
  noAlternatives: 'Ningún otro modelo puede reproducir esta configuración sin cambiar sus entradas obligatorias.',
  switchPreserved: (count: number) =>
    `${count} ${count === 1 ? 'referencia incompatible permanece' : 'referencias incompatibles permanecen'} en la configuración del modelo anterior.`,
  oneChange: '1 ajuste',
  manyChanges: 'ajustes',
  saved: 'Ajustes anteriores',
  title: 'Comparar modelos',
  current: 'Actual',
  candidate: 'Selección',
  choose: 'Elegir modelo',
  cancel: 'Cancelar',
  apply: 'Aplicar modelo',
  configurationOnly: 'Aplicar configuración',
  configurationReason: 'Añade las entradas necesarias antes de generar.',
  equivalent: 'Mismas condiciones',
  adapted: 'Ajustes adaptados',
  changes: 'Cambios',
  references: 'Referencias',
  preserved: 'Guardadas en configuraciones',
  empty: 'Todavía no hay configuraciones guardadas.',
  restore: 'Revisar',
  remove: 'Quitar',
  unavailable: 'Modelo no disponible',
  invalid: 'Esta configuración no se puede leer. Quítala para liberar espacio.',
  oversized: 'Almacenamiento de configuraciones lleno. Quita una configuración e inténtalo de nuevo.',
  incomplete: 'Termina las cargas o reemplaza las referencias incompletas antes de cambiar.',
  account: 'Inicia sesión para conservar configuraciones.',
  clear: 'Quitar configuraciones ilegibles',
  memoryShort: 'Esta página',
  memory: 'Guardado en memoria solo para esta página. El almacenamiento del navegador no está disponible.',
  loading: 'Calculando…',
  quoteError: 'Precio no disponible',
  retry: 'Reintentar',
  noQuote: 'Sin presupuesto',
  details: 'Detalles',
  on: 'Sí',
  off: 'No',
  inactive: 'Inactivo',
  items: 'elementos',
  characters: 'caracteres',
  video: 'Vídeo',
  start: 'Imagen inicial',
  end: 'Imagen final',
  primary: 'Fuente',
  reference: 'Referencia',
  frame: 'Fotograma',
  generic: 'Medio',
  unknown: 'Otro rol',
  'subject-frontal': 'Sujeto · frontal',
  'subject-reference': 'Sujeto · referencia',
  'subject-video': 'Sujeto · vídeo',
  reasons: {
    'not-stable': 'No se puede preparar esta configuración.',
    'unsupported-workflow': 'Este modo no está disponible para el modelo seleccionado.',
    'uploading-reference': 'Espera a que terminen las cargas.',
    'invalid-reference': 'Algunas referencias guardadas ya no son compatibles. La configuración se conserva.',
    'prompt-too-long': 'El prompt supera el límite del modelo. El texto se conserva.',
    'missing-input': 'Faltan entradas necesarias.',
    'invalid-input': 'Revisa los medios necesarios antes de generar.',
  },
  fields: {
    mode: 'Modo',
    effectiveDurationSec: 'Duración',
    durationSec: 'Duración',
    durationOption: 'Opción de duración',
    numFrames: 'Fotogramas',
    resolution: 'Resolución',
    aspectRatio: 'Formato',
    fps: 'FPS',
    iterations: 'Cantidad',
    seedLocked: 'Seed bloqueada',
    seed: 'Seed',
    loop: 'Bucle',
    audio: 'Audio',
    cameraFixed: 'Cámara fija',
    safetyChecker: 'Control de seguridad',
    supportsAudioToggle: 'Audio',
    multiPromptEnabled: 'Multiplano',
    multiPromptScenes: 'Planos',
    shotType: 'Tipo de plano',
    cfgScale: 'CFG',
    voiceControlEnabled: 'Control de voz',
    voiceIdsInput: 'Voces',
    negativePrompt: 'Prompt negativo',
    prompt: 'Prompt',
    klingElements: 'Sujetos',
    resolutionSupported: 'Resolución ajustable',
    aspect_ratioSupported: 'Formato ajustable',
  },
};
export function workspaceModelReviewCopy(locale: string): Copy {
  return locale.startsWith('fr') ? fr : locale.startsWith('es') ? es : en;
}
export function workspaceModelSettingLabel(field: string, copy: Copy): string {
  return (
    copy.fields[field as keyof Copy['fields']] ??
    field.replace(/^extraInputValues\./, '').replaceAll('_', ' ')
  );
}
export function workspaceModelSettingValue(value: unknown, copy: Copy): string {
  if (value === undefined || value === null) return '—';
  if (typeof value === 'boolean') return value ? copy.on : copy.off;
  if (Array.isArray(value)) return `${value.length} ${copy.items}`;
  if (typeof value === 'object') return `${Object.keys(value).length} ${copy.items}`;
  const result = String(value);
  return result.length > 60 ? `${result.length} ${copy.characters}` : result;
}
