name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: corepack prepare pnpm@10.18.2 --activate
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - name: Test (only if tests exist)
        if: ${{ hashFiles('vitest.config.*', 'jest.config.*', '**/__tests__/**') != '' }}
        run: pnpm test -- --run
      - run: pnpm build
