import Image from 'next/image';
import { getMcpIntegration } from '@/lib/mcp-integration-registry';
import { Plus, ShieldCheck } from 'lucide-react';
import type { AppLocale } from '@/i18n/locales';
import { getMcpEditorialCopy } from '@/components/marketing/mcp/mcp-editorial-copy';
import type { McpCompatibilityClientEvidence } from '../../mcp/_lib/mcp-compatibility';
import { formatMcpCheckpointDate } from '../../mcp/_lib/mcp-compatibility';
import { MCP_PRODUCTION_RESOURCE_URL } from '@/server/mcp/config';
import type { IntegrationPageCopy } from '../_lib/integration-copy';
import { IntegrationInstallCopy } from './IntegrationInstallCopy.client';
export function IntegrationSetupSection({compatibility,copy,locale}: {compatibility:McpCompatibilityClientEvidence;copy:IntegrationPageCopy;locale:AppLocale}) {
 const editorial=getMcpEditorialCopy(locale);
 return <section id="setup" className="mcp-setup mcp-section"><div className="container-page"><div className="mcp-section-heading"><div><p className="mcp-eyebrow">{copy.setup.eyebrow}</p><h2>{copy.setup.title}</h2></div><p>{copy.setup.intro}</p></div><div className="mcp-setup-grid"><div>{copy.setup.hostGuides.map((guide,index)=>{const evidence=compatibility.hosts.find(host=>host.id===guide.hostId);if(!evidence)return null;return <details key={guide.hostId} className="mcp-host-guide" name="mcp-host-guide" open={index===0}><summary><span><small>{evidence.hostLabel}</small>{guide.title}</span><Plus size={20}/></summary><div className="mcp-host-guide-body"><p>{guide.intro}</p>{copy.client === 'openclaw' && getMcpIntegration('openclaw').store.status === 'listed' ? <a className="mcp-text-link" href="https://clawhub.ai/camgraphe/skills/maxvideoai" target="_blank" rel="noreferrer">{locale === 'fr' ? 'Voir le skill MaxVideoAI sur ClawHub' : locale === 'es' ? 'Ver el skill MaxVideoAI en ClawHub' : 'View the MaxVideoAI skill on ClawHub'} ↗</a> : null}<ol className="mcp-setup-steps">{guide.steps.map((step,i)=><li key={step.title}><span className="mcp-step-index">0{i+1}</span><div><h3>{step.title}</h3><p>{step.body}</p>{step.proof?<figure><Image src={step.proof.src} alt={step.proof.alt} width={576} height={384} sizes="(min-width: 1024px) 45vw, 90vw" loading="lazy" className="h-auto w-full"/><figcaption>{step.proof.caption}</figcaption></figure>:null}</div></li>)}</ol>{guide.setupValues.length>0?<dl className="mcp-setup-values">{guide.setupValues.map(item=><div key={item.label}><dt>{item.label}</dt><dd><code>{item.value}</code></dd></div>)}</dl>:null}{guide.commands.length>0?<div className="mcp-commands"><p>{guide.commandLabel}</p>{guide.commands.map(command=><pre key={command}><code>{command}</code></pre>)}</div>:null}<IntegrationInstallCopy copy={copy.setup.installAction} instruction={guide.installInstruction} resourceUrl={MCP_PRODUCTION_RESOURCE_URL}/>{guide.authTrigger?<p className="mcp-host-limitation">{guide.authTrigger}</p>:null}<p className="mcp-host-limitation">{guide.limitation}</p><details className="mcp-evidence-details"><summary>{editorial.verified}<Plus size={16}/></summary><p>{copy.compatibility.statuses[guide.hostId]}</p><p>{copy.compatibility.checkpointLabel}: {formatMcpCheckpointDate(locale,evidence.lastChecked)}</p><p>{copy.compatibility.machineStatusLabel}: <code>{evidence.status}</code></p></details></div></details>;})}</div><aside className="mcp-authorization"><ShieldCheck size={29} strokeWidth={1.4}/><p className="mcp-eyebrow">{editorial.account}</p><h3>{copy.setup.oauthTitle}</h3><p>{copy.setup.oauthBody}</p><ol>{copy.setup.oauthSteps.map((step,index)=><li key={step}><span>0{index+1}</span>{step}</li>)}</ol><div className="mcp-account-path"><span>{copy.clientLabel}</span><span>→</span><strong>maxvideoai.com</strong></div></aside></div></div></section>;
}
