import type { AppLocale } from '@/i18n/locales';

const COPY = {
  en: { intro: 'See what each model can create. Compare quality, controls and price.', context: 'How to choose', examples: 'See the models in action', galleryNote: 'Independent examples, with different prompts and settings.', allExamples: 'Explore examples', watch: 'Watch video', empty: 'No published video for this model yet. Explore the available examples.', scoreTitle: 'Where each model stands out', moreScores: 'Explore all criteria', specs: 'Formats, inputs and controls', moreSpecs: 'All technical details', pricing: 'What will your video cost?', priceNote: 'Compare prices by resolution. The final quote depends on your duration, mode and settings.', criteria: 'Criterion', audio: 'Audio', profile: 'Model details' },
  fr: { intro: 'Voyez ce que chaque modèle peut créer. Comparez la qualité, les réglages et le prix.', context: 'Les repères pour choisir', examples: 'Voyez les modèles à l’œuvre', galleryNote: 'Exemples indépendants, avec des prompts et des réglages différents.', allExamples: 'Explorer les exemples', watch: 'Voir la vidéo', empty: 'Pas encore de vidéo publiée pour ce modèle. Découvrez les exemples disponibles.', scoreTitle: 'Les points forts de chaque modèle', moreScores: 'Explorer tous les critères', specs: 'Formats, références et réglages', moreSpecs: 'Toutes les caractéristiques', pricing: 'Combien coûtera votre vidéo ?', priceNote: 'Comparez les prix selon la résolution. Le devis final dépend de la durée, du mode et de vos réglages.', criteria: 'Critère', audio: 'Audio', profile: 'Fiche du modèle' },
  es: { intro: 'Mira lo que puede crear cada modelo. Compara calidad, ajustes y precio.', context: 'Claves para elegir', examples: 'Mira los modelos en acción', galleryNote: 'Ejemplos independientes, con prompts y ajustes distintos.', allExamples: 'Explorar ejemplos', watch: 'Ver video', empty: 'Aún no hay un video publicado para este modelo. Explora los ejemplos disponibles.', scoreTitle: 'En qué destaca cada modelo', moreScores: 'Explorar todos los criterios', specs: 'Formatos, referencias y ajustes', moreSpecs: 'Todas las características', pricing: '¿Cuánto costará tu video?', priceNote: 'Compara los precios por resolución. La cotización final depende de la duración, el modo y tus ajustes.', criteria: 'Criterio', audio: 'Audio', profile: 'Detalles del modelo' },
};
export function getCompareEditorialCopy(locale: AppLocale) { return COPY[locale]; }


export function getCompareDetailActions(locale: AppLocale) {
  return {
    en: { more: 'Compare the {count} other criteria', fewer: 'Hide additional criteria', shown: '{shown} of {total} criteria shown', allSpecs: 'Compare all {count} specifications', closeSpecs: 'Close the full specification table', specHint: 'Check references, audio, camera controls and output formats.', priceLink: 'Explore all prices', pricingNote: 'Your settings. Your quote. Before you generate.', faqCount: '{count} questions to help you choose', faqHint: 'Open a question to read the answer. One answer at a time.', jump: 'Jump to the details', examples: 'Watch examples', scores: 'Compare the scores', specs: 'Check the specifications', pricing: 'Compare prices' },
    fr: { more: 'Comparer les {count} autres critères', fewer: 'Masquer les critères supplémentaires', shown: '{shown} critères affichés sur {total}', allSpecs: 'Comparer les {count} caractéristiques', closeSpecs: 'Refermer le tableau complet', specHint: 'Vérifiez les références, l’audio, la caméra et les formats de sortie.', priceLink: 'Voir tous les tarifs', pricingNote: 'Vos réglages. Votre prix. Avant de générer.', faqCount: '{count} questions pour vous aider à choisir', faqHint: 'Ouvrez une question pour lire la réponse. Une réponse à la fois.', jump: 'Accéder aux détails', examples: 'Voir les exemples', scores: 'Comparer les notes', specs: 'Vérifier les caractéristiques', pricing: 'Comparer les prix' },
    es: { more: 'Comparar los otros {count} criterios', fewer: 'Ocultar los criterios adicionales', shown: '{shown} de {total} criterios visibles', allSpecs: 'Comparar las {count} especificaciones', closeSpecs: 'Cerrar la tabla completa', specHint: 'Revisa las referencias, el audio, la cámara y los formatos de salida.', priceLink: 'Ver todos los precios', pricingNote: 'Tus ajustes. Tu precio. Antes de generar.', faqCount: '{count} preguntas para ayudarte a elegir', faqHint: 'Abre una pregunta para leer la respuesta. Una respuesta a la vez.', jump: 'Ir a los detalles', examples: 'Ver ejemplos', scores: 'Comparar las calificaciones', specs: 'Revisar las especificaciones', pricing: 'Comparar precios' },
  }[locale];
}
